### ISSUE TITLE
betweennessCentrality() off by 1

### ISSUE THREAD

**Issue by mktonn** [cytoscape/cytoscape.js#1032]
I was using the function betweennessCentrality() for the following (undirected) network:

cy.add([
   {group: "nodes", data: {id: "n0", name: "0"}},
   {group: "nodes", data: {id: "n1", name: "1"}},
   {group: "nodes", data: {id: "n2", name: "2"}},
   {group: "nodes", data: {id: "n3", name: "3"}},
   {group: "nodes", data: {id: "n4", name: "4"}}
   ]);

cy.add([  
   {group: "edges", data: {id: "e0", source: "n0", target: "n1"}},
   {group: "edges", data: {id: "e1", source: "n1", target: "n2"}},
   {group: "edges", data: {id: "e2", source: "n1", target: "n4"}},
   {group: "edges", data: {id: "e3", source: "n2", target: "n3"}},
   {group: "edges", data: {id: "e4", source: "n3", target: "n4"}}
]);

and the function was calculating a betweenness of 8 for n1, but shouldn't it be 7?
Thanks!

**Comment by maxkfranz** [comment]
The author of that function will take a look at it as soon as he can.

**Comment by maxkfranz** [comment]
@mktonn In the meantime, I have verified that this function works as correctly on other externally documented inputs.

**Comment by ayhun** [comment]
I implemented this method directly from the algorithm at the 10th page of Brandes' paper on centrality http://algo.uni-konstanz.de/publications/b-fabc-01.pdf . 
![image](https://cloud.githubusercontent.com/assets/6255734/9657175/60f592e6-5247-11e5-9371-e43fb40e7785.png)

I checked the code with the algorithm on this paper several times and verified that the code is 1-1 consistent with the algorithm. I tested this with several graphs and observed that this "+1" error only happens very rarely on the node that has the highest centrality. Sorry I couldn't be more helpful since I too couldn't resolve how this special case occurs. I will look further and let you know if I can identify an error in the code but for now I can only advise you to use the normalized version of the algorithm.

**Comment by maxkfranz** [comment]
@mktonn @ayhun I tried refactoring and debugging the existing code.  That revealed nothing.

I then rewrote the function from scratch:

```
'use strict';

var is = require('../../is');

var elesfn = ({

  // Implemented from the algorithm in the paper "On Variants of Shortest-Path Betweenness Centrality and their Generic Computation" by Ulrik Brandes
  betweennessCentrality: function( options ){
    var eles = this;

    options = options || {};

    var weightFn = options.weight ? options.weight : function(){ return 1; };

    var defineSetterFn = function( defaultVal, onSet ){
      var fn = function( t, val ){
        if( fn[ t.id() ] === undefined ){
          fn[ t.id() ] = defaultVal;
        }

        if( val !== undefined ){
          fn[ t.id() ] = val;

          if( onSet ){ onSet( val ); }
        }

        return fn[ t.id() ];
      };

      return fn;
    };

    var max = -Infinity;
    var Cb = defineSetterFn( 0, function( val ){
      if( val > max ){ max = val; }
    } );

    var V = this.nodes();

    V.forEach(function( s ){

      var S = [];

      var P = function( w, toAdd ){
        if( !P[ w.id() ] ){
          P[ w.id() ] = [];
        }

        if( toAdd !== undefined ){
          P[ w.id() ].push( toAdd );
        }

        return P[ w.id() ];
      };

      var sigma = defineSetterFn( 0 );

      sigma( s, 1 );

      var d = defineSetterFn( -1 );

      d( s, 0 );

      var Q = [];

      Q.push( s );

      while( Q.length > 0 ){
        var v = Q.shift();

        S.push( v );

        var neighborhood = options.directed ? v.outgoers() : v.openNeighborhood();

        neighborhood.nodes().forEach(function( w ){
          var edges = options.directed ? v.edgesTo(w) : v.edgesWith(w);
          var max = edges.max( function( edge ){
            return weightFn.apply( edge, [edge] );
          } );
          var weight = max.value;
          var edge = max.ele;

          if( d(w) < 0 ){
            Q.push( w );
            d( w, d(v) + weight );
          }

          if( d(w) === d(v) + weight ){
            sigma( w, sigma(w) + sigma(v) );
            P( w, v );
          }
        });
      }

      var delta = defineSetterFn( 0 );

      while( S.length > 0 ){
        var w = S.pop();

        P(w).forEach(function( v ){
          delta( v, delta(v) + sigma(v)/sigma(w) * ( 1 + delta(w) ) );

          if( !w.same(s) ){
            Cb( w, Cb(w) + delta(w) );
          }
        });
      }

    });

    var getNode = function( nodeOrSelector ){
      if( is.string( nodeOrSelector ) ){
        return eles.cy().$( nodeOrSelector )[0];
      } else {
        return nodeOrSelector[0];
      }
    };

    var ret = {
      betweenness: function( nodeOrSelector ){
        return Cb( getNode( nodeOrSelector ) );
      },

      betweennessNormalized: function( nodeOrSelector ){
        return Cb( getNode( nodeOrSelector ) ) / max;
      }
    };

    // alias
    ret.betweennessNormalised = ret.betweennessNormalized;

    return ret;

  } // betweennessCentrality

}); // elesfn

// nice, short mathemathical alias
elesfn.bc = elesfn.betweennessCentrality;

module.exports = elesfn;
```

My implementation here is very clean -- staying verbatim with the pseudocode in the paper.  It uses functions so that the implementation is formatted just like the paper.

My alternative implementation gives exactly the same results as @ayhun's for the graph you posted.  I strongly suspect any issue is with the design of the algorithm itself. The paper mentions DAGs at one point, and another paper references this one w.r.t. betweenness estimates.  Perhaps the cycle throws this algorithm off, or perhaps the values are not to be taken absolutely but relatively -- making the normalised values more useful.
