### ISSUE TITLE
Haystack Edge Rendering Problem

### ISSUE THREAD

**Issue by istemi-bahceci** [cytoscape/cytoscape.js#1033]
Hi, 

  I've noticed that when using 'haystack' as edge 'curve-style', it seems that edges are not clipped correctly. You can refer to the image below. 

![image](https://cloud.githubusercontent.com/assets/8645080/9230343/67a7f670-412a-11e5-8403-cf30eecaf4b1.png)

Regards,
İstemi Bahçeci

**Comment by maxkfranz** [comment]
This is expected.  The edges are drawn to the radius you specify with `haystack-radius`.  If you want them on the edge of the node, you can set `1`.  Alternatively, you can use `opacity: 1` on the nodes.

Clipping based on shapes is expensive, especially for many shapes.

**Comment by istemi-bahceci** [comment]
Unfortunately setting opacity: 1 for nodes is not possible in my situation, when i set haystack-radius: 1, i get following result: 

![image](https://cloud.githubusercontent.com/assets/8645080/9230769/d596077e-412c-11e5-8c67-fa2361510e04.png)

is this normal ? i am curious because when i use 'bezier' i do not experience such situation.

**Comment by maxkfranz** [comment]
This is normal.  All edges go the edge of the node's shape with radius 1.  The location along the shape's edge is random, for performance.

Beziers do not use random positions and do expensive intersections.  It's a tradeoff.

If you don't have a mutligraph, I suggest `haystack-radius: 1`.  Otherwise, find a value you like.  If that doesn't fit your aesthetic, then you may want to use opaque nodes.  

Managing both aesthetics and performance is a difficult balance.

**Comment by maxkfranz** [comment]
Closing, because there is no bug to assign

If you have further questions, that's fine though

**Comment by istemi-bahceci** [comment]
Thanks for the answers :)

**Comment by maxkfranz** [comment]
Typo : I meant to suggest a radius of 0.  That will put an edge in a node's centre.
