### ISSUE TITLE
Autosized nodes based on label dimensions

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#1041]
e.g. 

```
node {
  width: 'label'
}
```

If you want spacing around the label, this requires support for padding properties on non-compound nodes: #1053

**Comment by maxkfranz** [comment]
Works but padding alignment and docs TODO

**Comment by cstancu** [comment]
This works well for nodes, although it doesn't seem to be working for parent (compound) nodes. Is that not supported? Is there a known workaround to resize parent nodes based on the bigger of either the collected width of the nodes or the width of the label?

**Comment by maxkfranz** [comment]
@cstancu Parents have implicit size to fit the children.  Any specification of width/height on a compound parent doesn't mean/do anything.

Adjusting compound parent size based on the label isn't so simple.  Yes, setting a minimum like that may work visually for simple cases.  However, layout is another case altogether.  

External lib layouts may or may not be compound aware.  Some consider only child positions/bounds for compound bounds, rather than full bounding boxes.  CoSE and CoSE-Bilkent should be OK.  Cola might be OK.  Others, probably not.

If you want a feature like this (e.g. `min-width`, `min-height`), it would probably make sense to have a separate issue.  We could probably PR your changes with the new style properties.  What do you think?

**Comment by cstancu** [comment]
Yes, dagre doesn't take into account the the full bounding box of a compound node, I guess it computes its own based on the nodes belonging to the cluster. Even if I specify a very large value for every cytoscape parent node in cytoscape-dagre.js DagreLayout.prototype.run the layout doesn't change.
 
Since right now I only need the `min-width` to match the label width, as a temporary workaround, I am thinking to add a dummy, invisible node (i.e., fully transparent and with a height close to 0) to every compound node. That would probably make dagre happy.

Sure, I could make a pull request and maybe try to find a proper solution when I have some time.

**Comment by thedmitriyk** [comment]
If I'm correctly interpreting what I'm seeing, I'd say that the `dagre` layout does not seem to take into account the actual size of nodes sized using `'label'`.

**Comment by maxkfranz** [comment]
@thedmitriyk Dagre can't set compound positions.  (See above.)  Dagre uses compounds to group descendants.  The full bounding box is sent to Dagre: https://github.com/cytoscape/cytoscape.js-dagre/blob/1.2.1/cytoscape-dagre.js#L100

**Comment by thedmitriyk** [comment]
Sorry, I may be in the wrong issue. I didn't mean compound nodes; just simple nodes with a label.

**Comment by maxkfranz** [comment]
The bounding box accounts for labels, so it's probably fine for your case.
