### ISSUE TITLE
Ability to specify size of parent nodes

### ISSUE THREAD

**Issue by dabobert** [cytoscape/cytoscape.js#1051]
Even though i try to specify the size of parent nodes, the width and height attributes always seems to be ignored.  I would find it beneficial to limit the space that parent nodes and their children take up on the canvas

**Comment by maxkfranz** [comment]
This may be possible to set as an option in particular layouts, but it's probably not possible in general with all the features that the API supports.

For example, some layouts only apply to noncompound nodes.  So, all the child nodes get positioned according to the layout algorithm (e.g. arbor or grid).  A compound parent has its dimensions set automatically based on its children.  If a restriction is set on compound dimensions, there is a contradiction.  There are many more examples like this.

It would be possible to have layouts (like the upcoming CoSE2) have support for limiting compound node sizes -- but even then this is more of just a hint rather than a hard and fast restriction.  Even within a layout, restricting compound size can create contradictions.  Consider avoiding overlap.  The compound may not have enough space to avoid its children from overlapping.

**Comment by dabobert** [comment]
honestly a hint would be amazing.  I understand that if a person were to define too little space for a compound nodes and its child nodes, it would have to "bust out" of the size originally designed

And if this could be included in an upcoming release that would be amazing.

**Comment by ugurdogrusoz** [comment]
Limiting compound node sizes is not straightforward at all. Any particular reason that you'd like to limit a compound node's size? Can you share with us some examples where the layout inside compounds are not to your satisfaction? Have you tried increasing gravity if you think layout produces compound nodes that are too large? Also, if your compounds typically include disconnected nodes, you should turn tiling on.

**Comment by ugurdogrusoz** [comment]
I think a layout algorithm's treatment of compound sizes is independent of whether or not the core allows resize of compounds. I think there should be an option at the core for compounds for auto resizing of compounds. I would make it true by default (current behavior). If false, however, I would allow compounds to be resized arbitrarily (independent of their children). We might want to restrict the geometry of the compounds in such a way that a compound is always "bigger" than its children's bounding rectangle (+paddings). There is no reason to disallow a compound not to be "bigger" than its content, otherwise.

**Comment by ugurdogrusoz** [comment]
@dabobert Now it's possible to size compounds to be bigger than their children's bounds using the options specified under "Compound parent sizing" in Cytoscape.js documentation. This is a feature outside a layout. For a layout to support this is a separate issue; in other words, layout might change any specified size for a compound.

**Comment by kunalganglani** [comment]
I want to use dagre layout along with an option to make the child nodes have vertical alignment and compound nodes a fixed height and width. Is this possible?

**Comment by rbowers02** [comment]
@kunalganglani Just curious were you able to accomplish this? I was looking to do the same thing I have 20 nodes inside a parent and I would like to be able to set max width on that parent and force a 4x5 layout inside that parent.
