### ISSUE TITLE
Nicer rendering for edges with overlapping nodes

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#1109]
Current behaviour : For edge e, if e's source and target overlap, then don't draw e.

Desired behaviour : For edge e, if e's source and target overlap, draw e.  Use the midpoint between source and target as the imaginary line intersections.

**Comment by jflaflamme** [comment]
@maxkfranz I see that edges overlapping are working only with Bezier adding extra spaces in between, otherwise, only one is visible. I want to make a flow graph and have different source/target arrows.

Any workarounds? (I use taxi lines per examples, but I would take any solution with straight lines)
