### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by igorcc** [cytoscape/cytoscape.js#1120]
Dear Cytoscape developers, in order to avoid some boring output it's better to change the line 13075 of cytoscape.js from if( styleEnabled ) to if( styleEnabled && cy_p.renderer ).
I suppose it's no need to create a pull request to amend this code.
Thanks.

**Comment by maxkfranz** [comment]
Thanks for your feedback.

Ref : https://github.com/cytoscape/cytoscape.js/blob/v2.4.8/dist/cytoscape.js#L13076

A renderer is always defined, or you can't init.  If you specify the null renderer, nothing is done in `recalculateRenderedStyle()`: https://github.com/cytoscape/cytoscape.js/blob/v2.4.8/dist/cytoscape.js#L26364

How would this change alter the lib's behaviour at all?  Could  you explain your usecase?

**Comment by igorcc** [comment]
Hi Max,

That’s pretty easy:

$(function () { // on dom ready

    cy = cytoscape({
        container: document.getElementById('cy'),
        elements: $.getJSON('/elements/'),
        style: $.getJSON('/style/'),
        headless: false,
        renderer: {
            name: "canvas"
        }
        // ,layout: {name: "random"}
    });

    cy.layout({name: 'random'});  // I call this according to the documentation
});

brings an exception to the console:  Uncaught TypeError: Cannot read property 'recalculateRenderedStyle' of null

It doesn’t matter if layout is defined in the constructor or not.

Thank you!

-------------------------------------
Kindest regards,
Igor Koshkarov
koshkarovigor@gmail.com

**Comment by maxkfranz** [comment]
(1) The renderer normally initialises after the data has loaded.  I've changed the 2.5/unstable branch to init the renderer right away, but this isn't really your problem.

(2) Even with the change in (1), it doesn't really fix your problem.  The problem is:  You have decided to load your data asynchronously and then try to manipulate is synchronously (before it's loaded).  Either init after your data has loaded or use `ready`.  Please refer to `ready` : http://js.cytoscape.org/#core/initialisation

**Comment by igorcc** [comment]
Thank you, Max

I’ll look into the documentation again.
Sorry for pestering you.

-------------------------------------
Kindest regards,
Igor Koshkarov
koshkarovigor@gmail.com

**Comment by maxkfranz** [comment]
No problem; it was an opportunity to improve the docs.  Thanks for the feedback
