### ISSUE TITLE
layout background image

### ISSUE THREAD

**Issue by wmartinezo** [cytoscape/cytoscape.js#1132]
Hi, there could be an option to put a image in background layout.

like this: http://www.gojs.net/latest/samples/kittenMonitor.html

**Comment by maxkfranz** [comment]
You can do this by putting a background image on the containing HTML DOM element.

You can even update the image on `pan` and `zoom` events if you like.

See [`background-image`](https://developer.mozilla.org/en-US/docs/Web/CSS/background-image?redirectlocale=en-US&redirectslug=CSS%2Fbackground-image), [`background-size`](https://developer.mozilla.org/en-US/docs/Web/CSS/background-size), [`background-position`](https://developer.mozilla.org/en-US/docs/Web/CSS/background-position)

I don't think things like this would be added to the lib itself, because it's very easy to do this in your app and a goal is to make future versions leaner.
