### ISSUE TITLE
Influence of locked nodes on layout

### ISSUE THREAD

**Issue by wolfig** [cytoscape/cytoscape.js#1137]
Hi Cytoscape experts,

I'm playing around with cyotscape.js and available force.driven layouts. My network has about 650 nodes and edges. I do see desired results using cola (cose et al. work well too) and with all nodes unlocked. However, it is essential for me to have some nodes locked to give my network some anchor-points where free nodes should orient to. If I use locked nodes I do get the impression that these are ignored by any of the layout algorythms - the unlocked nodes tend to move away from the locked ones. If you like I can provide my sources.

Bug, feature or feature request???

Best regards WolfiG

P.S.: I worked with Gephi so far (lacking the online capabilities), where the forceatlas2 produces results similar to cola. There I was able to lock nodes and the network arranged to them.

**Comment by maxkfranz** [comment]
In general, a physics layout will work in the way you want if and only if it (1) has internal modelling of locked nodes (or otherwise they just behave as though the node isn't locked but the actual position won't change) and (2) it has support for iterative runs.

In 2.5 ([currently prerelease](http://js.cytoscape.org/unstable/) but soon to be tagged and released), CoSE has improved mechanics for locked nodes (1) but it wouldn't be able to do (2).  [CoSE Bilkent ](https://github.com/cytoscape/cytoscape.js-cose-bilkent) supports (2) but I'm not sure about (1) yet.  Cola supports (2) and [now supports (1)](https://github.com/cytoscape/cytoscape.js-cola/issues/2).

Note that many layouts have been separated as external extensions for 2.5, like Cola -- which means layout releases can be more frequent and layout are easier to make pull requests to.

**Comment by maxkfranz** [comment]
Closing for now

**Comment by Does666** [comment]
@wolfig So how do you resolve you issue ?

**Comment by wolfig** [comment]
@Does666: Actually I didn't solve this at all. In the end I used vis.js (https://visjs.org/) which provides the functionality I needed out of the box.
