### ISSUE TITLE
Prevention of default events / event propagation not working

### ISSUE THREAD

**Issue by tambeta** [cytoscape/cytoscape.js#1145]
Prevention of default events or hindering event propagation doesn't seem to be functional in cytoscape.js. I am trying to override the default event which happens upon clicking a node (the node is selected) with instead selecting the node's neighborhood. None of the methods for hindering event propagation seem to work:

```
	cy.off("click");	
	cy.on("click", "node", null, function(e) {		
		e.stopPropagation();
		e.stopImmediatePropagation();
		e.preventDefault();		
		e.originalEvent.stopPropagation();
		e.originalEvent.stopImmediatePropagation();
		e.originalEvent.preventDefault();		
		
		e.cyTarget.neighbourhood("node").select();
	}
```

The result is that only the clicked node is selected. Using a setTimeout hack seems to confirm that the default event overrides the desired effect, i.e. replacing the last line of the event callback with

```
window.setTimeout(function() {
	e.cyTarget.neighbourhood("node").select();
}, 50);
```

works.

**Comment by maxkfranz** [comment]
Preventing default events is meant more for native browser events, because they're limited to that mechanism.  In Cytoscape.js, you can control if gestures are recognised at any time, and the control is fine-grained over which gestures are affected.

For your selection example, you can use `ele.unselectify()` and `ele.selectify()`.  Unselectify your nodes, and then you can selectify them at whatever point you want using whatever kind of selection behaviour you'd like.

**Comment by tambeta** [comment]
I am unclear on the concept of "selectification". The documentation on `eles.unselectify()`  states

>Make the selection states of the elements immutable.

Obviously I would like the selection state of my nodes to be mutable, as otherwise I wouldn't be able to mark them as selected? Wouldn't it make more sense to allow prevention of an event's propagation / default effect?

**Comment by maxkfranz** [comment]
For the effect you're describing, I would argue that it's the opposite:  You want *custom* selection behaviour, so you don't want selection state to be mutable by default.  Otherwise, any number of user events would generate selection.

It's far terser and more future-proof to selectify elements in the short window they need to be rather than hunt down every event that could cause selection.

```js
cy.elements().unselectify();

cy.nodes().on('tap', function(e){
  e.cyTarget().closedNeighborhood().nodes()
    .selectify()
    .select()
    .unselectify()
  ;
});
```

**Comment by tambeta** [comment]
I see, your example clarifies how you meant using `[un]selectify()` to this end. Thanks a lot; closing the issue.

**Comment by tambeta** [comment]
I'm reopening the issue for some more feedback.

I'm now trying to use box selection in conjunction with the custom selection behavior as explained above. What is the "cytoscape.js way" to do this? When I enable box selection, it obviously doesn't work, as node selection state has been set to immutable, as you recommended above. But I don't notice any box selection events for capture. If there were events like `boxSelectionBegin` and `boxSelectionEnd`, this would not pose a problem.

**Comment by maxkfranz** [comment]
Adding new events like those sound like a good idea, though keep in mind that only unselected elements would have `select` triggered afterwards.

For now, if you want custom selection behaviour, you have to disable the existing selection behaviour and replace it with your own.  We've already covered the tap case.  If you want custom box selection, you'll either have to reimplement it (or maybe try another approach with elements selectified by default).

**Comment by tambeta** [comment]
>Adding new events like those sound like a good idea, though keep in mind that only unselected elements would have select triggered afterwards.

OK. My idea is along the lines that a separate `boxselect` (or such) event would be fired for all nodes in the box, allowing the library user to implement any selection behavior. I.e. the box selection event would be similar to any other user input (click, tap, etc.).
