### ISSUE TITLE
SVG background image not rendering under IE (cy 2.5)

### ISSUE THREAD

**Issue by melborp** [cytoscape/cytoscape.js#1149]
Hi

The SVG images still will not render due to a small bug in the 2.5. 

The commit https://github.com/cytoscape/cytoscape.js/commit/8b24bd72d54e78a154632e9b0c5aaf4ffdf5544f , fixes some, but due to the fact that when the call "r.safeDrawImage( context, img, 0, 0, imgW, imgH, x, y, w, h );" in  "src/extensions/renderer.canvas.drawing-images.js", is using imgW / imgH, which will be 0. the background still will not show up.

In my copy of code i had one more activity if w / h were not 0,

    if (img.width === 0 || img.height === 0) {
        imgW = w;
        imgH = h;
    }

to make sure that the imgW / imgH will be the background-width / background-height if they were set.

related to https://github.com/cytoscape/cytoscape.js/issues/782 however i didnt want to type more to the closed issue.

**Comment by maxkfranz** [comment]
The checks that are there now are probably all that are possible.  If your SVG is valid and you are using the latest version of IE, then SVG backgrounds should work.

You can't assume that the width of the image is the same as what's specified in the style.  That may work in your particular case, but it doesn't hold true in general.  Adding your suggested change will certainly create bugs for other users -- and in much more common usecases too.

**Comment by melborp** [comment]
actually, if i switch between 2.4.8 (my changes https://github.com/melborp/cytoscape.js/commit/cb2e0f910112d1b4e5602afffc56c76ed59bc9b3) and 2.5 (with this line change here)

i still dont see the background images in IE. Something else has changed between 2.4.8 and 2.5 ?

**Comment by maxkfranz** [comment]
Falling back on the `background-width` etc might be OK in some cases.

#782 uses yet another workaround for IE, trying to render the SVG in the DOM to get its size.  Because of this extra check, the width might be null/undefined instead of zero if IE fails this check.

I'm hesitant to add this as an extra workaround, because it won't always work.  It can distort the image. It means `background-fit` doesn't work anymore.  It means tiling doesn't work anymore. 

I don't think we can expect everything to be perfect in old, broken versions of IE.  Some people in #782 have found IE works if the SVG is formatted carefully and correctly.  But you may be better off using PNG or JPG in IE if compatibility with old versions is important to you.

**Comment by melborp** [comment]
Hi Max
It seems it doesnt render the background image regardless of adding the code i am proposing here.
The loading trick deosnt work because of the way IE works with those images, width / height will remain 0.
allowing to use values from specified width / height seems like a good alternative.

In any case, it doesnt seem to be enough in 2.5 anymore. works in 2.4.8

My question is, has anything else changed?
2.5 also breaks navigator https://github.com/cytoscape/cytoscape.js-navigator/issues/15

**Comment by maxkfranz** [comment]
As I mentioned, you can not simply fall back on the style width/height.  That would *break* things for other users.

The additional check for 2.5 makes things better for IE, but it will not be perfect because *IE has a buggy SVG implementation*.  If you update your browser to the latest version of IE (now called Edge), SVGs work fine.

The list of changes for 2.5 is in the milestone: https://github.com/cytoscape/cytoscape.js/issues?q=milestone%3A2.5.0  The navigator extension should not reference private data.

**Comment by melborp** [comment]
So, regardless of the code on width / heigth setting. I think there is a breaking change in 2.5 after the refactoring of rendering.

When the rendering runs in IE, i get exception on call:

´´´
context.drawImage( img, ix, iy, iw, ih, x, y, w, h );
´´´

´´´
"Error: Unexpected call to method or property access.\n   
at CRp.safeDrawImage (http://localhost:40704/scripts/cytoscape/2.5/cytoscape.js:16168:5)\n   
at CRp.drawInscribedImage (http://localhost:40704/scripts/cytoscape/2.5/cytoscape.js:16294:5)\n   
at CRp.drawNode (http://localhost:40704/scripts/cytoscape/2.5/cytoscape.js:16856:9)\n   
at drawElements (http://localhost:40704/scripts/cytoscape/2.5/cytoscape.js:17482:9)\n   
at CRp.render (http://localhost:40704/scripts/cytoscape/2.5/cytoscape.js:17518:5)\n   
at CRp.renderTo (http://localhost:40704/scripts/cytoscape/2.5/cytoscape.js:17204:3)\n   
at renderTo (http://localhost:40704/scripts/cytoscape/2.5/cytoscape.js:7079:5)\n   
at render (http://localhost:40704/scripts/cytoscape/2.5/cytoscape.js-navigator.js:551:7)"
´´´

The code that breaks it for me is this:

´´´
  // workaround for broken browsers like ie
  if( null == imgW || null == imgH ){
    document.body.appendChild( img );

    imgW = img.cachedW = img.width || img.offsetWidth;
    imgH = img.cachedH = img.height || img.offsetHeight;

    document.body.removeChild( img );
  }
´´´

**Comment by melborp** [comment]
I would like to know more why this is an issue to include.
The code would really only run in IE.

**Comment by maxkfranz** [comment]
Using the style width and height as a fallback would break other people's usecases.

As for your error, it's unreproducible for me on several Windows machines with both the latest IE and Edge.
