### ISSUE TITLE
Disabling `userPanningEnabled` removes possibility to scroll the document on mobile devices

### ISSUE THREAD

**Issue by gopeter** [cytoscape/cytoscape.js#1164]
I'm using Cytoscape 2.5.0 and found some strange behaviour when disabling `userPanningEnabled` on mobile devices: if this option is disabled, I can't scrollt the document/entire page (there is a lot of text above/below my Cytoscape canvas).

Here is a little fiddle that illustrates the problem: https://jsfiddle.net/VzCZm/67/embedded/result/

Is there any way to enable scrolling when `touchStart` begins on Cytoscape's canvas?

**Comment by maxkfranz** [comment]
It's not possible to do that in general.  By allowing scroll on the Cytoscape div at all, it completely breaks IE and Edge support.

You'll notice that [it's mandatory in IE/Edge to use `touch-events: none` in order to disable default gestures and get pointer (i.e. touch) event support](http://blogs.msdn.com/b/davrous/archive/2013/02/20/handling-touch-in-your-html5-apps-thanks-to-the-pointer-events-of-ie10-and-windows-8.aspx).  So touch support precludes default gestures like scrolling.

For future reference, I've put the ideal solution in master.  It's disabled by default.  If you try it, you'll notice IE and Edge are completely broken.  If you re-enable the [`/*-ms-touch-action: none; touch-action: none;*/ `](https://github.com/cytoscape/cytoscape.js/commit/5f7870bb4f45bf0f67935f2c6052cedd2b5e1a9f) bit, then IE and Edge work again but scrolling doesn't.

Maybe in the future, this can be improved, but now there's no good, general solution.

**Comment by maxkfranz** [comment]
I've improved IE/Edge detection and set `touch-events: none` only on IE/Edge.

At least this will let things work properly on mainstream/standard setups like iOS and Android.  Chrome on Windows touch devices like Surface should also work.

**Comment by maxkfranz** [comment]
Try the snapshot and let me know how it goes: http://js.cytoscape.org/download/cytoscape.js-snapshot-e6f0e056b6-1448472477770.zip

**Comment by gopeter** [comment]
Thank you very much! I'm going to try it tomorrow :)

**Comment by maxkfranz** [comment]
OK, I'm going to close this for now and release the 2.5.1 patch version.  Since this issue isn't completely solved re. IE/Edge, it's going to be an ongoing issue anyway.  If you notice problems (on browsers like Chrome, Firefox, or Safari), please reopen.

Thanks

**Comment by gopeter** [comment]
Works like a charm, thank you very much! :-)
