### ISSUE TITLE
Border radius for parent of compound nodes

### ISSUE THREAD

**Issue by Andreew4x4** [cytoscape/cytoscape.js#1167]
Hi!
Is there or will be possibility to make rounded corners for parent of compound nodes?
It would be really nice to have somthing like this:
```javascript
    {
      selector: '$node > node',
      css: {
        'padding-top': '10px',
        'padding-left': '10px',
        'padding-bottom': '10px',
        'padding-right': '10px',
        'text-valign': 'top',
        'text-halign': 'center',
        'background-color': '#bbb',
        'border-width' : '2',
        'border-color' : 'red',
        'border-radius': '5'
      }
    }
```

Kindest regards,
AJ

**Comment by maxkfranz** [comment]
While this may seem like a nice idea, there are issues with it.  The border radius could be applied to any roundrect node, but it wouldn't work in all cases with compound nodes.

Compound nodes work by having children within the bounding box of the parent.  For existing roundrect parents, this isn't an issue because the radius is so small that the overall shape is essentially a rectangle.  

If you increase the radius, then that no longer holds true.  That means that the calculations for parent bounds become much more complicated and expensive.  Compound nodes already bring additional expense to rendering, and adding a customisable radius would make this *much* worse.

Until this performance issue can be solved/avoided, it would be unwise to add this feature.

**Comment by dovs** [comment]
Hi,
I support [Andreew4x4](https://github.com/Andreew4x4)'s request.
Like with other features which may affect performance a mention for this under the [Optimizations ](http://js.cytoscape.org/#performance/optimisations) section could be added, while still allowing those who could benefit from this feature to use it in situations where it can provide added value and does not necessarily cause a noticeable slowdown in performance.

**Comment by Does666** [comment]
So is it possible to set `roundrect` for compound node ? I tried this snippet, but it doesn't work.
```
{
	selector: ':parent',
	style: {
		'shape' : 'round-rectangle',//'round-rectangle',
	}
},
```

**Comment by kilobyte2007** [comment]
Use 'roundrectangle'. The docs are probably wrong.
