### ISSUE TITLE
Labels move if node border widths change.

### ISSUE THREAD

**Issue by dwjohnston** [cytoscape/cytoscape.js#1211]
This is related to issue [#965](https://github.com/cytoscape/cytoscape.js/issues/965)

If you have set styling where the node's border width will change (for example if you want to display a border when a node is selected), this will move the labels slightly. 

To fix change the calculation of node with from `node.outerWidth()` to `node.width()` on lines ~12248

**Comment by maxkfranz** [comment]
This is expected behaviour.  Labels are placed at the node's bounds.  The bounds can change on style updates.

If you're using the border for selection state or similar, you can use a transparent or near transparent border of the same width in the default state.  That way, the bounds are consistent.

**Comment by maxkfranz** [comment]
Closing for now

**Comment by dwjohnston** [comment]
The problem is the label will move around on style change (eg mouse over or
selection) which is distracting. There should be some way of fixing the
labels in place.

**Comment by maxkfranz** [comment]
The label is positioned based on the bounds of the node.  This means if you change the style such that the bounds (width, border, etc.) change, then the position of the label changes.

If you want the label to remain in a constant position, keep the bounds the same.  Use transparency as I mentioned, and it works exactly as you specified.
