### ISSUE TITLE
IE 10 Security Error CoSe

### ISSUE THREAD

**Issue by johnny-flinn** [cytoscape/cytoscape.js#1215]
Looking at the CoSe demo at http://js.cytoscape.org/demos/7b511e1f48ffd044ad66/ , layout fails in IE 10 emulation mode.  

Error possible related to http://stackoverflow.com/questions/10343913/how-to-create-a-web-worker-from-a-string

See also https://github.com/adambom/parallel.js/issues/12

**Comment by maxkfranz** [comment]
Cytoscape.js uses Weaver.js (weaver.js.org) for multitasking.  It uses inline-defined workers in browsers.  

It's not possible to work around the issue you've mentioned without creating a separate file just for IE10.  A major point of using Weaver threads is that you don't have to fiddle with external file references and minfication settings to get webworkers to work.

I don't think it makes sense to add a workaround for a browser that is two major releases out of date, especially since it creates complications for developers using the library.

If you really want IE10 support, your options are:

(1) Fork the CoSE layout with the thread option `{ disabled: true }`.  That way, simulated webworkers in the main thread are used.

(2) Use a layout other than CoSE.  There are many supported in the library and many more as extensions.

(3) Tell your IE10 users to upgrade their browser or (better yet) install a decent browser.  Chrome can be installed to a user's home directory -- even on Windows.

**Comment by maxkfranz** [comment]
I've added a ticket to Weaver to make this a bit more convenient: https://github.com/maxkfranz/weaver/issues/15
