### ISSUE TITLE
cy.json does not save/ copy style object

### ISSUE THREAD

**Issue by eelco2k** [cytoscape/cytoscape.js#1218]
When calling the cy.json() or cy.jsons() it does not save the style object of the element

$$.elesfn.json = function(){
    var ele = this.element();
    if( ele == null ){ return undefined; }

    var p = ele._private;

    var json = $$.util.copy({
      data: p.data,
      position: p.position,
      group: p.group,
      bypass: p.bypass,
      removed: p.removed,
      selected: p.selected,
      selectable: p.selectable,
      locked: p.locked,
      grabbed: p.grabbed,
      grabbable: p.grabbable,
      classes: ''
    });

does not contain css/style object in var json...

      css: p.css,
      style: p.style

**Comment by maxkfranz** [comment]
This is expected behaviour.  You can set the bypass style at init for convenience, but the style object is not part of the element JSON object proper.  

Options:

(1) Preferred : Use mappers and store your state in `ele.data()`.

(2) Get `ele.style()` separately to get the entire computed style.  This will be expensive for you to store, since it contains *all* style.
