### ISSUE TITLE
How to generate DAGs with variable edge length?

### ISSUE THREAD

**Issue by andrewlouis93** [cytoscape/cytoscape.js#1221]
I start at [this example](http://js.cytoscape.org/demos/e52c2fbc0b09edd6ec46/), and I've been trying to make the length edges vary per edge... 

I attempted using the `minLen` attribute, which doesn't guarantee that the edge is the given length and not any larger. 

Setting edge length is achievable using the `cola` layout, however since it's a physics simulation library, I don't see the tree like results like in that link above... 

Any direction as to how I can go about this would be great!

**Comment by maxkfranz** [comment]
In general, you can give layouts hints of edge length.

When you specify edge length, you create a multivariable set of equations that the layout solves. That system of equations can be overconstrained, leading to contradictions -- impossible to satisfy every equation / edge. 

Every layout has different strategies for handling overconstraining, and different compromises to achieve some result (rather than an error). 

Try using the dagre edge weight option. Dagre is the best automated tree layout out there.

**Comment by andrewlouis93** [comment]
Interesting - can you link me some more reading about that?

I also noticed that edgeWeight didn't seem to alter the appearance of any edges? Is this normal behaviour: http://codepen.io/anon/pen/pgdLVd ?
