### ISSUE TITLE
Render loop reregisters indefinitely

### ISSUE THREAD

**Issue by jsalankey** [cytoscape/cytoscape.js#1241]
I have been seeing an (eventually extreme) progressive slowdown in the rendering performance in at least IE11. This issue can be easily seen with the [Wine and Cheese](http://js.cytoscape.org/demos/cde4db55e581d10405f5/) demo. If you interact with the demo for a couple of minutes in IE11, particularly if you select nodes to force relayouts, the rendering performance will degrade significantly. I have not been seeing this progressive slowdown in other browsers.

The slowdown does not seem to occur with at least Cytoscape 2.4.2. I definitely see it in 2.5.2 and 2.6.1. I think the major change when this originated was with the increase in rendering framerate. IE seems to fall behind in the new rendering scheme where before, even though performance was never great because IE, it didn't degrade to unusability like it does now.

**Comment by maxkfranz** [comment]
Previously, the framerate was limited to ~30-40 fps for larger graphs, given the rendering scheme.  This previous rendering scheme was calculating things manually, and using timeouts and frameskipping to keep the performance consistent.

The side effect of this was that good browsers, like Chrome, Firefox, and Safari suffered.  They were capable of rendering at smoother, faster rates -- but the timeouts precluded that.  The new rendering scheme just lets the browser schedule frames.  This makes browsers that behave properly have better, smoother performance.

The IE family of browsers has always been buggy and slow.  I can't justify degrading the experience for the vast majority of browser marketshare to work around the quirks of a deprecated, slow browser.  IE/Edge is at <10% usage, last I saw.  Further, IE is no longer supported by Microsoft and Windows 10 / Edge now seems to be their only supported configuration.

Given all this, I can't really do anything about it.  

If you really want to support IE11 even though it's deprecated by Microsoft, you could conditionally load an old version of Cy.js if you detect IE.  I don't advise this, because detecting IE correctly is now very error prone.

**Comment by jsalankey** [comment]
Is there any kind of simple FPS capping method that could be implemented as a parameter on instantiating the Cytoscape instance? Something totally optional, but that might help with this IE issue and potentially with anybody who doesn't want or need the renderer to be cranking out as many FPS as possible for other reasons?

**Comment by maxkfranz** [comment]
You could experiment with the frameskipping parameters: https://github.com/cytoscape/cytoscape.js/blob/v2.6.1/src/extensions/renderer/base/redraw.js

That's different from the scheduling.  I'm not sure if it will help.  It's automatic as-is, so IE probably isn't reporting the clock properly -- in which case maybe a hard modulo frameskip would help more than a framerate detection autoframeskip.

If you find some tweak of the params that helps IE, it may make sense to have some option added for 2.7.  Then again -- I'm working on [general performance enhancements for 2.7](https://github.com/cytoscape/cytoscape.js/issues/593) that may make this a moot point...

**Comment by jsalankey** [comment]
So on further experimentation, it's not the FPS cap that is the problem. The problem is that `startRenderLoop` is called every time `notify`is called on the renderer.

Every time `startRenderLoop` is called, it re-registers `renderFn` as an animation frame callback. This results in enormously more calls to `renderFn` that intended per animation frame, most of which do nothing because `r.requestedFrame` is false. If you compare it to the registering of the animation loop in [animation.js](https://github.com/cytoscape/cytoscape.js/blob/b0759d99bd5dde13794c4a825ac0bc7913e63bda/src/core/animation.js), `renderFn` gets called potentially hundreds, even thousands of times more often. Every interaction with the graph results in another `renderFn` call per animation frame.

Chrome and FF seem to handle this well, but IE does not. I also don't think that Chrome and FF will handle it indefinitely--their performance will eventually degrade as well as a result of runaway calls of `renderFn` (even though they don't actually hit the `r.render` call).

**Comment by maxkfranz** [comment]
That's odd.  It must be some mistake in refactoring the renderer.

I've created a patch and verified that the registration happens once per renderer.  The patch is in the 2.6.2 release I just issued.

Thanks for the feedback

**Comment by maxkfranz** [comment]
@jsalankey It looks like adding the patch for the issue you noted broke smooth scroll / zoom support on Mac (touchpads, magic mouse, etc.).  I didn't notice this until I was on a different machine this afternoon.  The testing I did this morning went fine on a Linux machine (no smooth scroll).

I've added a smooth scroll fix and will release 2.6.3 for it.  Hopefully, this ends the issue.
