### ISSUE TITLE
Option to switch box selection behavior to not require shift key

### ISSUE THREAD

**Issue by jharwig** [cytoscape/cytoscape.js#1244]
In `2.4.x` cytoscape would draw a box selection on click and drag when `boxSelectionEnabled:true`. A change was made to [require `shift | alt | ctrl`](https://github.com/cytoscape/cytoscape.js/blob/v2.6.3/src/extensions/renderer/base/load-listeners.js#L577) for box selection around `1.5.x` Also it's additive selection.

Are you open to a PR to get the old behavior by some option? It's useful to make selection easier than panning in scenarios where users are selecting object more often than moving around the graph. (Also would have to [bring back the tap hold -> switch to panning](https://github.com/cytoscape/cytoscape.js/blob/v2.4.0/src/extensions/renderer.canvas.load-and-listeners.js#L623).)

**Comment by maxkfranz** [comment]
Bringing back the pan/boxselect behaviour isn't really an option, because it reduces usability.  It's hard for users to find, and by a large margin users prefer to pan by default.

It's better to have an explicit toggle in your app itself.  A toggle button that switches between panning and selecting is far easier for users to find, and it's more accessible -- i.e. less co-ordinated users have trouble with the delay option.  When panning is disabled, box selection can happen right away -- so this explicit toggle method works well.

**Comment by jharwig** [comment]
While i think something like a selection tool would work, it requires disabling panning (which is fine) but also disables zoom. Which could be just as confusing to the user.

The other issue is now users have learned knowledge of the selection by default, and click and hold to pan. So, we have to choose to break that experience or upgrade cytoscape.

**Comment by maxkfranz** [comment]
User zooming requires panning, and that's unavoidable.  Users tend not to differentiate the two anyway -- they considering it all "moving around".  It's clear if you have a mode: You can either move around or box select.  Additionally, it's standard behaviour in most software to require shift or control to box select.  Image editors are good examples.

The learned behaviour of the delay behaviour is minor and often overestimated by developers (myself included, until I ran lots of tests on users who had never used Cytoscape.js at all).  A very small minority of users ever learn it exists in the first place.  By and large, users are far more likely to find box selection via shift than via delay.

There's little value in keeping the delay behaviour.  If box selection by default is very important to you, then it's better by all accounts to have a mode for it rather than using old software versions.

**Comment by jharwig** [comment]
Thanks for your thoughtful responses, and your work on cytoscape. It's much appreciated. A selection mode is what I'll probably go with.
