### ISSUE TITLE
Spacing factor override option in layouts

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#1266]
Allows a postprocessing factor to be applied to spacing, because auto avoid overlap can space things out far if one element is large

This would update the definition of `eles.layoutPositions()` so that the option would work for all discrete layouts that call it.

`options.spacingFactor` : Applies a multiplicative factor to expand or compress the overall area that the nodes take up.  For example, a value of 2 would make the nodes twice as spaced apart.

**Comment by josephst** [comment]
I've added `spacingFactor` to the grid layout and am working on adding to others. Note: breadthfirst layout already includes a `spacingFactor` option which appears to work identically to the suggested `spacingFactor` option.

**Comment by maxkfranz** [comment]
@josephst Probably the `spacingFactor` in the bfs layout could be removed then.  We should probably use the name `spacingFactor` overall for backwards compatibility -- or we should check if  `spacingFactor` exists and use it for `scalingFactor`.

I think the positions have to be normalised before scaling is applied.  The scaling needs to happen as a vector relative to the bounding box centre, because the bounding box might not be (0, 0) to (w, h).

**Comment by josephst** [comment]
Newest additions to #1673 should check the bounding box for the elements that the layout is being run on. I've taken out the `spacingFactor` option from bfs now that spacing is handled in core layout. I verified that the bfs demo produces an identical result. 

The spacing factor doesn't work with the cose and cose-bilkent layouts; perhaps because it's iterative and the node positions that are being scaled aren't the final node positions?
