### ISSUE TITLE
nodes.outgoers() ignores self-loops

### ISSUE THREAD

**Issue by thpani** [cytoscape/cytoscape.js#1299]
Currently `nodes.outgoers()` does not include self-loops (i.e. edges to/from the same node).

This goes against (i) the common definition in graph theory, and (ii) the current documentation of the function.

**Comment by maxkfranz** [comment]
`.outgoers()`, `.incomers()`, etc are intended to be [DAG traversal functions](https://github.com/cytoscape/cytoscape.js/issues/546).  Their naming is chosen to avoid conflicts with compound functions.  For example, "parent" has both a compound meaning and a DAG meaning.

Those DAG functions should have been marked with "DAG" as `.roots()` is.  The tests also check explicitly against loops, because loops are classified as self -- neither really outgoing nor incoming.

Since loops don't really make sense in DAGs anyway, they can probably be safely added to the DAG functions.

**Comment by maxkfranz** [comment]
Try this snapshot and let me know if it works for you.  It's passing the unit tests as modified for loops.

http://js.cytoscape.org/download/cytoscape.js-snapshot-e9ba43d326-1458149978215.zip

**Comment by maxkfranz** [comment]
@thpani [snapshot download](http://js.cytoscape.org/download/cytoscape.js-snapshot-e9ba43d326-1458149978215.zip)

**Comment by thpani** [comment]
Thanks, the snapshot works for me.

**Comment by maxkfranz** [comment]
Great; thanks
