### ISSUE TITLE
Is it possible to build an entity-relationship diagram with table nodes using cytoscape.js?

### ISSUE THREAD

**Issue by john-bai** [cytoscape/cytoscape.js#1309]
Hi there! I really enjoy cytoscape.js and am interested in trying to use it to build an entity-relationship diagram with tables. There seems to be two features required in order to draw one:

1. Source and target labels on edges (#382, already implemented for 2.7.0)
2. Ability to draw a table node.

In what ways could I explore drawing a table node in a cytoscape.js graph? Could it be a compound node, where the table header and columns would each be a child node? How about building a UI extension where I could introduce a specialized node type TableNode?

![image](https://cloud.githubusercontent.com/assets/246892/13888328/2af498e8-ecfe-11e5-8498-04fd57a07471.png)

I built a POC using compound nodes: https://jsfiddle.net/do5qw18o/.
![image](https://cloud.githubusercontent.com/assets/246892/13891014/d665d8e2-ed0b-11e5-965c-310e8f407f69.png)

I'm a little confused about child node positioning as it doesn't appear to be relative to the parent node. Also, my attempt to set a position on parent nodes doesn't seem to work. Ideally I'd like to just mutate the parent node position and have the child nodes always positioned relative to the parent.

I'd appreciate it if the contributors could review the POC and let me know if this would be the ideal way of implementing this table node. Is the positioning for the nodes correct, or could the child nodes be relatively positioned?

**Comment by john-bai** [comment]
I built a POC using compound nodes: https://jsfiddle.net/do5qw18o/. I'm a little confused about child node positioning as it doesn't appear relative to be relative to the parent node. Also, my attempt to set a position on parent nodes doesn't seem to work. Ideally I'd like to just mutate the parent node position and have the child nodes always positioned relative to the parent.

**Comment by maxkfranz** [comment]
A compound parent doesn't really have its own position.  Its position is inferred from the dimensions of its children, because it must accommodate its children automatically.  

To "move" a parent, you would alter the positions of all of its non-parent descendants.  That's exactly how the drag gesture operates.

Further, it doesn't make sense to have position defined relatively to a parent.  That would confound model positions and especially rendered positions.  If you want relative position, then use [`node.relativePosition()`](http://js.cytoscape.org/#node.relativePosition).

**Comment by john-bai** [comment]
Thanks for the explanation and parent "move" strategy @maxkfranz! I'll close this issue for now as it sounds like I'm on the right path.

**Comment by clement911** [comment]
Hi @john-bai 
I'm facing the same need and I'm curious if you ever got it working?
