### ISSUE TITLE
Question: Layout, performance of 'add'  function

### ISSUE THREAD

**Issue by AntoniBertel** [cytoscape/cytoscape.js#1318]
Hi,
Firstly thank a lot for cytoscape, i solved a lot if question just using OOTB solutions.

My current flow is:
Initialize cytoscape
```
cytoscape({...});
```
Configure template:
```
var layoutParams = {
    name: 'cola',
    nodeSpacing: 4,
    edgeLengthVal: 45,
    edgeLength: 2500,
    maxSimulationTime: 0
};
```
Layout with empty data
```
cy.layout(layoutParams);
```
**Actions below are performed several times**
Delete all previous elements
```
cy.elements().remove();
```
Waiting for a data (response from server) and add nodes, edges
```
        cy.startBatch();
            cy.add(nodes);
            cy.add(edges);
        cy.endBatch();
```
Layout (data have been updated)
```
cy.layout(layoutParams);
```

Let me ask a few questions:

1. Between two steps: [adding new data] and [layout with 'layoutParams'], i got a temporary state when the data were drawn, but not yet structured in accordance with the 'layoutParams'.
How can i prevent drawing data first time (before layout) or draw the first time with template settings?

2. For ~500 nodes and ~1000 edges I have the following performance measurements:
Remove step: 61ms
Batch step: 497ms
Layout: 116ms
Could you suggest how I can optimize my approach to speed rendering?
(I cut styles to a minimum and read the 'Optimisations' paragraph)

Thank you a lot.

**Comment by maxkfranz** [comment]
Batching the add step won't help much, because you're only doing two operations anyway.  You could do `cy.add( nodes.concat( edges ) )` instead to simplify.

Hide the elements using style or move the viewport, if you don't want to see added elements before layout.

Adding elements is expensive because of stylesheets.  Use `cy.json()` to diff-patch your elements instead of removing them all if you can.

Also upgrade to 2.7 when released, which has >=3x improved stylesheet performance.

**Comment by AntoniBertel** [comment]
Many thanks for the answer. I removed 'bathes' frames and joined arrays.
Is 'unstable' branch close to the 2.7 release? I can build it and use.

**Comment by maxkfranz** [comment]
You can use it if you really want, but it's labelled `unstable` for a reason...

At this moment, it's feature complete but needs more testing
