### ISSUE TITLE
Layout options are being modified by cytoscape

### ISSUE THREAD

**Issue by AoDev** [cytoscape/cytoscape.js#1320]
Hello, 

I've had troubles with layouts until I realised that cytoscape modifies the layout options object.

Unless I'm mistaken in what is really happening, shouldn't you clone the options instead of modifying the object? this caused various problems on my side. Especially we can't reuse the option object when we need to relayout. I think it shouldn't be modified but if you want to keep it the current way, could you please add a note in the docs that warns developers that layout will modify the options.

<img width="558" alt="screen shot 2016-03-31 at 01 45 20" src="https://cloud.githubusercontent.com/assets/1526150/14161241/5d39d47e-f6e2-11e5-8879-92f5040c93ab.png">

**Comment by maxkfranz** [comment]
In general, you can't assume the objects that you pass to Cytoscape will be unchanged.  The reason for this is performance.  For example:  It's expensive to deep copy element objects when adding them to the graph.  It's cheaper to just let each element "own" its part of the passed object.

Layouts are a different case, I suppose, because of the `cy.layout()` API.  It actually just makes a new layout behind the scenes with `cy.makeLayout()`, but the naming for `.layout()` lends itself to devs recalling it with the same object over and over.  2.7 already has changes to accommodate this case, so your issue is already resolved.  Layouts aren't so much of a performance concern with cloning, but it is a bit of an issue of consistency.

There should be a warning somewhere in the docs re. elements, layouts, etc: https://github.com/cytoscape/cytoscape.js/issues/1325
