### ISSUE TITLE
Pan limits

### ISSUE THREAD

**Issue by kevinjuneja** [cytoscape/cytoscape.js#1329]
I was wondering if it was possible to set a pan limit. Ideally, I want to be able to limit it to the height/width of the graph so the user can't pan the viewport such that there aren't any nodes/edges visible. 

As an aside, would this functionality also prevent the user from being able to zoom in/out to a point where there are no nodes?

**Comment by maxkfranz** [comment]
Global pan limits aren't really meaningful, because pan is measured in rendered co-ordinates.

Rather than having snapping points for panning, you may be better off having a fit button.  That's generally useful anyway.

Having strict pan limits would interfere with some zooming cases too.  If you really want, you could check whether the viewport [extent](http://js.cytoscape.org/#cy.extent) overlaps with the [bounding box](http://js.cytoscape.org/#eles.boundingBox) of the graph at the end of panning gestures. You could animate back to something like a centred view at that point.

**Comment by vincerubinetti** [comment]
Here is a solution I'll be using.

```ts
let justPanned = false;

graph.current.on("viewport", () => {
  if (!graph.current) return;

  /** prevent infinite recursion from pan adjustment */
  if (justPanned) return (justPanned = false);
  justPanned = true;

  /** get current graph props */
  const zoom = graph.current.zoom();
  const pan = graph.current.pan();
  const width = graph.current.width();
  const height = graph.current.height();
  const paddingH = width / 2;
  const paddingV = height / 2;

  /** get bounding box of graph elements */
  const { x1, y1, x2, y2 } = graph.current.elements().boundingBox();

  /** limit left pan */
  if (x2 * zoom + pan.x < paddingH) pan.x = paddingH - x2 * zoom;
  /** limit up pan */
  if (y2 * zoom + pan.y < paddingV) pan.y = paddingV - y2 * zoom;
  /** limit right pan */
  if (x1 * zoom + pan.x > width - paddingH)
    pan.x = width - paddingH - x1 * zoom;
  /** limit down pan */
  if (y1 * zoom + pan.y > height - paddingV)
    pan.y = height - paddingV - y1 * zoom;

  /** adjust pan */
  graph.current.pan(pan);
});
```

Note the padding, which is written such that if the user is dragging the view to the left, it will never let the right-most content pass the center of the canvas, and etc. for the other directions. I find this to be good UX. It also handles zoom and such just fine. It may need to be modified to handle animations.
