### ISSUE TITLE
Tainted canvas when exporting PNG

### ISSUE THREAD

**Issue by michalhabala** [cytoscape/cytoscape.js#1363]
Hi @maxkfranz . I'm using images as node background and these images are from different domains. When I want to export visualization as a PNG image I get error in console "Unable to get image data from canvas because the canvas has been tainted by cross-origin data." and the image is not exported.

I figured out that a simple fix is to add 
`image.crossOrigin = "Anonymous";`
in **BRp.getCachedImage()** method right before
`image.src = url;`

I want to ask you if this is the right solution (modifying the library) and if you can consider to add it to CY.

**Comment by maxkfranz** [comment]
@michalhabala Thanks for the information.  It looks like [you're right about the `crossOrigin` field](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image).

Since you've already found, made, and tested a fix, it would be great if you would send a pull request for your change.

I've marked this for a 2.6.12 patch release

**Comment by maxkfranz** [comment]
@michalhabala Thanks.  I've cherry-picked this to the unstable branch for 2.7 too.

Here's a snapshot you can use until the offocial 2.6.12 release is pushed to npm etc : http://js.cytoscape.org/download/cytoscape.js-snapshot-a5e6cec48f-1462876048971.zip

**Comment by maxkfranz** [comment]
I'll release this on Thu/Fri, along with whatever other bugfixes happen this week (if any).
