### ISSUE TITLE
Compound node is not dragable if it contains non-visible children.

### ISSUE THREAD

**Issue by aindlq** [cytoscape/cytoscape.js#1371]
I'm trying to do some ad-hock collapse/expand feature for compound nodes. And it seems that it is not possible to drag compound node as soon as it has non-visible children.

See: http://jsbin.com/didunafota/1/edit?html,output
If you comment `'visibility': 'hidden'` it will be possible to drag compound nodes.

**Comment by maxkfranz** [comment]
(1) Invisible nodes aren't draggable or otherwise interactive -- else hidden elements would make it difficult to interact with visible ones.

(2) A compound node has no dimensions or position defined for itself -- those are inferred from the children.  It follows by (1) that if all children are invisible and undraggable, then parent is not draggable.

Because (2) is dependent on (1), it suffices to prevent (1) to get your usecase working for you.  Simply don't make children invisible.  

You can make them practically invisible with a nonzero opacity very close to zero -- e.g. `opacity: 0.001`.  Because the opacity is nonzero, it's technically not invisible and so the children are still draggable.

**Comment by maxkfranz** [comment]
You may also want to use `events: no` on the children

**Comment by aindlq** [comment]
Thank you for explanation! Your proposal works like a charm.

I'll keep example here for future references: http://jsbin.com/nuvociwudo/1/edit?html,output
