### ISSUE TITLE
Segment edges "segments-weights" property doesn't accurately map points

### ISSUE THREAD

**Issue by Rockster160** [cytoscape/cytoscape.js#1388]
+1 For support for Zig Zag edges: https://github.com/cytoscape/cytoscape.js/issues/882
Would make this all much easier, but until then, let's math it up!

Source Node Position = `{x: 236.5, y: 160}`
Target Node Position = `{x: 396.5, y: 300}`
Edge CSS: `{"segment-distances": "53.151 -53.151", "segment-weights": "0.11 0.89"}`

<img width="789" alt="screen shot 2016-05-27 at 10 54 26 pm" src="https://cloud.githubusercontent.com/assets/8505362/15625388/0d848e1c-2462-11e6-9b6f-568e628ee50e.png">

The segment weights state that the points should occur at approximately 10% from either end of the line, but it's clearly closer to 20-30%. 

Is there something I'm not understanding in the way the points are determined? Or is this a possible bug in the segment edges?

**Comment by maxkfranz** [comment]
This issue was missed somehow.  The points are calculated from the end of the shape where the imaginary line would intersect the node shape.

You can use the `edge-distances` property if you'd like to instead use the node position itself as the starting point: http://js.cytoscape.org/#style/segments-edges
