### ISSUE TITLE
Edge disappears when nodes have bigger size

### ISSUE THREAD

**Issue by chrjs** [cytoscape/cytoscape.js#1405]
Get the "Edge types" demo. Change the node style to width:150 and height:50.
Launch the demo. Move the second node of the Bezier under the first one. both are connected with 3 edges. Moving the second node, sometime one of the edge is not visible.
See here the result: 
![hidden-arrow](https://cloud.githubusercontent.com/assets/227026/15971049/042d7230-2f38-11e6-8df1-fabdc08ae51a.png)

**Comment by maxkfranz** [comment]
Some geometries create impossible bezier curves that can not be drawn.  You have to update (usually increase) the control point distance so that it's appropriate for the rest of your stylesheet.

See:

- http://js.cytoscape.org/#style/bezier-edges
- http://js.cytoscape.org/#style/unbundled-bezier-edges

**Comment by chrjs** [comment]
Thank you @maxkfranz: I solved my case by increasing control-point-step-size to 100.
