### ISSUE TITLE
Edge target arrows not working in unstable branch

### ISSUE THREAD

**Issue by mbeynon** [cytoscape/cytoscape.js#1408]
I noticed that edge source or target arrows are missing when using the unstable branch.  The standard cy demo show below.  Is this a known issue?

<img width="1164" alt="screen shot 2016-06-13 at 2 25 19 pm" src="https://cloud.githubusercontent.com/assets/5722945/16018601/23d6d1a2-3173-11e6-9bbc-2b2d9c3bcd28.png">

**Comment by maxkfranz** [comment]
The default stylesheet changed and haystack edges are default for performance.  See 

- https://github.com/cytoscape/cytoscape.js/issues/1199
- http://js.cytoscape.org/#style/edge-line

I'd appreciate it if you'd create a question for this on Stackoverflow that I can answer, because Stackoverflow usually is on the top of Google search results -- and that's how a lot of Cy.js users search for solutions.

Thanks

**Comment by mbeynon** [comment]
That's ironic, since I rebased unstable to include that change and didn't realize that was my problem.  I posted the question on SO.

**Comment by maxkfranz** [comment]
Great!  Answered the question on SO

**Comment by fracz** [comment]
[The question on SO](http://stackoverflow.com/questions/37822572/edge-target-arrows-not-working-in-cytoscape-js-2-7-0)
