### ISSUE TITLE
for( var key in obj ) => for( var i = 0; i < Object.keys(obj).length; i++ ){ ... } where possible

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#1425]
We used `for in` more conservatively than needed, because at one point the renderer was SVG only and so we wanted IE8 support.

We shouldn't lose any browser support by using `Object.keys()` now that we use canvas.

**Comment by EyMaddis** [comment]
Just a small heads up that the title is not correct, since the variable `i` does not actually have any helpful info for propertynames. Array iterations would/should not use `Object.keys()`.

Another thing to note is that `.map()` and `.forEach()` might be a better choice when it comes to function without side effects since it is easier for engines to optimize (and more readable), (not really a reference, but) see [this article](https://ryanpcmcquen.org/javascript/2015/10/25/map-vs-foreach-vs-for.html)

**Comment by maxkfranz** [comment]
It's just a shorthand.   `for( var i... )` should be used to iterate over the keys, because `.forEach()` is slow.

`for in` should never really be used to iterate over arrays.  I know the code in this repo isn't.

**Comment by maxkfranz** [comment]
( `.forEach()` is fine for dev app-level code where performance doesn't matter as much.  A dev can choose whether his code uses `for(...; ...; ...)` or `.forEach()` if it affects his perf.  He can't choose/change a lib's use of each.  We use plain `for` except for maybe one or two places where the arrays are very small and there was a big readability improvement.  Plain `for` is better by default for libs where perf matters.)

**Comment by maxkfranz** [comment]
Failing on node@0.12
