### ISSUE TITLE
all nodes drawn at (0,0) with picnicss

### ISSUE THREAD

**Issue by jtal** [cytoscape/cytoscape.js#1448]
I was just wondering if anyone has used picnicss with cytoscape?

All the nodes seem to get drawn at (0,0) despite position or renderedPosition being set to something else.

https://github.com/picnicss/picnic

**Comment by maxkfranz** [comment]
Please create a sample that reproduces your issue

**Comment by jtal** [comment]
Here's what was happening. My container is a div with id "cy". In a css file I set an initial height for #cy and on document ready I invoke cytoscape then resize height of #cy to fill the window. When the browser window is resized, I call my resize() again so #cy height always matches the browser height.

The problem is when I import picnic css something goes wrong. I suspect that at the time cytoscape() is called the height is very small. So it draws all the nodes at what appears to be (0,0).

I found two ways to get around this:

1. Call resize() before cytoscape()
or
2. Set initial height inline within #cy div instead of setting it in the css file. This must be a precedence thing.

Here is an example. I dont think there is anything for you to fix. Thank you for cytoscape by the way. ;)

https://gist.github.com/jtal/ec5a67f547eb038765afc393de0af919

**Comment by okoriko** [comment]
It seems this bug appear from `2.7.3` to 2.7.4`. Reverting to `2.7.3` fixed it in my case.

**Comment by maxkfranz** [comment]
There is no issue in Cytoscape related to this.  This is clearly expected behaviour.

Of course, Cytoscape gets the dimensions to use in a layout from its DOM element by default.  That way your graphs fits your div nicely.  If you don't size your div properly *before* a layout is run, how should Cytoscape know you want to use a larger space?

Size your div properly before running layouts (e.g. init or `cy.layout()`) or use a manual `boundingBox` specified to the layout.  Run a layout a second time after you resize your div if you really want.  

Just make sure you specify your sizes appropriately *before* layout.
