### ISSUE TITLE
Intersections can fail on polygons because of floating point inaccuracy

### ISSUE THREAD

**Issue by fedarko** [cytoscape/cytoscape.js#1466]
This is a similar issue to #1451 (edges are invisible upon the graph initially being rendered, but are clearly visible and valid when the edge's source or target nodes are moved in any direction—even when moved to be closer together), but with straight-line bezier edges (`'curve-style': 'bezier'`).

[Here's](https://output.jsbin.com/rehala) a demonstration of this error in effect (edges 138->137, 137->136, and 136->135 are all invisible and tagged with `._private.rscratch.badLine === true`), and [here's](https://jsbin.com/rehala/edit?html,js) the source code for this demonstration on JSBin. Changing all nodes' y-coordinates to -42 does resolve this particular instance of the problem, but that seems like something the Cytoscape.js renderer should take care of regardless.

**Comment by maxkfranz** [comment]
The issue is not that the line checks are too strict.  The issue is floating point inaccuracy on apex points:  When calculating intersections, the renderer does finite line intersections to calculate where the edge endpoints should go.  

Your edges point to the righthand apex point of your polygons.  This -- coupled with slight floating point inaccuracy and particular node positions -- makes some of the intersections fail.  That is, the intersection is seen as right on the apex point but with a slight float inaccuracy such that neither line segment is considered a hit.  Note if you change the style to `'shape-polygon-points': "-1 1 0.25 1 1 0.001 0.25 -1 -1 -1"` it works in this case (but other orientations may fail).

This commit cleans up the `math.finiteLinesIntersect()` function and adds a threshold to accommodate floating point inaccuracy.  The cleanup should make the function a bit faster -- easier to read anyway.

If anyone encounters this issue in the future, it may mean that the threshold needs to be updated.  I use a threshold of 0.001 for values that range on [0, 1].  The example in the OP is off by 0.0000000000000002.

**Comment by maxkfranz** [comment]
Try the snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-9e0e87baff-1469549663171.zip

Let me know if it works for you or if you have any issues with it.  

Thanks

**Comment by fedarko** [comment]
The snapshot works perfectly for me. Thank you!

**Comment by maxkfranz** [comment]
Great
