### ISSUE TITLE
Feature request: pie-i-background-image

### ISSUE THREAD

**Issue by witvliet** [cytoscape/cytoscape.js#1480]
It would be great to be able to set a background-image for each slice in pie charts. This would allow switching to a color-friendly mode, where, in addition to the background-color, there would be a unique pattern for each color (defined by the images).

**Comment by maxkfranz** [comment]
This looks interesting.  I'm a bit torn on it, though, because the pie properties only really came to be because browser SVG support (within canvases) was very lacking at the time.  Now, it's possible to set a SVG background image for a node that has arbitrary pie charts (or even other charts).

The pie feature may be replaced by an extension for this reason in 3.0.  That would help to make performance better for this feature (and overall) and to simplify the lib.  It would also make it easier to add more customisations for the charts, including the feature you've mentioned here.

**Comment by maxkfranz** [comment]
In v4, there will be no pie support.  It would be replaced with an extension using SVGs.  In that case, you could just modify the SVGs used in the extension.
