### ISSUE TITLE
All vertices are drawn in a single point [2.7.4-2.7.8] versions

### ISSUE THREAD

**Issue by AntoniBertel** [cytoscape/cytoscape.js#1500]
Hi,

My dependencies are:
1. cytoscape 2.7.8
2. cytoscape-cola 1.4.1
3. cola 3.1.3

I removed all custom styles/settings. 

Rendering flow is: 
```
var cy = window.cy = cytoscape({
        container: document.getElementById('cy')
        style: []});
var layoutParams = {
       name: 'cola'
 };

var layout = cyGraph.makeLayout(layoutParams);

// removing prev. elements and add elements
cyGraph.elements().remove();
cyGraph.add(nodes.concat(edges));
layout.run();
```
And all vertices are drawn in a single point. After i can drag-and-drop them. Please look at the screenshot.

![cys](https://cloud.githubusercontent.com/assets/15714604/17837864/67b9da42-67c7-11e6-8c35-172573fbb56e.jpg)

The problem is not reproduced for version 2.7.3 and lower.

Could you please advise what I'm doing wrong?

**Comment by AntoniBertel** [comment]
I changed `layout.run()` to `cyGraph.layout(layoutParams)` and it fixed the problem.
But how can i pre-compile template to spend less time>

**Comment by maxkfranz** [comment]
`cy.makeLayout()` is the same as `cy.elements().makeLayout()`

So, you're running a layout with no element, because you created the layout with an empty graph.  Your workflow in 2.7.3 relies on a bug to work : https://github.com/cytoscape/cytoscape.js/issues/1432

Make the layout with the elements you want, and then you can `layout.run()` multiple times.  Or, if you change the graph elements, you should just be reusing the layout options and creating new layouts each time.  It's very cheap to make a layout -- running them is the part that can be expensive.

**Comment by AntoniBertel** [comment]
Thank you for the answer.
It looks like with modified collection i spent a less time to re-render graph.
