### ISSUE TITLE
cannot avoid randomization of cose

### ISSUE THREAD

**Issue by EyMaddis** [cytoscape/cytoscape.js#1502]
It seems that [this commit](https://github.com/cytoscape/cytoscape.js/commit/1fe472708a5e9c62730e6533df9ba0ee6f3bb18d#diff-35aeced70ffa367d41eb274759dc4686L123) disabled the `randomize` flag. I wonder why and if that might be a regression as I would like to disable randomization.

**Comment by maxkfranz** [comment]
Try the snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-75a15818da-1471965465726.zip

Let me know if it works for you or if you have any issues with it.  

Thanks

**Comment by EyMaddis** [comment]
@maxkfranz it seems that all node are now on the same position and huge.

Could you provide a git commit hash/branch? That way I can use npm as dependency management as I did before testing the snapshot. I could then make sure that it is loaded exactly as the release version.
Thanks

**Comment by maxkfranz** [comment]
The commits for every issue is always cross-referenced in the issue (see above): 75a15818da5662c9e78930b157f8745885aca6a8

**Comment by maxkfranz** [comment]
@EyMaddis Is it working for you?  The snapshots are always labelled `cytoscape.js-<hash>-<timestamp>.zip`, so I think you should be able to use `cytoscape: http://path-to-repo.git#hash` in your package.json.

**Comment by EyMaddis** [comment]
@maxkfranz sorry for the delayed response.
I installed it via npm and can confirm, that the problem mentioned above does not change based on the dependency management.

>  it seems that all node are now on the same position and huge.

**Comment by maxkfranz** [comment]
@EyMaddis If you don't have initial positions defined for nodes, then they're all at (0, 0) at init.  You must enable randomisation in this state if you want force-directed/physics layouts like CoSE to work.

**Comment by maxkfranz** [comment]
(Consider that forces are proportional to distance and if distance is zero, then forces may not be well defined.)

**Comment by EyMaddis** [comment]
@maxkfranz in that case it "works" 😛 
What I would have expected was some randomisation, but based on a fixed seed, that is how `cose-bilkent` does it.

**Comment by maxkfranz** [comment]
CoSE-Bilkent is more feature rich, but it has a much larger file size because it implements a lot of custom things -- like its own PRNG that can accept a custom seed value.

The default CoSE isn't nearly as sophisticated as CoSE-Bilkent -- and probably never will be -- but it adds only a small size to the lib and it's very fast to run.

It might be good to have something like a `prng-random` layout extension that acts like the built-in `random` layout but with a PRNG that can accept a custom seed etc.  Anyone can then just chain layouts together (e.g. `prng-random` then `cose`) to use a more controlled randomisation.
