### ISSUE TITLE
fail to render background image with IE11.

### ISSUE THREAD

**Issue by jiangliu** [cytoscape/cytoscape.js#1504]
We have tracked down a failure to render background image with internet explorer 11, which was introduced with v2.6.12. A line of code, seems to solve some sort of issues, caused this regression with IE11. Comment out the line "image.crossOrigin = 'Anonymous'; // prevent tainted canvas" fixes the regression.

BRp.getCachedImage = function(url, onLoad) {
  var r = this;
  var imageCache = r.imageCache = r.imageCache || {};

  if( imageCache[url] && imageCache[url].image ){
    return imageCache[url].image;
  }

  var cache = imageCache[url] = imageCache[url] || {};

  var image = cache.image = new Image();
  image.addEventListener('load', onLoad);
  image.crossOrigin = 'Anonymous'; // prevent tainted canvas
  image.src = url;

  return image;
};

**Comment by maxkfranz** [comment]
`image.crossOrigin = 'Anonymous'` is a standard browser feature.

If we remove this line just for IE, we'll break legitimate usecases for modern browsers.

**Comment by jiangliu** [comment]
got it, thanks:)

**Comment by maxkfranz** [comment]
You could try embedded images that are base64 encoded rather than a URL, but that's just a guess.  It might bypass IE's bug because it's a different way of loading the file...

**Comment by jharwig** [comment]
Just hit this too on IE11 (which supports CORS), loading urls on the same origin with a crossorigin="anonymous" on the image won't send credentials, so was getting 403s because the images are protected. Testing with crossorigin="use-credentials" did work.

Can the renderer check the domain and set one or the other? Or some way to tell the renderer what to use?

**Comment by maxkfranz** [comment]
No, this is not something that the renderer can check.  You need to make sure your images are accessible without auth.

See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-crossorigin

We can't set `use-credentials`, because that will break things for everyone who serves images normally.  Checking the domain tells you nothing.  You need to get the HTTP header back, and by that time it's too late.

Presumably, you could control this with a new style property.  But I don't have time to add and test that right now.

**Comment by jharwig** [comment]
Thanks for the reply, I wasn't suggesting to replace it to send credentials. Unfortunately the images have to be protected. Other browsers work fine, it's just IE that takes anonymous literally, and doesn't send credentials even when there's no cross origin.

But why do I even need CORs here if I'm serving images from the same origin (even using relative urls)?

**Comment by maxkfranz** [comment]
From the MDN: 

> **When not present**, the resource is fetched without a CORS request (i.e., without sending the Origin: HTTP header), **preventing its non-tainted usage in <canvas> elements**. If invalid, it is handled as if the enumerated keyword anonymous was used. See CORS settings attributes for additional information.

The attribute needs to be set even if the image doesn't technically require CORS.  Otherwise, the browser treats the canvas as "tainted" and things like `cy.png()` won't work at all.

**Comment by maxkfranz** [comment]
There's probably a security concern that the HTML5 spec is trying to address, but it makes handling images a pain.

**Comment by jharwig** [comment]
okay, thanks for your help. For now I'm just replacing getCachedImage with an implementation that switches the crossOrigin value to 'use-credentials'.

**Comment by maxkfranz** [comment]
OK, made a ticket to track the new feature: https://github.com/cytoscape/cytoscape.js/issues/1607

If anyone wants to create the property in a PR, we could merge this in for 3.1
