### ISSUE TITLE
Will there be support for double click event?

### ISSUE THREAD

**Issue by mazing** [cytoscape/cytoscape.js#1518]
http://www.w3schools.com/jsref/event_ondblclick.asp

**Comment by maxkfranz** [comment]
A `dblclick` event would cause issues with touch devices:

(1) It's not a normal touch gesture.  It means you can't support touch well.  It's also a fairly hidden gesture on desktop, and it's much harder to do than a regular click.

(2) It causes problems when implemented.  The reason tools like Fastclick exist is to work around issues caused by `dblclick` support on touch -- that ~300 ms event delay is caused by `dblclick` support.

(3) `dblclick` can be implemented pretty easily on top of the existing events.  A `sglclick` event could also be easily implemented to differentiate between `click`s that are part of a `dblclick` and those that stand alone.  This could be packaged as a third-party extension for people who are interested in the feature.  These higher level events aren't exactly like the DOM implementation, but it would avoid the issues the DOM implementation has, like the ~300 ms delay.

For these reasons, I don't think the core will ever implement `dblclick`.  If anyone's interested in implementing a reusable extension for it, I'd gladly add to the extension list.

**Comment by hrvoj3e** [comment]
Just want to put this here. https://stackoverflow.com/a/58612489/2450431
```
cy.on('tap', 'node', function(evt){
  let node = evt.target;
  console.log('tapped ' + node.id());
  if (node.selected()) {
    console.log('selected ' + node.id());
  }
});
```
