### ISSUE TITLE
ungrabify() resets selection

### ISSUE THREAD

**Issue by buffpojken** [cytoscape/cytoscape.js#1524]
When having a group of nodes, pictured below - I want to drag them as a cluster if grabbing by the larger node in the center, and I don't want the smaller nodes to be grabbable at all.   

<img width="181" alt="screen shot 2016-09-12 at 16 35 08" src="https://cloud.githubusercontent.com/assets/47125/18439809/0045a138-7907-11e6-8d33-be4e85de68f1.png">

My first solution was to set the smaller nodes to ```grabbable: false``` in the event json, then on mouseover for the main node, fetch them, ```grabify``` them, add the middle node to the neighbourhood and then ```select()```. This works fine, except when I want to reset the grabbable-state of the smaller nodes to false. 

I tried the solution below: 

```
				let collection = e.cyTarget.neighbourhood('.virtual'); 
				collection.grabify().add(e.cyTarget).select();
				e.cyTarget.neighbourhood('.virtual').ungrabify();
```

but apparentely ```ungrabify()``` will overrule the selection already created, and "drop" the nodes matching ".virtual". The main node (```e.cyTarget```) is still selected and draggable just fine. 

What's the proper way to do this? My initial thought was that this would result in the selection remaining just fine (since it's created programmatically) but that's apparently not the case?

**Comment by maxkfranz** [comment]
The correct solution is not to grabify and ungrabify mid-gesture.  You have no guarantees of when grabbable state is checked during gestures.

Instead, just ungrabify the nodes you don't want grabbable.  Simply update the nodes you want dragged along during `drag` events on the main node.  If you get the initial position of the grabbed node on `grab`, you can calculate delta vectors on each `drag` event -- updating the positions of the secondary nodes by those delta vectors.

If you have a strict ruleset for the orientation of the secondary nodes w.r.t. the primary node, you can use the [automove extension](https://github.com/cytoscape/cytoscape.js-automove) and just specify that rule instead of keeping track of deltas.

**Comment by buffpojken** [comment]
Aah, I understand - so basically no change of "permitted" actions mid-gesture. 

Having had a quick read through automove I believe it suits my purposes just fine, thanks for the headsup!

**Comment by maxkfranz** [comment]
Great.  If you have any feedback on the automove extension, please let me know -- as the extension is relatively new.

**Comment by buffpojken** [comment]
Will do, thanks!
