### ISSUE TITLE
Edge arrows appear to fake opacity

### ISSUE THREAD

**Issue by somedmguy** [cytoscape/cytoscape.js#1542]
![image](https://cloud.githubusercontent.com/assets/21342204/18734072/8a4842e4-8025-11e6-96ef-ae585e1e03c4.png)

What we have here is two edges pointing in opposite directions (with target arrows enabled).  Both edges and their arrows are the same color with the same opacity.  It would the seem that the arrows are faking their opacity by calculating a new color based on the background and that the edge pointing to the left is on top of the one pointing to the right.  This explains the correct overlap coloring on the right side, but the solid arrow coloring on the left.

I guess this was an intentional performance optimization?

**Comment by maxkfranz** [comment]
The canvas is cleared behind an edge arrow -- otherwise part of the line that overlaps the arrow would show through with 0 < opacity < 1.  For straight edges and triangle arrows, this isn't obvious.  But consider other edge line styles (like curved) that can be combined with different arrow types:  Most lines overlap their arrows at least a bit.

The only other solution is to clip the line -- but unless that's changed recently in the browsers, a the equivalent clipping operation is dead slow.

I'm not happy with the current solution either, but the alternative is a major slowdown (at least 10x iirc) in performance for graphs with edge arrows.
