### ISSUE TITLE
Segment edges disappear if nodes are to close

### ISSUE THREAD

**Issue by Flui** [cytoscape/cytoscape.js#1543]
I am using segment edges wih edge-distance calculated by node-position and if the nodes are to close to each other, they disappear.

fiddle example: http://fiddle.jshell.net/Fjuri/b2xhjnfe/

**Comment by Flui** [comment]
it seems as it has to do with the segment. my poblem is that sometime i need segments and sometimes not . Is there a way to use segment syle, node-position for edge-distance without segmentation?

**Comment by maxkfranz** [comment]
An edge is not drawn if it's created contradictory/impossible positioning.  For example, that happens when two nodes overlap -- no intersections may be calculated for the edge.

In your demo, I notice you specify an invalid point w.r.t. the larger node for many orientations.  If you just specify a small distance, you can see the point:

 
<img width="499" alt="screen shot 2016-09-22 at 3 44 06 pm" src="https://cloud.githubusercontent.com/assets/989043/18763502/a93b3290-80db-11e6-8d34-5733b8b35887.png">

Because you can see the point (at the bend because we specified a small distance), you can see it will overlap the big node if you move the small node any closer.

You need to specify points that are valid for any orientation.  That's generally easier if you nodes are smaller sizes.  But for the example you give, it's not at all necessary to use a segment edge style -- you can just use the default `bezier` style, which uses a straight line for the first edge between two nodes.

In 3.1+, you will be able to make this easier with `edge-pointing-direction`: https://github.com/cytoscape/cytoscape.js/issues/1454.

**Comment by Flui** [comment]
My usecase is, hat I have two nodes and there positions in x and y coordinates and edge should go along a couple of supporting-points that are also defined with x and y coordinates.

So my fist problem was to get the weights and distances of these supporting points. Or is it possible to use x and y coordinates instead of weight and distance. Calculating he weight and distance is no the problem bu I would make some things easier id I could use the coordinates.

And If i got it right bezier can only show one supporting point.

**Comment by maxkfranz** [comment]
> So my fist problem was to get the weights and distances of these supporting points. Or is it possible to use x and y coordinates instead of weight and distance. Calculating he weight and distance is no the problem bu I would make some things easier id I could use the coordinates.

Only weights are supported.  Absolute positions would not update when the nodes are moved, leaving the edge point behind.

> And If i got it right bezier can only show one supporting point.

[`curve-style: bezier`](http://js.cytoscape.org/#style/bezier-edges) means automatically bundled beziers, with the first edge as just a straight line.  If you need a straight line with end arrows, that's what you should use.
