### ISSUE TITLE
DOT graph description language extension

### ISSUE THREAD

**Issue by mazing** [cytoscape/cytoscape.js#1555]
Are there any plans for implementing [DOT (graph description language)](https://en.wikipedia.org/wiki/DOT_%28graph_description_language%29), so it is possible to import/export graphs?

**Comment by maxkfranz** [comment]
That would be a great thing to support, but it would be something that would go into an extension rather than the lib itself.  For example, the iVis Lab at Bilkent University built the [`graphml`](https://github.com/iVis-at-Bilkent/cytoscape.js-graphml) extension to add GraphML support to Cytoscape.

As an extension, it would probably have the signature `cy.dot( dotFileStr )` to import and `cy.dot()` to export.

If you're interested in building this extension, take a look at the [scaffolder](http://js.cytoscape.org/#extensions/autoscaffolding).  It automatically generates the project for you, so you'd just need to fill in the dot-json (and vice versa) conversion.

**Comment by keiono** [comment]
There is a DOT support in Cytoscape desktop:

http://apps.cytoscape.org/apps/dotapp

And once you load your network into it, you can export it into Cytoscape.js JSON from _File &rarr; Export &rarr; Network and View_ menu item.

**Comment by maxkfranz** [comment]
A module that converts to cytoscape json could be built on top of this: https://www.npmjs.com/package/dotparser

**Comment by Remimstr** [comment]
I am considering implementing this extension so that I can use DOT to define my cytoscape graphs. Clearly there seem to be some unique challenges with this that I'd like to get your opinion on.

The DOT language doesn't seem to specify information about the position of the nodes (a feature that I actually prefer for my particular use case). How would you suggest addressing this? I am currently thinking this solution will likely involve trying to space the nodes evenly across the canvas in the X and Y directions.

**Comment by maxkfranz** [comment]
Everything but `data.id` is optional for nodes.  You don't need to specify a position.

Everything but `data: { id, source, target }` is optional for edges.

For data import/export, you should only consider element data, position being an optional component -- basically just element JSON.  The viewport, style, etc. are extraneous.

**Comment by Remimstr** [comment]
Ok I guess for my specific use case I'll have to build out additional functionality on top of dot. I'll give implementing this a go using the dotparser library you suggested.
