### ISSUE TITLE
Bind on key events

### ISSUE THREAD

**Issue by mazing** [cytoscape/cytoscape.js#1556]
Is it possible to bind on key events?

I couldn't find anything on http://js.cytoscape.org/#events about keys, but neither `cyContainer.onkeyup = function (event) {` nor `cy.onkeyup = function (event) {` works, so I wonder if there is any way to bind key events on the cytoscape canvas instead of the entire document (`document.onkeyup = function (event) {`

**Comment by maxkfranz** [comment]
It's not necessary to use any Cytoscape APIs for this.  I usually use [Mousetrap](https://github.com/ccampbell/mousetrap).  It lets you make global key bindings that don't conflict with text boxes etc.  For apps I've built, users like the global shortcuts -- but maybe this approach doesn't suit your particular app's UI.

If you want to bind to a particular div, take a look at this Stack Overflow: http://stackoverflow.com/questions/3149362/capture-key-press-or-keydown-event-on-div-element#3149416

**Comment by ignacy130** [comment]
For such code: `<div id="cy"></div>`
```
$('#cy').on('keydown', function (e) {
            console.log(e);
        });

        $('#cy').on('mouseout', function (e) {
            console.log(e);
        });
```
where `div#cy` is graph's container, `mouseout` event is triggered but `keydown` event not - so answer from StackOverflow is not working. 

Binding key events to specifiv element is pretty basic and functionality required in many more complex apps so having it would be great.

**Comment by source-transformer** [comment]
Just bumping this issue - we're not able to get key-bindings working using the suggested JQuery approach on stackoverflow.

**Comment by baveryt** [comment]
For what it's worth, it's not working because the cytoscape is binding the mousedown event which ultimately removes the focus on the div which then causes the key events not to work. You can get around this by adding another mousedown event on the div that restores the focus back to the div and then the key events will work.

`$('#cy').on('mousedown', () => {
      $('#cy').trigger('focus');
})`

You'll probably also want to set the css on the div to have outline: none on it to remove the focus style.
