### ISSUE TITLE
nodes.position() should return a list of positions

### ISSUE THREAD

**Issue by buffpojken** [cytoscape/cytoscape.js#1557]
Is there technical reasons for ```nodes.positions()``` without arguments not returning a list of 
positions for all nodes in the collection? 

Given that that's how ```node.position()``` works, I think that would be the path of least surprise? 

If there are technical reasons, how does one fetch all positions for a given collection in the best way? Looping?

**Comment by maxkfranz** [comment]
Because `nodes.positions()` is already plural for setting, I suppose it could return multiple values.  However, `cy.positions()` was created only because a generalised `cy.batch()` didn't exist yet.  The functions in the API are generally singular getters, unlike the plural `nodes.positions()`.

 Now, there really is no need for `cy.positions()` to exist anymore when you can just `cy.batch( () => updateAllThePositionsIWant() )`.  Similarly, for your usecase I would just `nodes.map( n => n.position() )`.

Some background:

In general, for collection functions that return a (non-chaining) value, the value for the first element is returned.  That means you won't get every value for collections of size 2 or greater.

There are several reasons for this, the most important of which is consistency.  Lots of function don't make sense to return multiple values, and it would be confusing if some functions do and some don't.  Another major reason is that it's the jQuery collection convention.  We tried to design the API to be similar to jQuery where possible to make it easier for devs to use -- because so many devs are already familiar with it.

**Comment by buffpojken** [comment]
Aaah, I see - it makes a lot of sense if ```cy.batch()``` didn't exist at the time of implementation. 

I'll use ```collection.map``` for this - thanks for the prompt reply!
