### ISSUE TITLE
Custom Code Flower Layout

### ISSUE THREAD

**Issue by aayush-aditya** [cytoscape/cytoscape.js#1578]
[cytoscape2.txt](https://github.com/cytoscape/cytoscape.js/files/538151/cytoscape2.txt)

Wrote a custom layout on Cytoscape Concentric layout, but in that cytoscape nodes and edges doesn't pick up style properties on dynamically added nodes and code breaks.
In Code Flower layout I intend to give specific arc for the last layer of nodes based on the penultimate layer no. of nodes. 
The code works perfectlly fine if we specify data for nodes and edges statically.
Even it works fine if we do cy.add and cy.remove,
But when we use cy.batch() function code breaks while Cytoscape is trying to plot the same,
the reason behind this is for the newly added nodes the style properties are not assigned and it breaks in the cytoscape's code and not the one where we manipulated.

Could you guys please look in to the same.

Thanks and Regards,
Aayush Aditya
![static works fine](https://cloud.githubusercontent.com/assets/16115711/19508964/b58e7e2a-95f9-11e6-898b-9c5d84169447.png)

**Comment by maxkfranz** [comment]
You can't read style properties reliably during a batch, because styles get applied after the batch block by definition.  See http://js.cytoscape.org/#cy.batch

You can read `.width()`, `.boundingBox()`, etc. more reliably -- but those values may be zero during batching if you added the elements in the same batch block.

You would probably find it easier to work on your layout in an extension, rather than doing a modified build.  The extension can be [automatically generated for you](http://js.cytoscape.org/#extensions/autoscaffolding) so you can just paste in your code.  Using an extension you put in a Github repo will also mean you can just use the vanilla `cytoscape` npm/bower package with your layout package in your apps.

**Comment by aayush-aditya** [comment]
Hi Max,

Went the same way as suggested by you, helped me to get the requirements
done.

Regards,
Aayush Aditya,
+91-9206251938/ + 91-7079227109
aay.adityapat@gmail.com
