### ISSUE TITLE
Feature Request: give the ability to check if extension has been already registered.

### ISSUE THREAD

**Issue by aindlq** [cytoscape/cytoscape.js#1585]
`cytoscape.register( type, name, impl )` : alias of cytoscape() to register an extension

`cytoscape.isRegistered( name )` : get whether extension with specified name is registered on this instance of the lib

OP follows:

---

Would be great to be able to check if extension has been already registered. I can track this on the call-site but it seems internally everything is there in https://github.com/cytoscape/cytoscape.js/blob/master/src/extension.js one just need to expose some api for `extensions`.

Maybe it can be interesting to someone, but currently it is possible to do this check in a quick and dirty way using cytoscape internals:

```
import * as CytoscapeCore from 'cytoscape/src/core/index';

...

if (!CytoscapeCore.prototype[extesionName]) {
  registrationFn(cytoscapeApi);
}
```

**Comment by maxkfranz** [comment]
It's probably better if you just check for existence on an instance or the prototype, e.g.

```js
let hasFoo = someEle.foo != null;
let hasFooOnPrototype = Object.getPrototypeOf( someEle ).foo != null;
```

**Comment by roballsopp** [comment]
I do like the clean modularity @aindlq's suggestion would lend. I have multiple react components that need cytoscape-canvas to be registered. Currently, I have to register cyCanvas once in some higher component or bootstrap file that is fairly removed from the components that actually need cyCanvas. It would be great to do the registration at the top of the file of each component that uses cyCanvas, both for the clarity it would bring (easier for another developer to see where this magical cyCanvas() function came from thats not in the main documentation), and so if I ever remove those files, cyCanvas is no longer registered without my remembering to do the additional code cleanup of my bootstrap file. Checking an instance would force me to put my registration inside a component, which would mean I'd have to do the check on every render, or at least every time the graph instance changed. Not a huge deal, but not super ideal either.

**Comment by maxkfranz** [comment]
I see what you're saying, @roballsopp.  On the other hand, putting a `Cytoscape.register()` call makes it so that you can't use Cytoscape outside of a React component itself.  Maybe that's not important for your usecase, but I've found your approach to be problematic in some of our projects.

Some usecases of note:

- Use a headless Cytoscape instance for layout or algorithms.
- Use Cytoscape instances in different React components.
- Use shared Cytoscape code across the server and the client.

For usecases like those, I've found it's much better to just to put the registrations in a central file.  That approach guarantees that wherever you use Cytoscape, the set of available extensions is the same.
