### ISSUE TITLE
eles.contains()

### ISSUE THREAD

**Issue by SumNeuron** [cytoscape/cytoscape.js#1596]
Please add a function for testing whether or not a given element is part of a collection.
Yes this can be achieved by testing to see if the intersection of the collection and the element is the element in question, but that is verbose.

It appears the above strategy doesn't work as:

`cy.nodes().intersection(nodeInQuestion) === nodeInQuestion` 

always returns false

`cy.elements().intersection(nodeInQuestion).empty()`

however works....

**Comment by maxkfranz** [comment]
You can't do equality checks on collections, because collections are immutable and APIs give you a new one each call.  You can use `.same()`.

You should use something like `has = ( a, b) => a.intersection( b ).nonempty()`

There could be an alias in the API, though.  Maybe with a name like `.has()` or `.contains()`

**Comment by SumNeuron** [comment]
Ok so simply define the function has and instead use nonempty for a similar logic as the function proposes.
