### ISSUE TITLE
Allow non-string values to be specified as string property values (e.g. `label`)

### ISSUE THREAD

**Issue by tbaeg** [cytoscape/cytoscape.js#1620]
Coerce non-string values to strings when specified to string style property values.  This will make it easier for devs who specify objects that can be `.toString()`ed.

OP follows:

---

When setting a label of anything falsy, does not render node labels. I came into a scenario where my node label was 0. Unfortunately, the label did not render due to the falsy check here.

https://github.com/cytoscape/cytoscape.js/blob/06e11b9c6792622d4d96be3da8b3001423465bff/src/extensions/renderer/canvas/drawing-label-text.js#L39

Simply removing the falsy check and checking for equality on an empty string resolved my issue. Making a PR now. Haven't dived into the source heavily so not sure what other side effects this may cause outside the scope of the function.

**Comment by maxkfranz** [comment]
`'0'` is not falsey, and the check definitely needs to include `null` and `undefined`.  You should specify the proper type for the property -- `label` is a string, not an integer.

Probably all string properties should have `.value` coerced to a string (as `.strValue` is).  The checks need to be kept simple for rendering functions to avoid error (like missing null) and to keep performance fast (otherwise we could just use nice functions like `is.emptyString()` -- but that's too expensive since it uses `typeof` checks etc.).

**Comment by tbaeg** [comment]
Apparently, I was on something when I said '0' was falsy.. apologies, you are absolutely correct.

**Comment by maxkfranz** [comment]
That change should make it so any value that has `.toString()` converted to a string.  That should work for numbers (e.g. `(0).toString() === '0'`) or complex objects:

```js
let hello = {
  toString: function(){ return 'hello world'; }
};

cy.nodes.style('label', hello);
```
