### ISSUE TITLE
mapData and zoom

### ISSUE THREAD

**Issue by buffpojken** [cytoscape/cytoscape.js#1676]
Is it possible today to use graph-level data as source in mapData style mappers, more specifically - zoom? If not - is there some way to get the graph containing a specific element from the element itself (as in - the argument to a regular style mapper function)? 

I've tried to investigate the second part of this question using console debugging without much luck.

**Comment by maxkfranz** [comment]
No, and it's not a good idea to vary style based on zoom because of performance.  Having a continuous mapping to zoom would kill performance.

The only valid mapping to zoom would be discrete breakpoints like CSS media queries.  For those, you can just set classes on elements based on the zoom level, e.g. 

```js
cy.on('zoom', function(){
  let z = cy.zoom();

  if( z > 2 ){
    cy.elements().removeClass('z-lt-2').addClass('z-gt-2');
  } else {
    cy.elements().removeClass('z-gt-2').addClass('z-lt-2');
  }
});
```

**Comment by buffpojken** [comment]
Roger that, thanks for taking the time to provide the example!

**Comment by maxkfranz** [comment]
You should probably also use `cy.batch()` and `lodash.debounce()` on the callback for perf
