### ISSUE TITLE
Is there a way that i can tell whether a event is from element or its lable ?

### ISSUE THREAD

**Issue by ericleef0522** [cytoscape/cytoscape.js#1679]
I have an application with a function only happens when click on edge label but not on edge. I successfully us 'text-events' to make sure i can catch events from label, however i need a way to tell if it is from edge or label, is there a way i can make this happen ?  Many thanks !

**Comment by ericleef0522** [comment]
Thanks maxkfranz for taking this question, does this mean there is no way different event source between "edge" and "edge label" for now ? :)

**Comment by maxkfranz** [comment]
No, `text-events` is meant only to extend the hit-box area of the element.  There is no differentiation.

We already have lots of tickets planned for the next few releases, so features like this one would only get added in the short-term via community pull requests.

I assign the issue only because the Github notifications queue clears out quickly, and otherwise questions like these would be lost and unanswered.

**Comment by ericleef0522** [comment]
Hi maxkfranz, I understand, really appreciate for taking time on my question.  I will try to figure something out if have enough time. Will also contribute to you guys if i made this happen. Thanks.

**Comment by maxkfranz** [comment]
There's no API design and too little time left before the release.  Pushing to 3.8

**Comment by maxkfranz** [comment]
Superseded by #2502
