### ISSUE TITLE
Possible regression on #1331

### ISSUE THREAD

**Issue by buffpojken** [cytoscape/cytoscape.js#1693]
I have started to see some very weird behavior that exactly mimics the issue described in #1331 when running on 2.7.14 - can repro 100% of the time as well on both trackpad and mouse.

I've put up a reproducing test case at https://jsfiddle.net/6h4z6on9/1/ - see order of events in console when tapping the single node. AFAIU - this ought to not be the case past 2.6.8?

**Comment by maxkfranz** [comment]
I initially thought this may have been a bug, but it seems #1331 is wrong.  I was too hasty in granting the request in the ticket for #1331.  It's my mistake, and I'll try to be more careful about accepting community suggestions in future.  Sorry for the confusion.

If you tapstart on a node, you've grabbed it.  It's then necessary to have a free event on tapend to complete the gesture --- even if no drag happens.  This is necessary behaviour for several important usecases, and it's necessary for existing performance enhancements in 2.7 and future enhancements in 3.x.

This was fixed in 2.7, so 2.7 behaves correctly.  If you want to know when something is dragged, listen to the drag event -- not grab.

It's also of note that you generally have no guarantee of the order of events of unrelated gestures:

E.g. grab => drag => free is guaranteed

E.g. tapstart => tapend => tap is guaranteed

E.g. tap => free and free => tap are both valid and which one happens is unspecified in a grab/drag/free gesture.

**Comment by buffpojken** [comment]
Hmm, check - the only reason I filed it as a possible regression was due to the description of #1331.

I get why you'd want to model a tapstart as a grab - I'll use a debounced drag instead then! 

Thanks!

**Comment by maxkfranz** [comment]
OK, if you run into trouble for your usecase let me know.  We can add new events if needed, which is less risky than changing existing ones.
