### ISSUE TITLE
Reading .cyjs (elements) and .json (style) files

### ISSUE THREAD

**Issue by Rociocc93** [cytoscape/cytoscape.js#1709]
Hi all,

I am quite new in using Cytoscape.js and I have been having problems with some issues. 

I used the Cytoscape Desktop version to export the BIOGRID database nodes and edges (elements) into a .cyjs file so that I could then use that file in my html document in which I have loaded the cytoscape.js script. However, the .cyjs file is very large and I want to import it somehow instead of copy-paste it. I have looked for questions in this same forum and the ones that deal with this issue have not been answered. Also the documentation and the examples I have seen haven't helped me.

Thank you all in advance and sorry to bother you,

Rocio.
Versions: cytoscape.js 2.7.14 and cytoscape 3.4.0

**Comment by maxkfranz** [comment]
@keiono Kei, this is a ongoing --- and often brought up --- issue with your plugin for Cy3.  The following changes should be made in order for your plugin to properly support Cyjs:

(1) The file you are exporting is JSON.  Use ` .json` suffix for the exported file.  It's confusing, especially to novices.  And you break the browser's ability to determine the proper file type by using an unclear suffix.

(2) The JSON file exported from Cy3 should contain *only* the JSON expected by Cyjs.  The JSON file should conform exactly to [the standard JSON format explained in the docs](http://js.cytoscape.org/#notation/elements-json) --- no more, no less, and no embedding of the proper JSON as a subdocument of the exported JSON file.

A complete example, including HTTP request, is as follows:

```js
let cy;

// just a standard http get request
fetch('./dir/to/my/exported-graph.json')
  .then( response => response.json() )
  .then( exportedJson => {
    cy = cytoscape( exportedJson ); // and use the json verbatim
  } )
;
```

If a dev can't do a simple `cy = cytoscape( exportedJson );` after doing an HTTP request to get the JSON file, then the export plugin isn't working as devs/users would expect.  If a user needs to do any transformation of the JSON file whatsoever, then I consider the plugin to be broken.  

It should be as simple as using `fetch()` or `jQuery.ajax()` to load the file --- no user instruction needed as instructions on making HTTP requests are already well documented by places like [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) and [jQuery](http://api.jquery.com/jQuery.ajax/), and tutorials for those APIs are numerous.

(3) The JSON file should not contain any extra fields or custom fields outside of element `data` or `scratch`.  If you have other extra data you want to export, perhaps associated with a Cy3 session, then use a different plugin or use a different feature to expose that data.  Cyjs has no --- and should have no --- concept of session, so that data is extraneous for exporting a single graph.

Would you please provide a code snippet for @Rociocc93 so he can transform the exported data from the plugin into the proper format?
