### ISSUE TITLE
Add ability to hide labels in png/jpeg export

### ISSUE THREAD

**Issue by jspautsch** [cytoscape/cytoscape.js#1730]
It would be useful for our users if the png/jpeg export functions had an option to hide labels from the exported image. An added benefit is this could be utilized by the cytoscape-navigator plugin to render the navigator image sans-labels (unless someone knows of of a way we could accomplish that today?), which tend to clutter the graph thumbnail.

**Comment by maxkfranz** [comment]
It wouldn't be much of a benefit for extensions like that, because it would double the rendering cost.  It might also make all the rendering caches dirty, dropping general performance as well.

Whatever stylesheet you have applied affects the export, so you can modify the style before export to get the effect you've described.

**Comment by jspautsch** [comment]
Gotchya, sounds reasonable.

**Comment by maxkfranz** [comment]
You can alternatively use a second instance for exporting.  Just grab the `eles.jsons()` from the main instance.  That way, it's completely isolated and you can use whatever styling you like,
