### ISSUE TITLE
Uncaught SyntaxError: Illegal break statement (WebPack2.2 UglifyjsWebpackPlugin)

### ISSUE THREAD

**Issue by smailsky** [cytoscape/cytoscape.js#1739]
webpack2.2.1:
new webpack.optimize.UglifyJsPlugin({
          beautify: false,
          mangle: {
            screw_ie8: true,
            keep_fnames: true
          },
          compress: {
            screw_ie8: true,
            warnings: false,
            drop_console: true,
            drop_debugger: true,
            dead_code: true
          },
          comments: false
        })

code:
import cytoscape from 'cytoscape';

error:
**Uncaught SyntaxError: Illegal break statement**

UglifyJs removed
> findClippingPoint function 
`while( false)`

**Comment by benjaminlees** [comment]
+1

**Comment by maxkfranz** [comment]
If Uglify can't handle that block, that's technically a bug in Uglify.  You can't assume a `do ... while` loop is dead code even if `while( false )`, because there's always the first iteration.

I checked the code.  It's valid, albeit unconventional.  I'll gladly revise the layout, but you ought to file a bug with Uglify as well.

For now, you'll have to set `dead_code: false`.

**Comment by smailsky** [comment]
@maxkfranz 
dead_code: false, no errors
but
display nothing

cytoscape(2.7.15)

modfiy code:
```
var flag = false;
do{
...
flag = false;
} while( flag);
```

**Comment by maxkfranz** [comment]
Try the snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-09af5035ff-1488570335428.zip

Or if you're using npm+browserify or npm+webpack, temporarily replace `"cytoscape": "x.y.z"` in `package.json` with `"cytoscape": "https://github.com/cytoscape/cytoscape.js.git"` to use the latest code from `master`.

Let me know if it works for you or if you have any issues with it.  

Thanks

**Comment by smailsky** [comment]
@maxkfranz it's ok!
