### ISSUE TITLE
Position event is not triggered for parent nodes when their children change position through draging or animating

### ISSUE THREAD

**Issue by metincansiper** [cytoscape/cytoscape.js#1754]
Hi,
Please would you see the following fiddle? http://jsbin.com/sujeyinomi/1/edit?js,console,output

In that fiddle we listen the 'position' event for parent nodes and print something in console when that event is called.

My observations are the followings,
If we reposition a node programatically by using 'position' or 'positions' function, then that event is triggered for its parent and something is written to the console.

If we reposition a node by dragging it then that event is not triggered for its parent.

If we reposition a node animatedly (e.g. by running "cy.nodes('#a').animation({position: {x: 5, y:5}}).play()" command in console) then that event is nor triggered for its parent.

Note that all node repositions I mentioned above changes the position of the parent as well.

I wonder is this a bug or is there a special reason behind it.

Thanks,
Metin

**Comment by ugurdogrusoz** [comment]
This is how we see the problem in newt:
![position-problem](https://cloud.githubusercontent.com/assets/3874988/24235554/8a7ffad4-0fa6-11e7-9130-f7b6a8d32067.gif)

**Comment by maxkfranz** [comment]
Part of the problem is your use of a delegate selector.  A delegate selector matches an element only if the target of the event matches the selector.  It does not match bubbled events, like from child up to parent.

A compound parent doesn't get extra `position` events for `updateCompoundBounds()`, probably because it would get one from its child anyway and so the event would be mostly redundant.

See this revised demo: http://jsbin.com/sewizokeli/edit?js,console,output

I guess `updateCompoundBounds()` could be emitted extra position events based on a diff every time.  But then you'll have to handle multiple events in quick succession sometimes.  Maybe that would make sense to do anyway, since the position could change from a non-`position` (e.g. `style`) event on the children.  Either way, you need to revise your approach.

**Comment by maxkfranz** [comment]
There's also internal `bounds` events that are emitted whenever compound bounds are altered.  Perhaps that could be made public and documented.

**Comment by metincansiper** [comment]
As far as I understand if ```updateCompoundBounds()``` emit extra position event we do not need to listen to any event other than ```position``` but in the other way we need to listen to ```bounds``` event. Is it true?

**Comment by maxkfranz** [comment]
If there are extra position events, you need to change your example code to ignore some position events.

If not, then you need to change your example code to also listen to bounds.
