### ISSUE TITLE
Applying css transforms to the container (or an ancestor)

### ISSUE THREAD

**Issue by davidsundell** [cytoscape/cytoscape.js#1756]
Hi, I discovered a bug in the canvas that causes a scaling error when using moz-transform. A suggested solution can be found below, however I found that it does not render correctly when not resizing the window.

The canvas will, first of all, upon rendering get two size settings for size (see example below); width/height and the style width/height. Not only is this unnessesary it also creates a problem when rescaling the tool using moz-transform.

The canvas will as it is now, rescale using the same setting in the moz-transform as the container-div, this results in the canvas being visually only a quarter of the div size (if rescale factor is 0.5). In addition the action area is not scaled, so to click a node I need to find its location where it would have been if the visual canvas was not scaled.

example:
original container div width: 400px
moz-transform 0.5 that will rescale the div container to 200px.
The canvas will automatically again rescale its visual window with factor 0.5 and have width/height = 100px and therefore only fill a quarter of the container div.

example html code:
The canvas layers will look like the one below with the same "error" for each individual canvas layer.
<canvas sublayer0 height=100px width =100px style:'width="200px" height ="200px'>
<canvas sublayer1 height=100px width =100px style:'width="200px" height ="200px'>

Where seeminly the visual representation takes the first setting and the action layer takes the second setting.

Resolution:

The resolution for this bug is to remove the canvas.style.width = width + 'px'; settings for the CANVAS_LAYERS as well as change the canvasContainer.style.width to use the canvasWidth/canvasHeight variable (the width and heigh variables are wrong when using moz-transform)  

I suppose the canvasContainer also can use the standard div height and width to be consistent.

Code example.
matchCanvasSize function line 18186 ---> 

var canvasContainer = data.canvasContainer;
  canvasContainer.style.width = canvasWidth + 'px';      // ( canvasWidth replaced the width variable)
  canvasContainer.style.height = canvasHeight + 'px';   // ( canvasHeight replaced the height variable)

  for( var i = 0; i < r.CANVAS_LAYERS; i++ ){

    canvas = data.canvases[ i ];

    if( canvas.width !== canvasWidth || canvas.height !== canvasHeight ){

      canvas.width = canvasWidth;  
      canvas.height = canvasHeight;

      //canvas.style.width = width + 'px'; commented these lines
      //canvas.style.height = height + 'px'; commented these lines
    }
  }

  for( var i = 0; i < r.BUFFER_COUNT; i++ ){

    canvas = data.bufferCanvases[ i ];

    if( canvas.width !== canvasWidth || canvas.height !== canvasHeight ){

      canvas.width = canvasWidth;
      canvas.height = canvasHeight;

      //canvas.style.width = width + 'px';  commented these lines
      //canvas.style.height = height + 'px'; commented these lines
    }
  }

<---

**Comment by maxkfranz** [comment]
I appreciate your detailed post.  However, some of your assumptions are false.

The different specifications of dimensions are indeed necessary for supporting high density displays.  `1px` in CSS does not mean one pixel.  It means one css-pixel.  They happen to be 1:1 for old displays (96ppi).  

You're using a prefixed (i.e. unfinished / experimental) CSS property (`-moz-transform`) on a canvas which has its own built-in transform capability.  That's probably not going to work.  It might not even be intended to work based on the CSS spec and the browser vendor.  You'd have read the spec and/or contact Mozilla to find out.

If you're trying to do some kind of responsive CSS, you should be using relative units like `em` and changing the font size of some parent element like `body` with media selectors.

See 

- https://en.wikipedia.org/wiki/Pixel_density
- https://developer.mozilla.org/en-US/docs/Web/CSS/transform
- http://stackoverflow.com/questions/27382331/how-a-css-pixel-size-is-calculated

**Comment by dwitvliet** [comment]
We are having the same problem. We are using 2D CSS transforms ([currently supported by all main browsers](http://caniuse.com/#search=transforms)) to scale the Cytoscape container down when not in focus, which scales down everything drawn by Cytoscape. It works well until resizing the window, which causes `cy.resize()` to be triggered, downsizing the canvas even further as @davidsundell describes it. 

Shouldn't it be easy for Cytoscape to account scaling of its container, when setting the canvas height and width with `cy.resize()`?

**Comment by dwitvliet** [comment]
It might be possible to use `offsetWidth` and `offsetHeight`, which gives the unscaled sizes of an element (e.g. see [jsfiddle example](https://jsfiddle.net/8dpk2wtk/2/)).

**Comment by maxkfranz** [comment]
> It might be possible to use `offsetWidth` and `offsetHeight`, which gives the unscaled sizes of an element (e.g. see [jsfiddle example](https://jsfiddle.net/8dpk2wtk/2/)). 

Unfortunately, that's not a standard property (yet anyway), and it looks like several browsers don't support it: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetWidth

The spec says this function would ignore transforms, so I'm not sure how useful it would be: https://drafts.csswg.org/cssom-view/#dom-htmlelement-offsetwidth

We're using `getBoundingClientRect()`, which is well supported for width/height: https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect

While generally we'd like to support as many usecases out of the box as possible, playing with viewport css generally isn't something that a visualisation library allows you to do.

It's not as simple as `width = scaleTransformX * domEleWidth`.  You'd want to use `domEleWidth` for cases where you'd want to scale up --- otherwise you'd get unexpected pixelation.  It's not as simple as handling a scale, either.  That may be enough for your usecase, but other devs would want other property support, like padding or rotation.  That would greatly increase the complexity of the renderer and it would introduce a lot of potential for bugs.  We'd also be continuously chasing after the latest css spec, having to add support for each new property.

Cytoscape already has built-in functionality for scaling the viewport:  Just change the zoom level.  If you want a smaller viewport extent as well, then you can change the width/height on the container.

**Comment by dwitvliet** [comment]
> Unfortunately, that's not a standard property (yet anyway), and it looks like several browsers don't support it

I tried both `offsetWidth` and `offsetHeight` in the most recent versions of GC, FF, IE, Safari, Opera. All of them seem to work, but slightly older versions might not.

> The spec says this function would ignore transforms

I think that's point; you'll get the width and height before any transforms are applied, which means it would work for all 2D transforms, not just scaling.

> Cytoscape already has built-in functionality for scaling the viewport: Just change the zoom level. If you want a smaller viewport extent as well, then you can change the width/height on the container.

The problem for us is that we want to animate the transition. When doing multiple independent animations on the same elements at the same time (cytoscape zoom and container size), the resulting animation is laggy and almost impossible to ease. Additionally, the container has to be re-positioned if the origin isn't top-left. All of this can be done perfectly in one css scale animation. That's what we were doing in Cytoscape.js v2, but it does not work in v3 because of the resizing issue. It's preventing us from updating to the newest version.

**Comment by maxkfranz** [comment]
@dwitvliet  

> I tried both offsetWidth and offsetHeight in the most recent versions of GC, FF, IE, Safari, Opera. All of them seem to work, but slightly older versions might not.

That could be problematic.  The lib supports pretty old browsers (basic subset of ES5 and canvas).  That's something like Firefox 4, IE9, etc.  A lot of people care about that feature, so it would be a shame to lose it.

> I think that's point; you'll get the width and height before any transforms are applied, which means it would work for all 2D transforms, not just scaling.

OK, I think I see what you mean.  We'd need both the effective size and the scaled size, and the renderer would have to take into account the scaled size in the co-ordinate projections for gesture/event support.

> The problem for us is that we want to animate the transition. When doing multiple independent animations on the same elements at the same time (cytoscape zoom and container size), the resulting animation is laggy and almost impossible to ease. Additionally, the container has to be re-positioned if the origin isn't top-left. All of this can be done perfectly in one css scale animation. That's what we were doing in Cytoscape.js v2, but it does not work in v3 because of the resizing issue. It's preventing us from updating to the newest version.

I suppose if you animate the viz and the dom element at the same time, you'll be invalidating the animation texture and potentially invalidating the document flow.  Either could kill the performance.

Maybe the approach I mentioned could work using only `getBoundingClientRect()` and `clientWidth/clientHeight`.  That wouldn't break compatibility, but even if it works it would be a risky change.  Anything that changes the projection/co-ords calculations in the renderer can potentially cause a lot of bugs.  So if this is possible, the change would probably have to go in the unstable branch for the next version (3.2).  It wouldn't be good for people who `npm install` the latest patch release to potentially get some weird projection bugs.

I'll play around with this and get back to you Tuesday or Wednesday.

**Comment by dwitvliet** [comment]
Awesome, thanks for being so supportive! We'll happily test out any changes in an unstable branch!

**Comment by maxkfranz** [comment]
@dwitvliet 947b487 should do it, I think.  I tested it yesterday a bit, and it seemed OK.

**Comment by dwitvliet** [comment]
Thank you for implementing this! We tried it, and as far as we can tell, it works perfectly with our transforms!

**Comment by maxkfranz** [comment]
@dwitvliet Good to hear.  I'll add this to the 3.2 milestone.  If there are issues with it, let me know here.

Some notes:

It should only correct itself *after* an animation is complete; it's too expensive to do each frame.  If you try to interact during the animation, it won't work.  For most cases, this is probably fine.

It only works on the container and its ancestors in the dom --- again, for performance reasons.  So if you animate some other element that somehow changes the container (maybe shifts it), then it won't work either.
