### ISSUE TITLE
Image 404 with background-image and background-image-fit breaks graph

### ISSUE THREAD

**Issue by tumri** [cytoscape/cytoscape.js#1814]
I am currently working with a large data set(few thousand nodes and edges).

I am initializing cytoscape as follows:

```
var cy = cytoscape({
                    container: document.getElementById('cy'), // container to render in
                    elements: getPos(),
                    style: cytoscape.stylesheet()
                                        .selector('node')
                                            .css({
                                                'height': 200,
                                                'width': 200,
                                                'background-image': 'data(node_image)',
                                                'background-fit': 'cover',
                                                'border-color': '#000',
                                                'border-width': 3,
                                                'border-opacity': 0.5
                                            }),
                    minZoom: 0.01,
                    maxZoom: 10.0,
                });
```

When any of the thousands of node images returns a 404 error the entire graph layout breaks and I get the following error:

`Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state.`

I was able to fix the error by making the following change:

```
CRp.safeDrawImage = function( context, img, ix, iy, iw, ih, x, y, w, h ){
  var r = this;

  // detect problematic cases for old browsers with bad images (cheaper than try-catch)
  if( iw <= 0 || ih <= 0 || w <= 0 || h <= 0){
    return;
  }

  context.drawImage( img, ix, iy, iw, ih, x, y, w, h );
};
```

to

```
CRp.safeDrawImage = function( context, img, ix, iy, iw, ih, x, y, w, h ){
  var r = this;

  // detect problematic cases for old browsers with bad images (cheaper than try-catch)
  if( iw <= 0 || ih <= 0 || w <= 0 || h <= 0 || !img.width || !img.height){
    return;
  }

  context.drawImage( img, ix, iy, iw, ih, x, y, w, h );
};
```

**Comment by maxkfranz** [comment]
Some images won't have dimensions defined (like some svgs) but they can be used if an explicit background width and height are set.  I'm not sure whether the change you posted could be used as it stands if it causes issues with existing usecases.

Maybe it would be better to handle the 404 at the load event itself.

**Comment by tumri** [comment]
@maxkfranz - I modified my PR #1815 to check if image exists and if image height and width are both === 0 in drawing_nodes.js where you have the check for image[i].complete.


`this.drawInscribedImage( context, image[i], node, i );`

to

```
if (!image[i] || (image[i].height === 0 && image[i].width === 0)) {
  console.log('Image Error');
} else {
  this.drawInscribedImage( context, image[i], node, i );
}
```
I had also tried using the onload callback by doing

image[i].onload = this.drawInscribedImage( context, image[i], node, i );

and a few other attempts at fixes but couldn't get anything else to work.

If you meant something else when you mentioned handling the error at the load event then I would appreciate if you could point me in the right direction(I am a bit inexperienced) and I will update the PR with a more agreeable fix.

**Comment by maxkfranz** [comment]
If there's a 404 it should be picked up around the same code that listens to `load`: https://github.com/cytoscape/cytoscape.js/blob/master/src/extensions/renderer/base/images.js

I suspect a 404 would give an `error` event instead of `load`.

**Comment by tumri** [comment]
Hey @maxkfranz.
I updated the PR and was able to get the following onError event to fix the issue.

`var onError = function(){ this.width = this.height = 0; }`

`cache.image.addEventListener('error', onError);`

I am setting width/height to 0 manually since the rest of the code seems to check for those values being set to zero as a signal to ignore the image but can change it if you would like.

**Comment by maxkfranz** [comment]
I suspect we may have to mark the cache/image object with a particular error flag to keep the checks precise.  I think the issue with your change is that you're referencing `this` in your handler.  You can't do that unless the function is bound to the image/cache object or you use a separate named reference.

**Comment by maxkfranz** [comment]
It would be great if you wanted to add your app to the list: https://github.com/cytoscape/cytoscape.js/issues/914

**Comment by tumri** [comment]
Hey I added the app to the list. Also changed the onError event to not use "this" so it fixes the issue without any problems.

**Comment by swtyler** [comment]
@tumri & @maxkfranz I am seeing this fail fairly often in 3.1.4.

By the time `image.error` is set, it's too late because `drawNode` has been called a second time via `requestAnimationFrame->render`. `safeDrawImage` then uses the cached image, which does not have error set. This breaks the graph and a full refresh is necessary.

I struggled to come up with a jsbin version but I have consistently made it happen with a node that has a bad url like http://www.oldurlthatisgone.com/image.png

**Comment by maxkfranz** [comment]
@swtyler I'm not seeing anything incorrect happening.  It doesn't matter when `.error` is set.  A frame is requested when a node's image is properly loaded and only completed images are drawn.  Adding a hack to check `naturalWidth` won't improve anything; we're already using the WC3 standard `load` and `error` events.

You are probably just having trouble with Chrome's overzealous caching or having general network issues.  Disable the cache when you're debugging.  If you load lots of images from lots of hosts, you're asking for a slowdown -- because you're making many simultaneous HTTP requests.  If you care about performance with lots of images, you should be using Webpack to bundle your images as base-64 data URIs.

If you can create a demo that consistency shows incorrect behaviour, then please create a new ticket.

**Comment by swtyler** [comment]
@maxkfranz Thanks for the response. It was a combination of both Chrome caching and network issues. I was able to find a workaround by including another `error` check on icons in our code.

Not a cytoscape issue - cheers!

**Comment by rzec-r7** [comment]
@maxkfranz I am seeing a similar issue to this in `3.2.15`.

If I have an image that fails to load because of a CORS error, 5% - 10% of the time I will get the same error of the OP but the other 90% - 95% of the time I will get the CORS error in the console but cytoscape does not bomb out (the graph still renders just without the images as expected).

Not exactly sure why it is inconsistent or what I could do to make sure if the image fails to load for whatever reason, the graph does not bomb out but instead always renders, just without those images that failed to load.

**Comment by tumri** [comment]
I noticed this issue pop up again sometime last year and had to revert to using the original fix I had (see OP) since that seemed to work better despite potentially causing issues with other functionality that I wasn't using. If you're having problems you may want to try that.

**Comment by giudicelli** [comment]
Hello,
I'm using version 3.2.22, I have the same problem, source image is returning a 404, and yet I do have values for iw and ih in CRp.safeDrawImage. Maybe the easiest solution would be to surround context.drawImage with a try cactch ?
