### ISSUE TITLE
kd-tree or pr-quadtree for BRp.findNearestElements (coord-ele-math/coords.js)

### ISSUE THREAD

**Issue by jamelt** [cytoscape/cytoscape.js#1816]
Hello, I was reviewing the code and I noticed that this function gets called for all mouse movement to detect events.

[BRp.findNearestElements](https://github.com/cytoscape/cytoscape.js/blob/26fbcca9197d9ce3258084a258e5b823b3c5dcda/src/extensions/renderer/base/coord-ele-math/coords.js#L58)

Although it's probably a non-issue with very small graphs. I was wondering if you thought that maybe using a kd-tree or pr-quadtree instead of [getCachedZSortedEles()](https://github.com/cytoscape/cytoscape.js/blob/26fbcca9197d9ce3258084a258e5b823b3c5dcda/src/extensions/renderer/base/coord-ele-math/z-ordering.js#L45) would boost performance? It may reduce CPU load by minimizing the number of comparisons needed to find the nearest elements.

As the number of nodes and edges increases, it could probably significantly cut down the number of comparisons.

Let me know, I may be interested in implementing this performance enhancement.

**Comment by maxkfranz** [comment]
Hi.  It could definitely be useful in some cases.  I had considered it for the hit tests, but the issue is the additional cost of building the tree.  The z-sorted elements are used in several places already and generating that list is cheap.  But you're right about the additional comparisons.

The problem with using a tree (like a quadtree) is that it would have to either be built for every hit test call or it would have to be cached and updated every time a node is moved.  Maybe the first case would be efficient but I suspect the second would be too expensive with all the invalidations.

I suppose the main problem would be overlap, moreso with edges than nodes.  That would make the leaves of the tree contain several elements, so the tree potentially becomes O( n*log4(n) ) rather than O( log4(n) ).  

In the worst case, it would devolve to almost O( n ) -- e.g. edges in a circle layout.  In cases like that, using a quadtree adds more expense than using the pre-existing O( n ) list.

Even if it doesn't work out for the hit tests, I think there are some other places that could use a quadtree.  It would make sense to identify those places in the code, though.  I don't remember them offhand.

**Comment by jamelt** [comment]
It did some more research and I'm going to investigate integrating a simple r-tree. Maybe use that as a benchmark and see what results are produced.

**Comment by maxkfranz** [comment]
Great!  I'm interested to see what results the benchmarks show.  Hopefully we can get an improvement.  Thanks
