### ISSUE TITLE
Unstable branch does not work in my simple commonjs test application

### ISSUE THREAD

**Issue by metincansiper** [cytoscape/cytoscape.js#1838]
I created a simple commonjs application to experiment something in Cytoscape.js. I managed to do it with cytoscape.js master branch but when I tried to do the same thing with unstable branch I get the attached error.

![capture](https://cloud.githubusercontent.com/assets/6534865/26400098/124106a4-4088-11e7-94d2-c50879618a08.PNG)

The github url of my app is "https://github.com/metincansiper/cytoscape-test". I do not know if it is a known or expected thing in unstable branch but I wanted to report it.

**Comment by maxkfranz** [comment]
You can either use an official npm release or `require('cytoscape/src')` and run babel on the source (include `node_modules/cytoscape/**`) yourself.

The `main` field can't point to the source anymore if the project uses Babel and `dist` gets updated only on a release.

**Comment by metincansiper** [comment]
Currently I am not using unstable branch I just realized it and filed this issue. If you see no problem you can close the issue.

**Comment by maxkfranz** [comment]
The problem is that currently the only practical way of allowing for `cytoscape: 'https://github.com/cytoscape/cytoscape.js.git#unstable'` is building the `dist` files adding them to each commit.  That would add too much noise to the git commit history.

Right now, Cytoscape.js is using CJS `require()` instead of `import` because Node doesn't support `import` yet.  It makes running tests much slower if you have to build each time before testing.  Right now you can test the source directly with Mocha on node>=6.  That's a big productivity gain.  It's also nice because it decouples the build process from testing:  You can run the tests on a built version or on the raw source files.  That can help to isolate problems with the build system.

Once Node supports `import`, we can use [`module`](https://github.com/rollup/rollup/wiki/pkg.module) in `package.json` for the raw source code.  But you'd still have to run Babel on it.

It's probably best in general to only use official releases on npm.  If you really need a snapshot version you can do this:

Add a directory in your app called `cytoscape`.  In it, put `package.json`:

```js
{
  "name": "cytoscape",
  "version": "0.0.0-snapshot",
  "main": "cytoscape.js"
}
```

Then inside the `cytoscape` dir, copy your built snapshot of `cytoscape.js`.  So you have:

```
- cytoscape
  - cytoscape/package.json
  - cytoscape/cytoscape.js
```

In your app's `package.json`, replace `cytoscape: 'x.y.z'` with `cytoscape: 'cytoscape/cytoscape.js'`.

**Comment by maxkfranz** [comment]
Here's a useful article on the topic: http://2ality.com/2017/04/setting-up-multi-platform-packages.html

Basically only the `es2015` field could work with untranspiled source.  `module` would work today with webpack and browserify, but would still require a babel build.

**Comment by maxkfranz** [comment]
Also of interest : https://github.com/standard-things/esm
