### ISSUE TITLE
Add Collection Support to cy.png() & cy.jpg()

### ISSUE THREAD

**Issue by Insulince** [cytoscape/cytoscape.js#1853]
Recently I started using the [navigator extension](https://github.com/cytoscape/cytoscape.js-navigator) to supplement my cytoscape environment, and it is fantastic, however, I find that I often want the navigator to ignore some nodes and zoom on a specific subset or collection of nodes. I decided to do my own investigation into how to accomplish this and found that the culprit which stands in the way of doing this ends up boiling down to the fact that cy.png() supports capturing either the entire graph or your current viewport. So I decided to dig into the core of this function as well and found that the way cy.png() works on full mode is by getting the bounding box of all of the elements in the graph and proceeding with the png operations from there. So I posit that exposing some additional option to pass into cy.png() (perhaps a selector, collection, or array of elements) would define a third mode in which cy.png() captures the bounding box of that argument and creates the png out of that. I do already know it's possible, using cytoscape@3.1.1 (via npm), exploring to
`cytoscape > src > extensions > renderer > canvas > export-iamge.js > line ~15`:
```javascript
CRp.bufferCanvasImage = function( options ){
  var cy = this.cy;
  var eles = cy.mutableElements();
  var bb = eles.boundingBox();
  var ctrRect = this.findContainerClientCoords();
```
Changing the bb line to this:
`  var bb = cy.$('.someClass').boundingBox();`
Seemed to make it work.

Simply allowing a user to pass in '.someClass' from the cy.png() or cy.jpg() command would make this very handy.

**Comment by maxkfranz** [comment]
That's enough for a correct solution.  If you look farther down, you need the z-sorted elements.  You change is still drawing the excluded elements.

It would require more changes to work properly and the API should be `eles.png()` if it's operating on a subset of the graph.  That also means that some options won't make sense anymore, so that would have to be addressed as well.

If you're interested in a feature like this, feel free to make a PR and it will be reviewed by me or someone in the group.
