### ISSUE TITLE
Performance of ele.width() and ele.boundingBox() operations for compound nodes

### ISSUE THREAD

**Issue by metincansiper** [cytoscape/cytoscape.js#1860]
How is the performance of ele.boundingBox() as compare to ele.width() for a compound node? And what are the time complexity of both operations? Do they linear to the number of its children or descendents?

Thanks

**Comment by metincansiper** [comment]
Sorry, I need to update my question. What I need is not ele.boundingBox(). I need ele.children().boundingBox(). Therefore, my updated question is:
How is the performance of ele.children().boundingBox() as compare to ele.width() for a compound node?

**Comment by maxkfranz** [comment]
`boundingBox()` is an expensive operation.  It needs to read a lot of style values, and it potentially has to (re)calculate some rendered values (text dimensions, control points, etc.).

`ele.boundingBox()` is cached for this reason, per element.  `eles.boundingBox()` may use the cached `ele.boundingBox()`, but it still needs to do several comparisons and create a new object for the overall box. The cache is easily dirtied (position, style, etc.), though.  If the graph is static between calls, `.boundingBox()` will be cheap.  Generally, you should avoid calling `boundingBox()` unless it's absolutely necessary.

`.width()` is much cheaper, because it only takes into account the inner width.  That's just one or two style properties.  I think it's also cached, but I'm not sure in what version (maybe 3.2/unstable).  `.outerWidth()` is also relatively cheap but not so much as `.width()`.

**Comment by metincansiper** [comment]
@maxkfranz Thanks for the detailed answer. In the latest versions of Cytoscape.js there is a ```min-width``` property for compound nodes. As expected this property affects the result of ```.width()``` call on a compound. However, sometimes I need to get the value which would be the with of a compound if the ```min-width``` of it was not set (I suppose that this value is equal to the result of ```ele.children().boundingBox()``` and thats why I asked the question). Is there a proper way of getting this value?

**Comment by metincansiper** [comment]
Actually, I gave importance to the performance of this operation because I supposed that I need to get that value (the one I explained in the previous comment) while the user is interactively moving the mouse cursor (on a grapple provided to resize the node). However, now I realized that I do not need to get it consistently on user interaction. Getting it once on mouse down seems to be enough for me (In my case this value will not change while the user is moving the mouse cursor). Therefore, I suppose that even if I use ```ele.children().boundingbox()``` it is not a big deal. However, it may be still good to know if there is a better way to get that value.

**Comment by maxkfranz** [comment]
It depends on your stylesheet whether `.width()` is enough versus `.bb()`.

But why do you need to get the bb at all?  The parent can't be sized smaller than the min even if you specify a smaller value, so that constraint should be automatic.  And you need to query parent w/h every time it's resized to redraw the grapple anyway -- which is inexpensive compared to child bb.

**Comment by metincansiper** [comment]
I do not need child bb to draw the grapples. I need it to determine new values of ```min-width-bias-left``` and ```min-width-bias-right``` while a compound node is resized. For example, if the node is resized through the center right grapple these values are calculated so that the extra width put on the left side of the node should not be changed (I need the children bbox to calculate extra spaces around the compound). I am able to resize compounds with this logic.

And as I wrote previously getting children bbox only on mouse down on a grapple is enough for me. Therefore, I think that even if getting children bbox is expensive it seems not to be a big deal.

**Comment by maxkfranz** [comment]
OK, that makes sense.  Let me know if you run into any issues.  Closing for now
