### ISSUE TITLE
Crossline on 'triangle-cross' arrow heads disappears

### ISSUE THREAD

**Issue by kinimesi** [cytoscape/cytoscape.js#1921]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.1.4 (exists in unstable branch too)

**Current (buggy) behaviour**

When `arrow-scale` attribute of `triangle-cross` shaped arrows decreases, the distance between crossline and triangle decreases too. After a points, the crossline merges into triangle head and disappears. The shape is no longer `triangle-cross`, it looks like `triangle`.

**Desired behaviour**

The distange between crossline and triangle should not disappear.

**Minimum steps to reproduce**
Demo: [https://jsbin.com/beyahihato/1/edit?js,output](https://jsbin.com/beyahihato/1/edit?js,output)

**Comment by d2fong** [comment]
Okay thanks for reporting this, I will look into it.

**Comment by d2fong** [comment]
### Initial steps to fix (For those who care)

1.  Read triangle arrow cross scaling code
https://github.com/cytoscape/cytoscape.js/blob/unstable/src/extensions/renderer/base/arrow-shapes.js#L211
https://github.com/cytoscape/cytoscape.js/blob/master/src/extensions/renderer/base/arrow-shapes.js#L217
https://github.com/cytoscape/cytoscape.js/blob/master/src/extensions/renderer/base/arrow-shapes.js#L221

2. Alter the scaling function so that it scales properly for values < 1


#### Why this bug exists

I didn't realize that the arrow scale property could be < 1

**Comment by maxkfranz** [comment]
@d2fong Is it possible to make the cross line a constant distance away?  If it's not scaled, then it shouldn't be an issue for small values.

**Comment by d2fong** [comment]
Do you mean check if arrow-scale < 1 and if it is just return some constant distance value?

**Comment by maxkfranz** [comment]
I mean whether we could use a constant distance always.  The arrows are specified in relative units anyway.

**Comment by maxkfranz** [comment]
Whoops, wrong button...

**Comment by d2fong** [comment]
Yeah that makes sense to always keep a constant distance between the arrow head and the crossline.

**Comment by maxkfranz** [comment]
@d2fong Could you take a look at this for 3.2.2?  I have a couple of other renderer bugs I need to look at.

**Comment by d2fong** [comment]
Ok

**Comment by d2fong** [comment]
## New Implementation Notes

- base the implementation off triangle tee
- make crossline points an array of four points instead of two to form a rectangle
- get rid of forceStroke, match edgewidth
- calculate bottom two rectangle points such that the distance between the top and bottom rectangle points equals edgewidth

**Comment by maxkfranz** [comment]
@d2fong Should we defer this to 3.2.3?  I need to release 3.2.2 this week.

**Comment by d2fong** [comment]
Hi Max, yes we should. It won't be ready for a 3.2.2 release.

Thanks,
Dylan

**Comment by maxkfranz** [comment]
OK, no worries.   Thanks for letting me know
