### ISSUE TITLE
Error on large resolutions for cy.png()

### ISSUE THREAD

**Issue by KonradHoeffner** [cytoscape/cytoscape.js#1943]
WIth large resolutions I get the following error when I use `cy.png()`:

```
NS_ERROR_FAILURE:   cytoscape.min.js:42
	[82]</s.bufferCanvasImage file:///localstorage/projekte/snik/cytoscape/lib/cytoscape.min.js:42:28442
	[82]</s.png file:///localstorage/projekte/snik/cytoscape/lib/cytoscape.min.js:42:28674
	png file:///localstorage/projekte/snik/cytoscape/lib/cytoscape.min.js:32:2191
```

The code:

```
const options =
  {
    "bg": "black",
    "full": false,
    "maxWidth": 15000,
    "maxHeight": 11250,
  };
  const image = cy.png(options);
```

**Comment by maxkfranz** [comment]
Each browser has limits to the size of files that it can export.  It varies by OS/browser and it's not documented by the browser vendors.  Your best bet if you want high-res exports is to use JPG with a relatively low compression option value.

**Comment by KonradHoeffner** [comment]
Thanks for the information! I had no idea about undocumented file size limits. I will stay with PNG though, as the file sizes are very close for my graph. I think due to the way the lossless PNG compression works, it is much better suited for cytoscape graphs. This could be different with textured backgrounds or color gradients though. JPG on the other hand is very badly suited for high-frequency images with lots of text and the fine edges between nodes.

**Comment by maxkfranz** [comment]
See

- https://stackoverflow.com/questions/695151/data-protocol-url-size-limitations
- https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob

Data URIs are the only reliable cross-browser way to initially export the image from the canvas.  It looks like `toBlob()` support is a bit better over the past months.  We could potentially do a feature detect for `cy.png({ output: 'blob' })`: Use `canvas.toBlob()` if available, otherwise use the current data URI to blob conversion.
