### ISSUE TITLE
Event handlers that remove themselves can cause others to be skipped.

### ISSUE THREAD

**Issue by somedmguy** [cytoscape/cytoscape.js#1953]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : Found in 2.7.15.  Reproduced in 3.2.1
- Browser/Node.js & version : chrome, firefox, ie11

**Current (buggy) behaviour**

Emitter iterates over the actual array of event handlers, but the array can be modified without its knowledge during the operation (see promiseOn() and collection.beforeEmit() for examples).  This causes the next handler to be skipped.

**Desired behaviour**

No event handlers get skipped.

**Minimum steps to reproduce**

```js
let layout = cy.makeLayout(...);
layout.pon('layoutstart').then(function() { console.log("runs"); });
layout.pon('layoutstart').then(function() { console.log("skipped"); });
layout.run();
```

**Comment by maxkfranz** [comment]
@somedmguy My initial thought was to just always copy the listener list on `removeListener()`.  That works.  It turns out to be the same approach taken by eventemitter3.  But I think it's only necessary if you call `removeListener()` while you `emit()`.  Copying isn't good for performance, so I'm only copying if you remove a listener while you emit.  That passes all the tests I added and the case you posted.

Please try the latest source on master and let me know whether it works for you in your app.

**Comment by maxkfranz** [comment]
@somedmguy If this change works for you on 3.x, then I'll look into backporting it to 2.x.

**Comment by somedmguy** [comment]
That's a clever optimization, but here's a unit test that fails it.

```js
    it('removed one event stays removed', function( next ){
      var n = cy.nodes().first();
      var count = 0;
      var inc = function(){ ++count; };

      n.pon('foo').then( inc );
      n.one('foo', inc );

      n.trigger('foo');

      setTimeout(function(){
        expect( count ).to.equal(2);
        next();
      }, 50);

      n.trigger('foo');
      expect( count ).to.equal(2);
    });
```

Then there's the question of a handler that adds another handler.  e.g.

```js
      n.one('foo', () => { 
        inc();
        n.one('foo', inc );
      });
```
Should the added handler be executed in the same pass?  I wouldn't expect it to, but it would under the old code, and it may or may not (if another handler removed itself) under the new code.

Also, is there a reason promiseOn() wraps on() & off() instead of simply one()?  (Aside from making it easier to write these tests)

**Comment by maxkfranz** [comment]
```js
    it('removed one event stays removed', function( next ){
      var n = cy.nodes().first();
      var count = 0;
      var inc = function(){ ++count; };

      n.pon('foo').then( inc );
      n.one('foo', inc );

      n.trigger('foo');

      setTimeout(function(){
        expect( count ).to.equal(2);
        next();
      }, 50);

      n.trigger('foo');
      expect( count ).to.equal(2); // not valid
    });
```

That's a good test, but the last line isn't valid.  We can't assume that the promise is fulfilled synchronously.  Otherwise, it looks OK to me.

The `one()` / `once()` listeners should remove themselves with the same copy method.  But doing an inline `filter()` should be a bit cheaper than `removeListener()`.

> Then there's the question of a handler that adds another handler.

It should suffice to store the listener list length at the top of `emit()`.  The list is a snapshot w.r.t. removals, so removals don't need to be considered.  Additions only happen to the end of the list, so caching the length should work.

> Also, is there a reason promiseOn() wraps on() & off() instead of simply one()? (Aside from making it easier to write these tests)

It's a bit more explicit in when the listener is removed and when the promise is resolved, but yes, it could be refactored in a later feature release.

> Edit: Another problem is an event handler triggering another event (e.g. 'tap' handler that converts two quick taps into a 'doubletap') would dirty your emitting control variable.

Yes, it's not a simple on-off.  It's like paren balancing; it needs a stack or a counter.

**Comment by somedmguy** [comment]
Ok, it looks like you've covered every edge case I can think of.
