### ISSUE TITLE
Clarify behavior and documentation when passing "empty collection" to fit, center, animate

### ISSUE THREAD

**Issue by joeframbach** [cytoscape/cytoscape.js#1954]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.2.1
- Browser/Node.js & version : All browsers (but I'm on Chrome 60)

**Current (buggy) behaviour**

When `cy.fit` is called with an empty collection, nothing happens.

**Desired behaviour**

When `cy.fit` is called with an empty collection, all nodes and edges should fit.

**Minimum steps to reproduce**

http://jsbin.com/sozotomugi/1/edit?html,js,output

```
cy.fit(cy.$('#matches-nothing'));
```

**Comment by maxkfranz** [comment]
That's expected behaviour.

Fit to everything: `cy.fit()`

Fit to nothing --- i.e. nop: `cy.fit( emptyCollection )`

It's usually more ergonomic for the dev to see that `cy.fit( eles )` is a nop when `eles.length === 0`.  If something is passed, it generally means you want to fit to it.  So a dev can see that he made a mistake when he calls `cy.fit()` on an empty set.  Otherwise, fitting to the entire graph may look superficially like fitting to some expected set, leading the dev to believe things are working as expected when they are not.

What is your usecase where `cy.fit( empty )` would be useful?

**Comment by joeframbach** [comment]
The documentation states this:

http://js.cytoscape.org/#cy.fit

> If an empty collection or no collection is specified, then the graph is fit to all nodes and edges in the graph.

`cy.$('#matches-nothing')` is an empty collection, so the graph is fit to all nodes and edges in the graph.

**Comment by joeframbach** [comment]
A documentation update would be an acceptable resolution for this issue.

**Comment by maxkfranz** [comment]
Agreed, but it looks like there are other functions that use the same
language and/or have incorrect behaviour.

These functions need to have updates:

- [ ] `eles.center( empty )` : Seems to centre on the origin on empty
collection
- [ ] `cy.animate({ center: { eles: empty } })`
- [ ] `cy.animation({ center: { eles: empty } })` -- this should cover
`.animate()`

These functions need docs updates:

- [ ] `eles.center()`
- [ ] `eles.fit()`

**Comment by maxkfranz** [comment]
(Replacing with md post)

Agreed, but it looks like there are other functions that use the same
language and/or have incorrect behaviour.

These functions need to have updates:

- [ ] `eles.center( empty )` : Seems to centre on the origin on empty
collection
- [ ] `cy.animate({ center: { eles: empty } })`
- [ ] `cy.animation({ center: { eles: empty } })` -- this should cover
`.animate()`

These functions need docs updates:

- [ ] `eles.center()`
- [ ] `eles.fit()`
