### ISSUE TITLE
Resizing the Cytoscape container element interactively

### ISSUE THREAD

**Issue by jri** [cytoscape/cytoscape.js#1987]
I want resize the Cytoscape container element interactively and hoped this would be easy by means of the CSS `resize` property. When adding e.g. `resize: horizontal` to the container the browser shows its resize handle. However when I try to drag it no resize takes place. Instead the graph is panned.

![screen shot 2017-10-05 at 0 43 03](https://user-images.githubusercontent.com/120337/31203177-33ed4e74-a966-11e7-96d4-30e86ab92723.png)

How can I make the browser's resize handle work?
Can Cytoscape detect the resize and suppress the panning in this case?

**Comment by maxkfranz** [comment]
Cytoscape owns all the events that occur on its container.  There is nothing Cytoscape can do to accommodate `resize` CSS.

Further, each browser can potentially have different UI for representing how to resize a div using CSS.  It usually a good idea to use `resize` CSS only on elements where what particular (browser implemented) UI for resizing doesn't matter, like a text area.  If your app design depends on a particular way to represent resizing, it's not really safe to use `resize` CSS.

In any case, you should make the parent DOM element resizable rather than the graph container.  That way you can give the parent some padding etc. to make sure there is enough space for interactivity on the parent element.
