### ISSUE TITLE
List extension : cyto_cxtmenu

### ISSUE THREAD

**Issue by callin2** [cytoscape/cytoscape.js#2061]
https://github.com/callin2/cyto_cxtmenu
Context menu for cytoscape.js. nested and dynamic submenu support.

**Comment by maxkfranz** [comment]
Would you please structure your extension a bit more like the others?

1. There is no demo.
1. There is no documentation in the readme.
1. The source code annotations are not in English.  Programmers generally know at least basic English, so English should be used for all documentation, comments, etc.
1. It would be nice to have a screenshot in the readme, since this is a UI extension.
1. It's not published to npm.

Several of these could be easily addressed by using the scaffolder: https://github.com/cytoscape/slush-cytoscape-extension

**Comment by maxkfranz** [comment]
This can be re-opened once the above points are addressed.
