### ISSUE TITLE
Use ctrl + scroll to zoom (or allow general customization of the zoom "action")

### ISSUE THREAD

**Issue by dee-see** [cytoscape/cytoscape.js#2062]
Feature request

Use <kbd>ctrl</kbd> + scroll to zoom (or allow general customization of the zoom "action")

**Description of new feature**

Just like embedded Google maps and other similar "zoomable" objects (see https://developers.google.com/maps/documentation/embed/guide), it would be great if we could require <kbd>ctrl</kbd> to be pressed to zoom with the scroll wheel.

**Motivation for new feature**

We have a full-width graph in a web page and whenever a user tries to scroll down the page, the graph hijacks the scrolling and turns it into a zooming command. The user has to carefully place their mouse outside of the graph area to scroll and it's irritating

**Comment by maxkfranz** [comment]
You can disable and enable user zooming at will, so you're free to implement the feature you described above in your own app code.  

There are lots of potential options for setting when zooming can happen.  Cytoscape has a sane default that most users expect.  The iframe Google maps example you linked to even has an instructional overlay shown on `wheel` because users expect to zoom on `wheel`.  It's the responsibility of the app author to implement what's appropriate for the app, rather than complicating Cytoscape with N different ways to handle zoom.

N.b. Cytoscape already handles the case where you start scrolling the page *outside* the graph and then continue to scroll while over the graph.  If you `wheel` *within* the graph while zooming is enabled, the graph is zoomed.
