### ISSUE TITLE
Performance on node.js environment : `eles. floydWarshall()`

### ISSUE THREAD

**Issue by piuccio** [cytoscape/cytoscape.js#2070]
**Issue type**

Bug report (maybe)
I'm not too sure

**Environment info**

- Cytoscape.js version : 3.2.9
- Browser/Node.js & version : node 9.4.0

**Current (buggy) behaviour**

First of all, thanks for the library, it's amazing and saved me a lot of time. Second, I might be using it wrong, anyway...

It feels like cy is optimized for the browser and there are some operations that might be unnecessary on node (or any environment that doesn't have a `container`).

Ok, my use case: I have a list of nodes (train stations) and edges (lines); I want to compute, for every node, all the other nodes that are reachable within a certain distance (minutes).

I figured the best approach would be to run the [Floyd Warshall search algorithm](http://js.cytoscape.org/#eles.floydWarshall) as it finds the shortest path between all pairs of nodes and then for every node get the distance (and path) to any other node.

This is how the code looks like more or less

```js
const cytoscape = require('cytoscape');
const graph = cytoscape();

timeBegin('building the graph');
stations.forEach((s) => graph.add({ group: 'nodes', data: s }));
connections.forEach((line) => graph.add({ group: 'edges', data: line }));
timeEnd('building the graph');

timeBegin('calling floydWarshall');
const { path, distance } = graph.elements().floydWarshall({
  weight: (edge) => edge.data().distance,
});
timeEnd('calling floydWarshall');

timeBegin('measure distance');
const allPaths = [];
stations.forEach((s) => {
  stations.forEach((t) => {
    if (s.id === t.id) return;

    allPaths.push({
      source: s.id,
      target: t.id,
      path: path('#' + s.id, '#' + t.id),
    });
  });
});
timeEnd('measure distance');
```

Note that I call the algorithm only once. I figured after that just getting the path between two point would be inexpensive.

Turns out that with ~1400 nodes the timings are

```
perf: building the graph took <1s
perf: calling floydWarshall took 12s
```

Adding nodes and edges in the graph is negligible, fine, calling the algorithm takes 12 seconds, which is ok I guess, there's a lot to process, but then computing all the paths takes so long that I got bored, I don't know how long it would take to compute all of them.

If I make my graph smaller, and work only with 1000 nodes, it would take 6 minutes! Just to make it clear, 6 minutes only to call `path()` which should already have calculated the whole matrix of distances.

**Desired behaviour**

Be faster.

I dug in the code a little bit and applied a couple optimizations:

* Using a string as node identifier seems to loop over all the map to find the node, change that to an object with `id` function (basically a node)

```js
// too slow path('#' + s.id, '#' + t.id)
path({ id: () => s.id }, { id: () => t.id })
```

This change alone takes the time from 6 minutes down to 22 seconds (on 1000 nodes, it's still too boring on 1400)

* Override `cy.collection`. At the end of the [`path` function](https://github.com/cytoscape/cytoscape.js/blob/master/src/collection/algorithms/floyd-warshall.js#L182) you call `return cy.collection( pathArr );` which converts an array to a collection.
My code doesn't really benefit from having a collection, an array works just fine

```js
timeEnd('calling floydWarshall');

timeBegin('measure distance');
graph.collection = (array) => array;
// ... rest is the same
```
I don't know what this function does internally but that one line cuts the time in half, from 22 seconds to 10.

* Override `cy.getElementById`. In a [bunch](https://github.com/cytoscape/cytoscape.js/blob/master/src/collection/algorithms/floyd-warshall.js#L140) [of](https://github.com/cytoscape/cytoscape.js/blob/master/src/collection/algorithms/floyd-warshall.js#L146) [places](https://github.com/cytoscape/cytoscape.js/blob/master/src/collection/algorithms/floyd-warshall.js#L155) there's a `getElementById` that returns the node given its id. The function itself doesn't do much, but if forces me use `node.data()` later on to get information from the node.
Not a huge deal I guess, but replacing it with a simple map that doesn't require another function call later on makes me save 2 more seconds.

```js
const normalizedNodes = {
   nodeOrEdgeId: {},
   nodeOrEdgeId: {},
};
timeBegin('measure distance');
graph.collection = (array) => array;
graph.getElementById = (id) => normalizedNodes[id];
```

All in all I can finally run the algorithm on all my 1400 nodes in 16 seconds. It's not small, but I can live with that.

Anyway, I don't know if you guys want to or can look into the performance issue, I'm putting this up in case anyone else can benefit from it.

**Comment by maxkfranz** [comment]
There was a set of people who worked on the algorithms, mostly students.  They did a good job at making sure that the algorithms that they wrote were correct and that the code was mostly maintainable.  There was no time for performance optimisations.

There are [plans to improve the algorithms](https://github.com/cytoscape/cytoscape.js/issues/1224), but pragmatically, I'm not sure how many will be able to be addressed for 3.3.  If you'd like to address `eles. floydWarshall()` in a pull request, that would be great.

You mentioned that most of the issue is with use of (or lack of use of) collections.  A collection has been historically immutable -- the set of elements in the collection can not change.  That's great for a lot of things (especially UI usecases), but it's not great for performance in things like algorithms.  

That's why there's now functions like `eles.merge()` and `eles.unmerge()` to modify a collection in place.  Most collection APIs still treat it as immutable, but there is a concession of mutability for performance-intensive usecases.  The algorithms didn't have access to these APIs.

(1) So basically, the main change to make would be to use collections from the start instead of separate maps and arrays.  A collection can be used like a list/set and can be queried performantly for element membership.  Creating a collection at the end duplicates a lot of work being done manually in the algorithm right now. 

(2) The other change to make would be to remove all selector creation/querying and replace it with `eles.getElementById()` -- which is a quick map lookup rather than a filter (with a selector object created).

Probably the main change for #1224 would be to address (1) and (2) for each function.  If you want to do that in a PR for `floydWarshall()` that would be great.  There are facilities in './benchmark' to test performance differences.

**Comment by piuccio** [comment]
Thanks for the message. The algorithms works pretty well. Yesterday just for the fun I forked the code and removed all things `cy` specific, so leaving just the algorithm working on plain arrays. The speed is comparable to what I obtained with those couple tricks.

Obviously I'm not too familiar with the code base but I'll see if I can make a PR, at least to fix (2), it seems more approachable.

**Comment by maxkfranz** [comment]
Ref https://github.com/cytoscape/cytoscape.js/issues/1224
