### ISSUE TITLE
taphold as ctrl-click, tap as click

### ISSUE THREAD

**Issue by maurocasonato** [cytoscape/cytoscape.js#2086]
**Issue type**

Feature request

**Description of new feature**

Use "taphold" event to reproduce in a touch screen the "ctrl-click" event. In this way more elements are easily selectable. Moreover the "tap" event should work as the "click" event, for example to deselecting all elements when free space is tapped. In cytoscape 3.2.11 to deselect it is necessary instead the "taphold" event. The "taphold" event, when no elements are selected, can be used to show the context menu (right-click menu). This is very important when the context menu is tied to an element (e.g. for the "remove" menu item); cytoscape.js now requires a two-fingers tap to show the context menu, but this is very complicated to tie to an element.

**Motivation for new feature**

The increasing use of touch screen devices requires a complete "gesture standard", that allows a user to work as with a mouse and keyboard.

**Comment by maxkfranz** [comment]
It seems the generally standard action performed on touch devices for holding the finger is to show some kind of menu or show some kind of preview.  I don't think that it makes sense for Cytoscape.js to then enforce a default action on `taphold`.  That would conflict with all apps that expect to show a menu on `taphold`, for example.

The average user does not use box selection much, even on desktop.  I don't expect that many users would use box selection on touch devices.  You can use `selectionType: 'additive'` to make selection of multiple elements easier.

As for tapping the background, you can write a small amount of code to enable this behaviour.  There's nothing in the lib that would conflict with tapping the background to deselect all elements.  The reason that `taphold` is used instead of `tap` for deselection by default is that we found from user testing that `tap` can be too easy to do by accident.

**Comment by maurocasonato** [comment]
Ok thanks for the first and last clarification, but for "ctrl-click" I mean merely ctrl-click not the ctrl-mousedown-drag-mouseup, that is the box selection. The "ctrl-click" is normally used to select more cells/rows on a spreadsheet file, more strings on a text file, and more nodes on a cytoscape graph, and for this reason it should be translated in a simple gesture.

**Comment by maxkfranz** [comment]
> The "ctrl-click" is normally used to select more cells/rows on a spreadsheet file

That's exactly what `selectionType: 'additive'` does.

**Comment by maurocasonato** [comment]
> That's exactly what `selectionType: 'additive'` does.

It's not true. What `selectionType: 'additive'` does is to add an element in the selection set with a simple "click" not "ctrl-click", and for this reason this option cannot be used because it changes the normal behaviour expected by any user for any application.

**Comment by maxkfranz** [comment]
These are typical touch-based actions that can be performed:

1. one-finger tap
1. one-finger swipe (i.e. tap and drag -- move a node, pan, etc.)
1. pinch (i.e. to zoom)
1. taphold
1. cxt (two side-by-side fingers) tap
1. cxt (two side-by-side fingers) swipe
1. multiple, separated finger swipes -- not supported by Cytoscape.js

The list is sorted by descending probability of a user making the action. You can expect typical users to only do the top three.  The remainder tend to be performed *very* rarely.  There is only one of the top three actions that a user would expect to be selection:  Tap.  And thus, `selectionType: 'additive'` uses tap to be a sane default.

Taphold is used over tap for deselecting everything, because users tend to accidentally tap the background.  Admittedly, this makes it difficult to deselect everything.  Perhaps it would be better to just use tap for global deselection, and then leave the problem of handling of accidental deselection to devs to handle on their own.

If you want to customise the selection behaviour, you are free to do so outside of the lib.  You could even package it as [an extension](http://js.cytoscape.org/#extensions), if you like.

The only prerequisite for writing an extension like that would be to add `cy.userSelectionEnabled()` to allow disabling of the default, built-in selection gesture.  If you're interested in custom selection behaviour and would like to make a PR for `cy.userSelectionEnabled()`, that would be great!

New selection behaviours (e.g. taphold to select) are not going to be added to the core lib.  Eventually, `selectionType: 'additive'` will no longer be a core feature and will be an extension instead.

**Comment by maurocasonato** [comment]
So for the moment the only way to select more than one node on a touch screen device is set the core with `selectionType: 'additive'`, right?

**Comment by maxkfranz** [comment]
If you only want to use built-in gestures in 3.2, you would have to use `selectionType: 'additive'`.  In 3.2, you could alternatively use additional UI elements, like the cxtmenu, to do custom selection actions.

**Comment by maurocasonato** [comment]
- `selectionType: 'additive'` cannot be used because on mouse-input devices it changes the normal behaviour for additive selection, expected by any user for any application. 
- The cxtmenu cannot be used because on touch devices it's impossible to point to a node with two fingers; sometimes the node is pointed by one finger and sometimes by the other finger, unpredictably.

Any other suggestion?

**Comment by maxkfranz** [comment]
Ref : Change the default deselect touch gesture to background tap #2190
