### ISSUE TITLE
I can't bind events on dynamically added elements, WHY?

### ISSUE THREAD

**Issue by wbl0930** [cytoscape/cytoscape.js#2090]
I use "cy.add()" to add a node,but i can't bind events on dynamically added elements, WHY?

"cy.nodes().on("click",function(e) {......"    -----》 This does not work.	

Who can help me？  Thanks！！！

**Comment by shabble** [comment]
if you mean that you're calling `cy.nodes().on('click', ...)` to set some handler, and then sometime later adding additional nodes with `cy.add()` which aren't responding, that is to be expected because only the nodes that existed (ie: the collection that `cy.nodes()` returns) at the time of the handler setup will be bound. You might find the [jQuery docs on delegate handlers](https://learn.jquery.com/events/event-delegation/) helpful (although cyto isn't using the exact same mechanisms, it's close enough to be useful).

You might want a delegated handler (`cy.on('click', 'nodes', ev => { ... })`) instead.

This seems like a support question better suited for [cytoscape tag on Stack Overflow](https://stackoverflow.com/questions/tagged/cytoscape.js) though.
