### ISSUE TITLE
`ele.classes()` getter & aliases

### ISSUE THREAD

**Issue by sjneph** [cytoscape/cytoscape.js#2110]
Allow getting the list of classes on an element as an array, i.e. `classArray = ele.classes()`.

Also allow `ele.className()` and `ele.classNames()` as aliases of `ele.classes()`.

OP follows:

--

I find it useful to know which classes might be assigned to a collection.  Could you provide a space-separated list method, please?  I recommend an implementation similar to the following in classes.js.

```
  getClasses: function () {
    let ele = this[0];
    return (ele != null)
      ? ele._private.classes.toArray().toString().replace(/,/g, " ")
      : "";
  },
```

**Comment by maxkfranz** [comment]
`ele.json().classes`

**Comment by maxkfranz** [comment]
See https://github.com/cytoscape/cytoscape.js/issues/2019

It would probably be better to support getting/setting arrays with `ele.classNames()`, since for v4 it's planned to change the default JSON export to use arrays.  That way, `classNames()` is future-proofed and only old things would need to be changed.

```js
el.classNames(['a', 'b']); // set
el.classNames(); // get
el.classNames([]); // clear, maybe also allow null to clear
`
