### ISSUE TITLE
Support circle shape for compounds

### ISSUE THREAD

**Issue by Aluriak** [cytoscape/cytoscape.js#2129]
**Description of new feature**

According to the doc and to my tests on [a demo](http://js.cytoscape.org/demos/cose-bilkent-layout-compound/):
> Only `*rectangle` shapes are supported by compounds, because the dimensions of a compound are defined by the bounding box of the children
I would want to be able to make compounds groups as circle, and why not any other shape available for nodes.

The reason behind the limitation seems perfectly sain to me. However, i think that, at least for a first version, it would be possible to just bound the position of nodes in a rectangle (as usual), but draw a circle that contains the rectangle instead of the rectangle itself.

**Motivation for new feature**
I am working on hierarchical graphs, and currently there is not much solutions to visualize them. Cytoscape 2 has some non-official and non-maintained way to get them in a limited manner. Some other desktops software has also some support (if it was not dropped few versions ago), but in the end the only maintained way i can visualize my graphs are cytoscape.js, and to improve the visualizations, having the possibility to have different shapes would be awesome.

Thank you !

**Comment by maxkfranz** [comment]
I don't think that this is something that would be added in the lib itself, because it would be inconsistent with how every other shape works.

You could do something visually similar by hiding the node body and using an ellipse as an SVG background image.  Having this feature would also help:

Expand drawing box style property #1782
