### ISSUE TITLE
mapData shows missing data as minValue - wrong, it is missing, we don't know it.

### ISSUE THREAD

**Issue by smoe** [cytoscape/cytoscape.js#2199]
**Issue type**

Bug report - at the borderline to a feature request, admittedly

**Environment info**

- Cytoscape.js version : 3.2.17 and earlier
- Browser/Node.js & version : Firefox (latest) and others

**Current (buggy) behaviour**

mapData does not treat missing data any different from a minimal value. Presenting data wrongly qualifies as a bug for me.
**Desired behaviour**

there should be a special value that is chosen when the data is missing. That value should be indicated by the programmer.

**Minimum steps to reproduce**

See documentation at http://js.cytoscape.org/#style/mappers - the API would need to change.

**Comment by maxkfranz** [comment]
There should be an error message in the console if you do this.  A mapper must have valid values defined for all elements that match the containing selector block.  It's up to the programmer to specify the rules for how the style should be applied using the selector blocks.

The existence selector should suffice for that, e.g.:

```
node[foo] {
  background-color: mapData(foo, 0, 100, red, blue);
}

node[^foo] {
  background-color: yellow;
}
```

If you use an explicit `null` value rather than `undefined`, then `[?foo], [foo = 0]` matches non-null, non-undefined values of `foo`.

"Null" just means zero, and zero is usually towards the bottom of a mapper.  I suppose that's why the bottom of the range is used, but the value that is used in an error case is arbitrary:  It's just to prevent crashes.  Just as the browser doesn't crash on invalid CSS files, Cytoscape tries not to crash where possible on invalid stylesheets.
