### ISSUE TITLE
Overlapping compound nodes

### ISSUE THREAD

**Issue by ghamarian** [cytoscape/cytoscape.js#2220]
**Issue type**

Feature request

**Environment info**

- Cytoscape.js version :
- Browser/Node.js & version :

**Description of new feature**

I would like to have nodes with multiple parents, i.e., intersecting compound nodes. 

**Motivation for new feature**

I am creating a graph editor for bayesian nets (template notations) in cytoscape.js. In the template notation sometimes I need to have a node with two parents. Like the graph in the picture.
![image](https://user-images.githubusercontent.com/17321904/48716290-4886d900-ec17-11e8-994e-d06b8b69bf1f.png)

The picture is taken from: https://github.com/jluttine/tikz-bayesnet

**Comment by maxkfranz** [comment]
Compound nodes are not intended to be used for overlapping sets:  Compounds exist in a strict tree hierarchy.  That can not change in the model.

If you're interested in visualising overlays like these, it might be a better fit to use something like [cytoscape-canvas](https://github.com/classcraft/cytoscape.js-canvas).

**Comment by ghamarian** [comment]
I have implemented this by allowing parent to be collections, and a couple of minor adaptation. Would you be interested in a pull request or is it against your design policies?

**Comment by maxkfranz** [comment]
The compound node model, by definition, is one parent maximum per node.  So that's not something that we can support directly in the library.

It would be great if your usecase could be supported by an [extension](http://js.cytoscape.org/#extensions).  If an existing extension does not meet your requirements, I would encourage you to create one.  An extension can be [scaffolded for you](http://js.cytoscape.org/#extensions/autoscaffolding), and they're easy to write.

You could, for example, create an extension that reads `node.data('sets')` for a specification of the list of sets (other node IDs).  For each set node, your extension would update the bounds appropriately.

**Comment by ghamarian** [comment]
![cytoscape_intersecting](https://user-images.githubusercontent.com/17321904/52737998-f531e600-2fcd-11e9-83f4-cb51ca24a8bd.gif)

**Comment by maxkfranz** [comment]
> I think the change I suggested cannot be done with an extension as it required a change to the data structure

I meant that in the extension case that the extension would not use compound nodes at all:  It would maintain set nodes (that are automatically sized by the extension in a way similar to compound nodes) using a key like `sets`.

Because the definition of compound nodes is a tree of nodes, we can't merge in changes to the main lib that would contradict this definition.

**Comment by maxkfranz** [comment]
Take a look at https://github.com/upsetjs/cytoscape.js-bubblesets.  @sgratzl may be interested in collaboration.

The main paper I'm aware of on this topic is [Bubble Clusters: An Interface for Manipulating Spatial Aggregation of Graphical Objects](https://www-ui.is.s.u-tokyo.ac.jp/~takeo/papers/watanabe_uist2007_bubble.pdf) by Watanabe et al.

https://www-ui.is.s.u-tokyo.ac.jp/~takeo/research/bubble/index.html

The video on the U Tokyo website is very compelling

(N.b. using a compound-like node (rectangles) for sets may not be the best idea -- consider layout and visual overlap.)

**Comment by yisehak-awm** [comment]
Has there been any activity on this?
