### ISSUE TITLE
Chrome crashes with specific font-family on MacOS

### ISSUE THREAD

**Issue by step4** [cytoscape/cytoscape.js#2249]
**Environment info**

- Cytoscape.js version : 3.3.1
- Browser version : Chrome Version 71.0.3578.98 (Official Build) (64-bit) MacOS

**Current (buggy) behaviour**

Chrome on MacOS crashes when a specific font-family is used for styling a node. I can not try it on windows right now.
The font-family is 'BlinkMacSystemFont'. Actually it happens with specific zooms. 
I will provide example for both cases.
With version 3.2.17 cytoscape works as expected.

**Minimum steps to reproduce**

https://output.jsbin.com/zikurub

just change the version from 3.2.17 to 3.3.1 and the Chrome tab should crash with this:

<img width="750" alt="screenshot 2018-12-22 at 01 08 07" src="https://user-images.githubusercontent.com/11348121/50368176-1bb34200-0586-11e9-9119-6a73e3f0e4ef.png">

this example should crash when you start zooming:

https://output.jsbin.com/yaquhed

**Comment by maxkfranz** [comment]
This is a Chrome bug that seems to be fixed in newer releases.  Safari and Firefox are fine as well.  For issues like this, there's nothing we can do.  It's up to the browser vendor to fix them.

Since the Chrome team seem to have fixed the issue, I'm closing the issue.  In cases where they don't fix the issue, you should post the issue on the Chromium issue tracker.
