### ISSUE TITLE
[documentation][selectors] meta characters 

### ISSUE THREAD

**Issue by einsweniger** [cytoscape/cytoscape.js#2319]
**Issue type**
Bug report

might be related to #722

The documentation caveats remind to escape meta characters, but the ones mentioned in the documentation differ from those in tokens.js

https://github.com/cytoscape/cytoscape.js/blob/d9424465f7a90303fa122cdef9df476ed6151072/src/selector/tokens.js#L5

https://github.com/cytoscape/cytoscape.js/blob/d9424465f7a90303fa122cdef9df476ed6151072/documentation/md/selectors.md#L32

I am unsure if the choice is deliberate, I might be missing something here.

**Comment by maxkfranz** [comment]
It could be that the list in the docs is incomplete.  I think at least some of the cases in the code aren't absolutely necessary but are just included just in case (e.g. an old browser doesn't support it directly).

**Comment by maxkfranz** [comment]
I think the only place this would apply would be field names under `data`, like the example `cy.filter('#some\\$funky\\@id');`.  

String values would already follow the normal JS rules for escaping with `\`.

So if this only applies to field values, the list might already be too big.  The only valid and good practice character for a field/variable name in that list is `$`.  Would someone really use field names under `data` like `my|^weird+*field`?

Maybe the list should be pared back instead of expanded.

**Comment by einsweniger** [comment]
I have to admit, that I'm still not entirely certain about JS escaping rules, but I agree.
Is there some resource (MDN?) that documents these? I think pruning the list is fine, if there is a link to these rules; that might help some people that are unfamiliar to JS.

I mean, I'm still not dead certain about some aspects of the language, but due to the amazing documentation of cytoscape.js I was able to use it anyway :D (which is also the reason I ended up opening issues).

Although, if there was an Object with:

```js
let document = {
  "doc.type": "person",
  // ...
};
```

where "doc.type" had several possible values, could you build a selector for that or would one have to remodel the data? Just asking, because I have had this _issue_ and just remodelled the data.

**Comment by maxkfranz** [comment]
No, how would you know what's meant?

```js
let document;

// was it this? (1)
document = { doc: { type: 'foo' } };

// or was it this? (2)
document = { 'doc.type': 'foo' };
```

There is no clear way to differentiate that in a selector, and to assume (2) would break with the principle of least surprise.  For weird cases like that, you're almost always better served by a filter function.  In a stylesheet you can't use a filter function, but you can use a mapper function that specifies a property value for each element.

According to [Stack Overflow](https://stackoverflow.com/questions/1661197/what-characters-are-valid-for-javascript-variable-names), which links to the spec, a variable name can be almost anything in unicode -- even something silly like a smiley character or any other non-ASCII character.  

General best practises dictate that things like variables should be named in English using ASCII -- using only `[a-zA-Z]` and maybe also `_`.  In JS `$` slipped through on account of jQuery.

The only case I can think of where someone would have a need for weird field names is the use of an object as a map.  You may have a map, for example, that uses email addresses as keys.  That would include characters like `.` and `@`.  Because of `.`, I don't think it would work.  But in any case, it would be far better to use a real `Map` under `scratch` (non-serialisable / non-JSON data).  The built-in selectors are intended to be used for straightforward things like numbers and booleans that are intuitive to map.  Anything more complicated than that is generally better off using custom filter and mapper functions.

**Comment by einsweniger** [comment]
I know about the best practices, but some API won't accept the nested documents.
My linter is very annoyed about it as well :D This was just out of curiosity.

I've read through the links, and I'm dazzled by what's legal for variable names. I'm not so sure anymore if the docs should link to that, except with a note/warning "for _very_ curious people only".

I'd leave the decision up to you, maybe I'd extend `Note that metacharacters` to `Note that metacharaters such as`, but that's optional IMHO.

**Comment by maxkfranz** [comment]
> I know about the best practices, but some API won't accept the nested documents.
My linter is very annoyed about it as well :D This was just out of curiosity.

I expected you knew, but it's helpful to be descriptive for other people who read this thread in future.

I'll try to update the text today, keeping in mind the warning you suggested.  Thanks

**Comment by einsweniger** [comment]
Nice, Thank you!
