### ISSUE TITLE
Extension idea: Allow Pan with Middle Mouse Button

### ISSUE THREAD

**Issue by UweHeim** [cytoscape/cytoscape.js#2335]
Core Library Feature Request

Currently you pan with left button ONLY. I would prefer if you can pan with the middle button (e.which==2), too (alternatively or additionally). There could be an option to turn this feature ON and OFF. Can be OFF as default.

I have a working patch of version 3.2.16

I have patched the library in 5 lines, mostly looking like
    // } else if (r.hoverData.which === 1) { 		// removed
    } else if (r.hoverData.which === 1 || r.hoverData.which === 2 ) { //added

I can provide all patched lines and/or patch the newest version, too - if needed.

**Motivation for new feature**

Users of CAD Software expect the middle button to work like that. The middle button is currently totally unused and vacant. If the feature can be turned ON and OFF (and if OFF is default), it would not hurt anyone. In mobile use-cases it should not hurt anyone, either.

**Comment by maxkfranz** [comment]
I know that this took a while for an answer, but I wanted to review this issue fully before answering.

It seems we shouldn't be using `which` at all actually: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button

I think we used `e.which` because we originally wanted to target browsers as old as IE6.  We eventually decided on a canvas implementation for the renderer, so in practice we can only support IE >= 9 with the default renderer.  I suspect `event.which` isn't generally reliable beyond left and right clicks.  In any case, it's not officially supported and deprecated.

Anyway, I don't generally want to support features in the core that could have spotty cross-browser or cross-hardware support.  For example, we don't support a double-click event.  Just like a physical product or a UI, a library has affordances.  If we allowed events like double-click, then the library makes it too easy to create apps that have bad user experiences.  I really don't want that.  If we were to add support for middle mouse buttons at all in the core library, then there would need to be full support (`middleclick`, `middledrag`, and so on).  And then we have the same problems as double-click:  It's too easy to abuse, especially when the library encourages you to do it by having the option.

Further, the core has too many initialisation options as it is.  Several should be removed altogether, and others should be extensions.  For example, `selectionType` be an extension rather than a core feature.  Here's a good article on the subject: [Why not add an option for that?](http://neugierig.org/software/blog/2018/07/options.html).  The author focusses on end-users, but much applies to libraries as well:  The user, or consumer, of a library is a programmer.

In this case, I think this feature should be an extension.  I admit that this would be a bit more lines of code than your patch, but I don't think that this feature belongs in the core.  I appreciate your usecase, and I think the feature should be able to exist somehow --- but outside of the core library.
