### ISSUE TITLE
Taxi edges should automatically forbid endpoints other than `outside-to-node` 

### ISSUE THREAD

**Issue by assafweinberg** [cytoscape/cytoscape.js#2343]
**Environment info**
- Cytoscape.js version 3.5:
- Browser/Node.js & version : Chrome 73.0.3683.86 

**Current (buggy) behaviour**
When creating taxi edges between parent nodes, the edge turns at on-right angles. Sometimes the turns take very strange routes and have more than one turn.

<img width="549" alt="Screenshot 2019-03-27 14 21 05" src="https://user-images.githubusercontent.com/327664/55115668-4ee40080-50a2-11e9-954d-ff6a7dcef820.png">

**Desired behaviour**
Taxi edges between parent nodes should default to a single right angle turn.

**Minimum steps to reproduce**
https://jsbin.com/vegopuc/edit?html,css,js,output

**Comment by ar-stackrox** [comment]
@maxkfranz I'm also encountering this issue. Is it a bug in the library?

**Comment by steevokovsky** [comment]
> **Current (buggy) behaviour**
> When creating taxi edges between parent nodes, the edge turns at on-right angles. Sometimes the turns take very strange routes and have more than one turn.


This occurs not just between parent nodes connected via taxi edges but also with any node (compound or non compound, edge target or edge source) connected with a parent (compound node).

**Comment by maxkfranz** [comment]
You should have endpoints specified as `outside-to-node` for a taxi edge.  That's not yet documented anywhere.  It's a tacit assumption:  No other endpoint makes sense for a taxi edge.  The issue here is not with compound nodes, rather it is with the endpoint specification.  

The default stylesheet specifies `outside-to-line` for `:compound` edges with `curve-style: bezier`.  This helps to make compound-connected edges work nicely by default:  The general default of `haystack` doesn't make sense for compounds.  And for beziers to work well for compounds of large size, you really need `outside-to-line`.  Unfortunately, this default does not work well if you set only `curve-style: taxi` without updating the endpoints appropriately.

I've updated the documentation and I've made a patch to force the endpoints of a taxi edge to `outside-to-node` regardless of what the consumer sets.  You could set that in your own stylesheet before the patch is released.

**Comment by maxkfranz** [comment]
Example:  `outside-to-line` doesn't make sense for a taxi edge.  See how the straight, grey line shows the intersection for the endpoint.

<img width="508" alt="Screen Shot 2019-03-29 at 1 19 25 PM" src="https://user-images.githubusercontent.com/989043/55254577-a2835500-522e-11e9-95fb-9daf67a62d2b.png">

`outside-to-node` makes sense:

<img width="613" alt="Screen Shot 2019-03-29 at 2 11 59 PM" src="https://user-images.githubusercontent.com/989043/55254626-c9da2200-522e-11e9-8d25-3297906681fd.png">
