### ISSUE TITLE
Allow active selector overlay 'shape' to be changed

### ISSUE THREAD

**Issue by schnaepschen** [cytoscape/cytoscape.js#2379]
Is there a way for the overlay shape to be changed for the active selector ?

E.g. from the current round-cornered square to a circle ?

Thanks.

**Comment by maxkfranz** [comment]
It does not exist.  If you're interested in the feature, it would be useful to specify the style properties you propose -- more or less according to the issue template. Naturally, a pull request would also be appreciated.

**Comment by michalhabala** [comment]
Actually the default behavior for the node overlay was using the same shape as the selected node has but it was changed in 2014 to 'roundrectangle' because of some rendering issues with Yue's n-sided-polygons which were behaving oddly if n was odd :) 

More info is in this issue : #419
[Here is the commit](https://github.com/cytoscape/cytoscape.js/commit/dc6cdb84eec27a3ee5bbfc70602c7da2a04ea633) which changed the dynamic behavior to 'roundrectangle' constant

I think the best solution is to bring back the default dynamic behavior (if the rendering problems mentioned in #419 are solved).

I think all it takes is to change in this file: [drawing-nodes.js](https://github.com/cytoscape/cytoscape.js/blob/unstable/src/extensions/renderer/canvas/drawing-nodes.js) in the CRp.drawNodeOverlay function
this part:
`r.nodeShapes[ 'roundrectangle' ].draw(
      context,
      pos.x,
      pos.y,
      nodeWidth + overlayPadding * 2,
      nodeHeight + overlayPadding * 2
    );`
to this:
`r.nodeShapes[ r.getNodeShape( node ) ].draw(
      context,
      pos.x,
      pos.y,
      nodeWidth + overlayPadding * 2,
      nodeHeight + overlayPadding * 2
    );`


@maxkfranz I can make a pull request with this change, but I think it should be tested carefully against the issues in #419 for which I don't have the capacity right now.


On the other hand it'll be nice to have the option to change the shape of the overlay. In such case I propose this setting:
- **"overlay-shape"** : determines the shape of the node overlay in :active state. The same shapes can be used as in node's shape property

**Comment by maxkfranz** [comment]
I don't think it would be sufficient to just specify shape, since the overlay is always the same ratio plus equal padding on all sides as the node.  That would give a bad experience for several shapes, including `ellipse`.  It wouldn't look right in many cases.

`overlay-shape` is a good idea, but I think we may need to build on it more for it to work the way that people tend to like.

What we have right now is very consistent with how browsers (especially mobile browsers) indicate an active element.  It's always a round rectangle.  While not very flexible, it's easy to use and consistent.

**Comment by zakjan** [comment]
Hi @maxkfranz, I took a look at implementing `overlay-shape` property in #2881. Would this be enough to merge, in order to improve the visual look for basic shapes?

Triangle overlay could be improved by either an automatically computed overlay offset, or by providing `overlay-offset-x/y` properties.

Proper support for non-square bounds, vee overlay, or custom polygon overlay would mean more significant changes. Overlay padding would need to be applied using rounded corners at each shape point instead of sharp angles.
