### ISSUE TITLE
Accessing an empty array in bounds.js

### ISSUE THREAD

**Issue by manotoor** [cytoscape/cytoscape.js#2391]
https://github.com/cytoscape/cytoscape.js/blob/ad2051b65e2243cfd953d8b24a8bf95bfa8559e5/src/collection/dimensions/bounds.js#L504

in the next lines we try to access ex1 but if htps = [] there is no htps[0].x
var hpts = rstyle.haystackPts || [];
        ex1 = hpts[0].x;
        ey1 = hpts[0].y;
        ex2 = hpts[1].x;
        ey2 = hpts[1].y;

**Comment by maxkfranz** [comment]
Please follow the issue template and provide a demo of your issue.  I'll gladly re-open the issue once you do.

**Comment by manotoor** [comment]
@maxkfranz sure, I'll look for the template. I think this is more of a JS bug than a cytoscape bug

if we set hpts to rstyle.haystackPts || []
when hpts = []
you cannot access hpts[0]

**Comment by maxkfranz** [comment]
> you cannot access hpts[0]

Yes, you can.  It's undefined rather than generating an exception.

**Comment by manotoor** [comment]
right hpts[0] is undefined. So
hpts[0].x throws a TypeError
```
Uncaught TypeError: Cannot read property 'x' of undefined
```

**Comment by motin** [comment]
I tried to to reproduce this issue but failed, but this particular kind of issue should not require a test case or reproducible example since it is a clear logical error in the code. There is no way that the code can run past `rstyle.haystackPts` being falsy at this point. Either throw a controlled error here or replace `[]` with `[{},{}]` so that `hpts[0].x` and `hpts[1].x` returns undefined rather than throwing an error.

**Comment by r-ba** [comment]
@motin Any potential issue in this direction was amended by cc1d7bb91.
