### ISSUE TITLE
Special Characters in Node Labels

### ISSUE THREAD

**Issue by shean42** [cytoscape/cytoscape.js#2462]
I'd like to have node labels with German umlaut characters, i.e. Ü,Ö,Ä and ü, ö, ä. Interestingly only the lowercase characters are correctly rendered, for the uppercase ones the dots over the characters are missing. I suspect this is not the intended behaviour :-)

Quick demo with v3.8.1: [https://jsfiddle.net/Ltz6uxwb/1/](https://jsfiddle.net/Ltz6uxwb/1/)

**Comment by maxkfranz** [comment]
The demo works on my machine, Mac 10.13.6 on Safari, Chrome, and Firefox.  You should be able to use labels like "Äpfel".

It's probably an issue with a particular font or how your OS is reporting text dimensions.  What OS, browser, and font are you using?

**Comment by shean42** [comment]
Thanks a lot for the hint! I'm using it in a Lubuntu 18.04 VBox and the dots are missing in current versions of FF and Chromium. Just tested with FF on Ubuntu 18.04 (non-VM) and a current Android version and both are fine!

**Comment by maxkfranz** [comment]
It seems that Lubuntu does not report the text dimensions correctly and the marks above ascenders are not taken into account:

![Screen Shot 2019-07-18 at 1 30 56 PM](https://user-images.githubusercontent.com/989043/61479062-0312db00-a961-11e9-81a0-bcad451a6e03.png)

The issue may be in how LXQt reports text dimensions to the browser.  I don't foresee a robust workaround for this, since fonts can vary a lot.

If Lubuntu support is important to you, I suppose you could replace "Ö" with "Oe" as a workaround.

**Comment by shean42** [comment]
Thanks for following up on this Max!

Lubuntu is really only used as a lightweight dev environment for a VM over here and thus we can safely ignore this!

viele Grüße :-)
