### ISSUE TITLE
An element must be of type `nodes` or `edges`; you specified `nodes`

### ISSUE THREAD

**Issue by KonradHoeffner** [cytoscape/cytoscape.js#2501]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.9.x
- Browser/Node.js & version : Firefox Developer Edition 69

**Current (buggy) behaviour**
Loading a JSON file where values are mistakenly placed as singletons instead of values (e.g. `["nodes"]` instead of "nodes") produce a confusing error message: 

> An element must be of type `nodes` or `edges`; you specified `nodes`.

**Desired behaviour**

While it is obviously the wrong format, a clearer error message would help with bugfixing.
It happened to me because I used `new JSONObject()#append` instead of `new JSONObject()#put` in Java.
Proposal: "single value expected but array encountered".

**Steps to Reproduce**
Load the following into a Cytoscape.js graph:

```
[
  {
    "data": [{"id": ["myid"]}],
    "position": [{
      "x": [42],
      "y": [90]
    }],
    "group": ["nodes"]
  }
]
```

**Comment by maxkfranz** [comment]
I think this is a matter of `Array.prototype.toString()`, which would be used to implicitly cast an array to a string with string concatenation operators.  This same problem affects several different warning and error messages.

I suppose we could do something like `JSON.stringify()` on all values, but that could cause conflicts in some cases.

**Comment by maxkfranz** [comment]
Because of the inconsistency in different messages (and because I'm cleaning up the issue tracker), I'm going to close this for now.

For now, the best solution is to use the debugger and set it to break on any uncaught exception.  This will allow the programmer to inspect each value.

We can re-open this issue when there's a better solution that can be applied to all the error and warning messages.
