### ISSUE TITLE
Gradient stops incorrect w.r.t. padding & direction

### ISSUE THREAD

**Issue by perrelle** [cytoscape/cytoscape.js#2507]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.9.1
- Browser/Node.js & version : Firefox 68.0.2 (64-bit) & node v10.15.2

**Current (buggy) behaviour**

When using `'width': 'label'` with nodes, a padding, and a linear gradient, the color is uniform between the border and the content area, and the gradient starts only at the contents area. In other words, a stop at "0%" is not at the border but at the content area. The same goes for the "100%" stop.

**Desired behaviour**

A similar behaviour as in CSS gradient where the gradient starts end ends at the border, without uniform areas, and regardless of the padding style.

**Minimum steps to reproduce**

Current behaviour : https://jsbin.com/fahojiviwo/1/edit?html,output
CSS behaviour : https://jsbin.com/fikunel/edit?html,output

Also note that in CSS, `to left` have the opposite meaning.

**Comment by maxkfranz** [comment]
You're right:  Generally, things should be like CSS where possible.

I think the original PR for gradients used property values like "left", and I requested values like "to-left" to make it more similar to CSS.  It looks like the name was revised but not the behaviour.  I suppose "left" meant "from-left" rather than leftwards like "to-left".

As for padding, it may have just been an oversight in the same PR that the inner content box is used instead of the padding box.  This might be because we have don't have functions for the padding box.  `width()` and `height()` are for the inner content box, while `outerWidth()` and `outerHeight()` are for the border box.  Maybe we should add something like `paddingWidth()` and `paddingHeight()` as private, undocumented functions to make contributions like gradient support easier in future.  I don't think that the name is really clear, though.  It sounds like it could be the padding value itself.

**Comment by maxkfranz** [comment]
Divs:

![Screen Shot 2019-08-30 at 1 51 36 PM](https://user-images.githubusercontent.com/989043/64043086-6d5a9600-cb31-11e9-9f38-fea7f1ebf3a3.png)

Revised linear node gradients:

![Screen Shot 2019-08-30 at 1 51 24 PM](https://user-images.githubusercontent.com/989043/64043057-5ae05c80-cb31-11e9-9a57-edd8637466df.png)

**Comment by perrelle** [comment]
Thank you ! It works like I would expect it to work. Amazing work !
