### ISSUE TITLE
When rstyle.haystackPts is not defined, the code crash Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by alessandro308** [cytoscape/cytoscape.js#2529]
The line https://github.com/cytoscape/cytoscape.js/blob/088995626b9cd69013da183980a3f178edc5a149/src/collection/dimensions/bounds.js#L519

can produce 
```
cytoscape.umd.js:9744 Uncaught TypeError: Cannot read property 'x' of undefined
    at boundingBoxImpl (cytoscape.umd.js:9744)
    at cachedBoundingBoxImpl (cytoscape.umd.js:9936)
    at Element.elesfn$j.boundingBox (cytoscape.umd.js:10049)
    at getBb (cytoscape.umd.js:27765)
    at makeLayer (cytoscape.umd.js:27775)
    at LayeredTextureCache.LTCp.getLayers (cytoscape.umd.js:27824)
    at Renderer.CRp$1.drawLayeredElements (cytoscape.umd.js:28469)
    at Renderer.CRp$6.render (cytoscape.umd.js:30208)
    at renderFn (cytoscape.umd.js:26591)
```
when rstyle.haystackPts is not defined.

**Comment by maxkfranz** [comment]
Please provide a reproducible test case or demo.

**Comment by alessandro308** [comment]
I cannot reproduce the error quickly. Anyway, reading the code is trivial to verify that the line 519 can produce the error if initialized to [] since three lines after there is
`ex1 = hpts[0].x;`

**Comment by maxkfranz** [comment]
That's true on the surface, but you shouldn't get to that condition in the first place.  There are two possibilities for why your code would get there:  (1) Your code does something invalid.  (2) There's a deeper bug that causes this condition.

I generally don't apply patches unless the true root cause of the issue is understood.  A superficial patch often only addresses the problem superficially, with the problem persisting elsewhere.  So, we really should start with a test case.

**Comment by josejulio** [comment]
As a side question, why is the variable initialized with `[]` when `rstyle.haystackPts` is falsy?
Isn't it better to just leave it as: `let hpts = rstyle.haystackPts` ?

**Comment by maxkfranz** [comment]
> As a side question, why is hpts initialized with [] when rstyle.haystackPts is falsy?
Isn't it better to just leave it as: let hpts = rstyle.haystackPts ?

I agree.  That generally would be better so things would fail fast.  However, many of the dimensions functions are guarded -- primarily for headless mode.  At this point, it would be a less invasive change to make edge bound style read operations more guarded rather than making all of the other read operations less guarded.

I've made a change that makes the use of rendered style values generally stricter, in which there is a guard on the haystack points.  It's consistent, but I don't really like it personally.

That guard wouldn't really fix anything in @alessandro308's case.  It probably would just make things fail silently in his app, which is arguably worse.  Whether or not that failure would be significant or noticeable is an open question.

See #2546
