### ISSUE TITLE
Error on mouseover/out while changing bounds 

### ISSUE THREAD

**Issue by josejulio** [cytoscape/cytoscape.js#2535]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.10.0 
- Browser/Node.js & version : Version 73.0.3683.103 (Official Build) (64-bit)

**Current (buggy) behaviour**

The following exception appears in the log when having edges that change on mouseover/out
```
cytoscape.min.js:23 Uncaught TypeError: Cannot read property 'x1' of null
    at x (VM48 cytoscape.min.js:23)
    at m.findNearestElements (VM48 cytoscape.min.js:23)
    at m.findNearestElement (VM48 cytoscape.min.js:23)
    at VM48 cytoscape.min.js:23
```

**Desired behaviour**

No exception appears there

**Minimum steps to reproduce**

- Add a style selector for `edge` that has any `label` and `text-events` sets to `true`
- Add a style selector for `edge.mouseover` that has a different `label` value.
- Add a mouseover function on the edges that add the class `mouseover` to the edge.
- Add a mouseout function on the edges that removes the class `mouseover` off the edge.
- Move your mouse around the nodes and check your console, you should get these exceptions

Reproducer: https://output.jsbin.com/gimadatibu

![Peek 2019-09-24 16-59](https://user-images.githubusercontent.com/3845764/65553586-cd541a80-deec-11e9-9498-b1e8215dc585.gif)

**Comment by josejulio** [comment]
Note that this doesn't happen on `3.7.1`

**Comment by josejulio** [comment]
I was searching on what version it started happening:
It started on:
- 3.8.3
- 3.7.6

So probably related to this issue: https://github.com/cytoscape/cytoscape.js/issues/2480

**Comment by IfatChitin** [comment]
We are experiencing the same error, with mouseover/out nodes with labels and text-events:
https://output.jsbin.com/kafipexaku

**Comment by josejulio** [comment]
Thanks for the reproducer! Its more  or less the same but for nodes.

**Comment by maxkfranz** [comment]
If you use something like [licecap](https://www.cockos.com/licecap/) to make a GIF, please set 30fps or 60fps.  Otherwise, the video is not so smooth and it's difficult to see.

You should be careful of making any change on movement events, like mousemove or mouseover.  By changing the style, you may change the bounds.  When you change the bounds, you may change whether the cursor is inside without the user even moving the cursor.

With the exception resolved, you still get poor results like the following example:

![An example of a bad mouseover result](https://user-images.githubusercontent.com/989043/65724471-7716e100-e07e-11e9-8e06-08a04015efc7.gif)

That's not a result that a user would like to see, and on top of that it makes your app slow.

You should generally debounce or throttle movement event handlers.  Both demos can mutate the style at a faster rate than the generation of new frames.  You get a new frame every 16ms in the best case (60fps).  You can get a mousemove event, for instance, in 2ms.

**Comment by josejulio** [comment]
Thanks for the comments.
The example provided is only a minimum reproducer, the gif objective was only to show the exception when "moving around" the mouse.
In our application we don't drastically change the label like that :)
But i think the exception happens regardless if you actually change the label or not (see https://output.jsbin.com/kafipexaku)

**Comment by josejulio** [comment]
Here is an actual example of what we do:
![Peek 2019-09-26 16-39](https://user-images.githubusercontent.com/3845764/65727036-39b15400-e07c-11e9-91fc-34eeb909a613.gif)

**Comment by maxkfranz** [comment]
> But i think the exception happens regardless if you actually change the label or not

If you change the bounds, it's the same result.  It doesn't matter if the change in bounds came from the label or the border.

**Comment by maxkfranz** [comment]
> The example provided is only a minimum reproducer, the gif objective was only to show the exception when "moving around" the mouse.

Makes sense

**Comment by josejulio** [comment]
> You should generally debounce or throttle movement event handlers. Both demos can mutate the style at a faster rate than the generation of new frames. You get a new frame every 16ms in the best case (60fps). You can get a mousemove event, for instance, in 2ms.

I'll take this into account, thank you!
