### ISSUE TITLE
Option to change box selection behaviour

### ISSUE THREAD

**Issue by hegoczkigabor** [cytoscape/cytoscape.js#2560]
**Issue type**
Feature request

**Description of new feature**

I would like to use box selection, but now, If I select elements only partly with the box, the partly selected elements being to selected too, not only the fully contained ones. For example:

If I do this now, the parent box being to selected:

![sample_1](https://user-images.githubusercontent.com/11390877/67484009-6ea6cb80-f667-11e9-8f6b-08f4c5b44286.png)

But i would like to select it only in this case:

![sample_2](https://user-images.githubusercontent.com/11390877/67484012-6ea6cb80-f667-11e9-923b-fc6b474b074f.png)

**Motivation for new feature**

I would like to use box selection but I would like to select  only that elements which are fully contained by the selection box.

**Comment by maxkfranz** [comment]
I think that the core library should be simplified in future rather than complicating it with more options over time.

Most people expect the behaviour as it is now.  For some apps, it may make sense to have behaviour like you describe.

It should be possible to do what you're asking for without modifying the core library:  Simply toggle the selection mutability by `eles.unselectify()` when appropriate, and define how selection is carried out based whatever gestures and rules you want.  This could be packaged into a reusable extension.  Given that there is public API for bounding boxes and selection `box` events, it should be straightforward.
