### ISSUE TITLE
Interdependent endpoints

### ISSUE THREAD

**Issue by alihanokka** [cytoscape/cytoscape.js#2600]
**Issue type**
Bug report

**Environment info**
- Cytoscape.js version : latest
- Browser/Node.js & version : latest Chrome

**Current (buggy) behaviour**
I am currently writing a layout algorithm that extensively uses [edge endpoints](https://js.cytoscape.org/#style/edge-endpoints). When I specify values for both source and target endpoint of an edge then there is no problem. However, if only one of them is specified, I expect the other endpoint to continue its default `outside-to-node` rule. Meaning it should point towards the node’s center and gets placed on the outside of the node’s shape. But instead, it starts to point a bit off-center.

Here is a picture demonstrating the issue. I specified target endpoint of the edge going from n1 to n2 as `"target-endpoint": "30% 50%"`.
![Screenshot from 2020-01-08 16-03-21](https://user-images.githubusercontent.com/15351692/71980149-6e62a900-3230-11ea-8bd9-41489b2c3c5a.png)

**Desired behaviour**
It should look like this. I can workaround this issue using `"source-endpoint": "0 0"` but it looks bad when compound nodes are involved. 
![Screenshot from 2020-01-08 15-59-27](https://user-images.githubusercontent.com/15351692/71979904-ea102600-322f-11ea-910c-027e9838bc13.png)

**Minimum steps to reproduce**
[Here](https://codesandbox.io/s/nostalgic-dream-88h4e) is the code I wrote to demonstrate this bug.

**Comment by maxkfranz** [comment]
A straight edge should have the same result for `outside-to-node` and `outside-to-line`.  Those values can give different results only for edges that have intermediary points, such as a bezier with a control point.  See the following figure:

![71980149-6e62a900-3230-11ea-8bd9-41489b2c3c5a](https://user-images.githubusercontent.com/989043/72008197-4cadf580-3221-11ea-8bbd-bf838fde872f.png)

A bezier is annotated in cyan.  The cyan edge has an intermediary point --- the control point.  The endpoints for `outside-to-node` can be calculated by intersecting the node shape with a line from the centre point to the control point, indicated by the dashed lines.

Your edge is annotated in red.  The red edge has no intermediary point, so centre-centre line must be used.

I believe there is no concept of one endpoint depending on another endpoint in the library at this time, which is what your request implies.  I don't know offhand whether that would work well or whether it would cause problems.  In any case, it would have to be carefully considered and evaluated.  If added, that change would be part of a future feature release rather than a patch release.
