### ISSUE TITLE
text-align:center of parent div introduces an mouse/cursor offset

### ISSUE THREAD

**Issue by bc0n** [cytoscape/cytoscape.js#2626]
**Issue type**
Bug report

**Environment info**
- Cytoscape.js version : 3.13.0
- Browser/Node.js & version : FF 72.0.2, Node 6.13.6

**Current (buggy) behaviour**
If the parent div of the cytoscape container has text-align:center, the graph canvas is only shown on the right 50% of the container, and there is a 50% offset between the OS cursor and the graph's circular gray cursor.  Panning, zooming, and node dragging are correspondingly offset.

**Desired behaviour**
Cytoscape should not be affected by the parent div's centering.

**Minimum steps to reproduce**
https://jsbin.com/gozegohaqe/1/edit?html,css,js,output

The offset error appears when:
<body>
  <div style="text-align:center">
    <div id="cy"></div>
  </div>
</body>

If text-align is left, no offset is present.  Calling cy.resize() does not fix this error, contra https://js.cytoscape.org/#cy.resize .

Many thanks!

**Comment by maxkfranz** [comment]
I know that this is a frustrating issue, but this might not be possible to address universally within the library itself.

Ultimately, the author of an app is responsible for CSS and its effects, especially w.r.t. inherited properties like `text-align`.  However, there may be approaches to mitigate the effort required to address this issue.

Those approaches include things like web components and overrides like [`all`](https://developer.mozilla.org/en-US/docs/Web/CSS/all): [`initial`](https://developer.mozilla.org/en-US/docs/Web/CSS/initial).  The `all: initial` approach is more tractable, but it won't -- even if effective -- resolve the issue for all the browsers that this library supports.

Since you have an interest in this issue and you have an affected app, it would be helpful and appreciated if you would experiment with `all: initial` (or similar) and report back here.  Potentially, it could be used by the library itself to make things more convenient for app authors who only support modern browsers.

**Comment by bc0n** [comment]
Setting the Cytoscape div to `all: initial` does result in proper display.  I don't have an application demand for setting the Cytoscape div to `text-align: center` and so just changed the parent to `left`.  I struggled a bit to find the cause of the mouse/cursor offset and trusted Cytoscape to manage its tag/style/environment.  What does it take to add a sentence on the `text-align` requirement to the documentation?

**Comment by maxkfranz** [comment]
The documentation is specified in the docmaker.json file and the corresponding markdown files.  While text-align may be one example property to mention, there are many others that could have an effect.

Would you be open to making a pull request that applies `all: initial` within the library?  Since your app is affected, it would be a good test case.
