### ISSUE TITLE
remove/update a cytoscape.js style

### ISSUE THREAD

**Issue by canbax** [cytoscape/cytoscape.js#2637]
**Issue type**

Feature request

**Description of new feature**

we can add a style https://js.cytoscape.org/#cy.style Why we can't remove/update it? Here is my question in sof https://stackoverflow.com/q/59370556/3209523

**Motivation for new feature**

Logically, If I can add something, I should be able to **modify/remove** it. There are lots of use cases for the style. I want to change many styles dynamically with user input. e.g. change the color of a subset of nodes, change the color of edges, change font size etc... 

By using 
```
cy.style()
  // and then define new styles
  .selector('node')
      .style('background-color', 'magenta')
  // ...
  .update() // indicate the end of your new stylesheet so that it can be updated on elements
;
```
I can change how the elements look. But this continues adding more styles. I just want to modify the existing one. This actually causes some kind of memory leak.

update: I found a workaround. I get JSONrepresentation of the current style, update it and set style from modified JSON.
```
var json = cy.style().json();
// update the "json" object
cy.style().clear().fromJson(json).update();
```

**Comment by umdstu** [comment]
@canbax - I've done a lot of this as well, with success, only using the cytoscape.js API.
I think the first thing that would help you is using the `cy.css()` function, not `cy.style()`. It's discouraged because once you change the css, it loses the original style that css set, eg. colors, font sizes et.

What I ended up doing was creating classes for colors and shapes and sizes. From this the user can select from a fixed list of colors (10?), and a fixed set of font sizes. By adding and removing classes to supersede any of the original style properties, you retain the original style properties on the elements, but get the 'modified' styles while the classes are enabled.

Hope that makes sense. GL

**Comment by canbax** [comment]
@umdstu Thanks for the suggestion. But in my case, there are no fixed settings. I want to change them with user input.

**Comment by umdstu** [comment]
And you certainly can do that using the .style() / .css() function. I'm not sure where your problem lies.

Just update the nodes css() based on the user selection. Store the value in the data key for when you read the data back in later. 
The reason i stopped doing this, aside from it apparently being frowned upon, was because you will lose the original selectors style settings for whichever css value you're setting.

eg. If you define your initial stylesheet as `.selector('node').css({'border-color': #CCC});` and then later if you let the user change the border color to a node, you do node.target.css({'border-color': '#888'})

That node will have a border-color of `#888` and the other nodes will still have the `#CCC`. The problem with this is that you lose the original `#CCC` for that changed node. And for me that mattered because you then lose the `.selector('node:selected').` css values.

By using classes I am able to swap in styles without impacting the internal/initialized stylesheet. So you can do what you want, you just have to keep in mind you will lose those initial selector styles. It would be great if it did not, but that's not the case.

**Comment by canbax** [comment]
There is no visible problem if you don't itch the edge cases.

Firstly, there is a logical problem. Cytoscape.js let you add styles but not remove nor update them. If you let user/developer to add elements to a list, you should also let them remove.

Secondly, this situation is actually a memory leak. Cytoscape.js might consume too much memory in the long run if you keep adding more and more cytoscape.js styles.

![image](https://user-images.githubusercontent.com/8426741/76848329-8a984d00-6854-11ea-84be-0694f63b136f.png)

**Comment by maxkfranz** [comment]
The main thing you're intended to do with the stylesheet is to set it at initialisation or to replace it entirely at runtime.  If the API is confusing or you're trying to do something that it isn't designed for, then maybe parts of the API should be deprecated and removed.

I don't think anyone would try to add and remove selector blocks for an ordinary CSS stylesheet in an HTML document, so I'm doubtful that the analogue should be supported here.  I suspect the best solution would be to deprecate all of the `cy.style()` API and replace it with a setter `cy.style(stylesheetJson)`:  Additionally, only JSON would be supported via `cy.style()`; the functions would no longer be supported.

**Comment by umdstu** [comment]
I rely on the `.css()` function quite a lot, this would be terrible for me. Do you need use cases?

**Comment by maxkfranz** [comment]
cy.style().css() or ele.css() ?

**Comment by umdstu** [comment]
Ahh good catch. Yes the latter, ignore me!
