### ISSUE TITLE
Betweenness Centrality calculated for entire graph, not calling collection

### ISSUE THREAD

**Issue by yousefamar** [cytoscape/cytoscape.js#2650]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.14.0
- Browser/Node.js & version : 13.10.1

**Current (buggy) behaviour**

I have a completely connected graph. I select a subgraph of this that contains all nodes but different edges (e.g. `cy.elements('nodes, edges[weight < 50]')`. When I run the `betweennessCentrality` function (alias `bc`) on this subgraph collection, it calculates betweenness centrality for the whole graph, not respecting the collection.

**Desired behaviour**

I was expecting a similar outcome to if I were to run it on a clone of the graph without the elements outside the subgraph. I.e.

```js
cy = cytoscape({ elements: cy.elements('node, edge[weight > 50]').jsons() });
let bc = cy.elements().bc();
cy.nodes().map(bc.betweenness);
```

**Minimum steps to reproduce**

Go to whatever example on the main page (I use [grid layout](https://js.cytoscape.org/demos/grid-layout/)) and find the betweenness centralities of a collection without any edges whatsoever (theoretically it should give you all zeros).

```js
let bc = cy.nodes().bc();
cy.nodes().map(bc.betweenness);
```

It doesn't give you all zeros and acts as if we are considering the whole graph, unlike what the documentation suggests ("Considering only the elements in the calling collection, calculate the betweenness centrality of the nodes.").

Thanks.

**Comment by maxkfranz** [comment]
@ugurdogrusoz -- Hi Ugur, do you know whether the original author of the betweenness centrality implementation would be able to take a look at this?  Thanks

**Comment by ugurdogrusoz** [comment]
Is the original author somebody I know? I forget.

**Comment by yousefamar** [comment]
Could it be @ayhun? (see https://github.com/cytoscape/cytoscape.js/issues/1032#issuecomment-137411846)

**Comment by ayhun** [comment]
@yousefamar I am the person that originally implemented this (based on the paper:  "On Variants of Shortest-Path Betweenness Centrality and their Generic Computation" by Ulrik Brandes)

But it looks like @maxkfranz rewrote the code from scratch so there's nothing remaining from my original betweenness implementation. I would've liked to be helpful on this issue but it has been more than 5 years and I, unfortunately, don't remember anything about this algorithm or even the javascript language itself. I'm afraid I won't be able to help in this case.

**Comment by somedmguy** [comment]
I would expect the source of the problem is how the algorithm makes use of calls to [outgoers()](https://github.com/cytoscape/cytoscape.js/blob/40a1a8f1e9e9e086ff8f4e43fb122194a2252b1f/src/collection/algorithms/betweenness-centrality.js#L38) [openNeighborhood()](https://github.com/cytoscape/cytoscape.js/blob/40a1a8f1e9e9e086ff8f4e43fb122194a2252b1f/src/collection/algorithms/betweenness-centrality.js#L40) and [edgesTo()](https://github.com/cytoscape/cytoscape.js/blob/40a1a8f1e9e9e086ff8f4e43fb122194a2252b1f/src/collection/algorithms/betweenness-centrality.js#L81) [multiple](https://github.com/cytoscape/cytoscape.js/blob/40a1a8f1e9e9e086ff8f4e43fb122194a2252b1f/src/collection/algorithms/betweenness-centrality.js#L82) [times](https://github.com/cytoscape/cytoscape.js/blob/40a1a8f1e9e9e086ff8f4e43fb122194a2252b1f/src/collection/algorithms/betweenness-centrality.js#L84).  None of these is bounded by the source collection, so they all will reach out to the entire graph.

**Comment by maxkfranz** [comment]
The files have been moved around with the refactoring to support ES modules
with Rollup.  The source may look different in some ways, but it should be
mostly the same.  There may also have been some minor optimisations, but
I'm not sure offhand.  If the algorithm uses traversal functions like
`outgoers()`, then the resultant collections probably just have to be
intersected with the calling collection.  I'm not familiar with the inner
workings of the algorithm to be able to say whether that could produce
conflicts.

Does someone have test cases that could be used on subgraphs, other than
the zero case mentioned in the top post?

**Comment by maxkfranz** [comment]
I can add @somedmguy's suggested change, but I need someone to provide sample data for at least one subgraph test case.
