### ISSUE TITLE
Constant request for animation frames is killing battery life on mobile device

### ISSUE THREAD

**Issue by kawazoe** [cytoscape/cytoscape.js#2657]
**Issue type**
Bug report

**Environment info**

- Cytoscape.js version : 3.14.1
- Browser/Node.js & version : Chrome iOS (v80.0.3987.95)

**Current (buggy) behaviour**

The way the render loop is currently designed (aka polling instead of pushing), means that the library will execute javascript code every ~10ms and constantly allocates memory at ~166 KB/sec (as seen on screenshot). This keeps the CPU busy which prevents certain power saving features to trigger on mobile devices.

![repro-cytoscape-render - with - Google Chrome 3_30_2020 4_34_43 PM](https://user-images.githubusercontent.com/406575/77960125-bb8d6e80-72a5-11ea-8e2e-86fd175c4488.png)

This is a deal-breaker for me as I intend to use the library in a project that will be predominantly mobile with sparse interactions over a long period of time.

**Desired behaviour**

The library should only request an animation frame when a re-render is needed. This will move from polling to pushing renderings which would greatly help with idle states which would also greatly cleanup the flame-graph.

![repro-cytoscape-render - without -  Google Chrome 3_30_2020 4_36_18 PM](https://user-images.githubusercontent.com/406575/77960147-c942f400-72a5-11ea-93b3-4481a94ab2e2.png)
_(obviously this is running nothing as I have no way of running the render only once, but I would expect an idle graph to behave like an idle blank page)_

**Minimum steps to reproduce**

1) Clone this repository: https://github.com/kawazoe/repro-cytoscape-render
2) `npm install`
3) Comment/uncomment the code that creates the graph in index.html
4) `npm run serve`
5) Load the site in a browser and profile. You can also use the local ip address on your phone.

After 15 minutes of running this code on my phone, the battery drained 4% compared to the device draining <1% battery without the cytoscape graph in the page.

I set my phone auto-lock settings to "never" for the duration of the test and brightness to 50%. Both pages are predominantly white so OLED screens power savings should not impact power usage.

Included profile session on Chrome Desktop that matches the screenshots: 
[profile sessions.zip](https://github.com/cytoscape/cytoscape.js/files/4405379/profile.sessions.zip)

See #2656 for initial discussion.

**Comment by maxkfranz** [comment]
I tried to reproduce your results on one of the demos, and I compared the result to letting an ordinary page (e.g. Wall Street Journal or New York Times) sit idle.  There was no difference between the Cytoscape demo and the news article page.  Both cases used approximately 1% of battery life over 15 minutes.  Both an iPhone and an iPad had the same result.

It's difficult to come up with reliable benchmarks for things like this.  There are a lot of factors to consider, like what is happening in the background.  Usually battery life tests are most reliable on factory-reset devices used over many hours.  That's how reviewers and device makers come up with battery benchmark results.

To get a conclusive result, you also need an appropriate control.  I used an ordinary page, assuming that it's a good baseline comparison from an end-user's perspective.  If you use a completely empty page, you may be testing whether an empty page is better than any non-empty page.  Nevertheless, I got the same result comparing the empty page to the Cytoscape page.

I don't think that this is a high-priority issue for the following reasons:

- The issue is not reproducible on my devices.
- The use of `requestAnimationFrame()` is standard and the browser should generally be optimised for it.
- Most mobile users use their devices only for a few minutes at a time, so most users for most apps wouldn't be affected by this issue -- even if it were reproducible.
- Changes to the `requestAnimationFrame()` cycle may impact rendering performance.  The browser is pretty good at spacing out animation frames when the graph is very large to keep the frame rate consistent, even if it drops below 60 fps.  Further, the renderer has caches that can be optimistically filled in during idle frames.
- Changes to the `requestAnimationFrame()` cycle may impact animations.

Nonetheless, you're welcome to make a PR if you think it would improve the library for your use case.  However, I'd like to see that the library isn't negatively affected for general rendering performance, animations, etc.
