### ISSUE TITLE
Use browser-friendly module links

### ISSUE THREAD

**Issue by SamuraiJack** [cytoscape/cytoscape.js#2661]
Hello,

As modern browsers supports ES modules now, the good practice will be to use so called "isomorphic" code, that runs equally well in browser and in node. For that one would need to use relative urls for modules everywhere, instead of "absolute" ones:

For example, instead of (from the `cytoscape.esm.js`)
```js
import util from 'lodash.debounce';
import Heap from 'heap';
```
would be better to write:
```js
import util from './node_modules/lodash/src/debounce'; // sample link
import Heap from './node_modules/heap/index.js'; // sample link
```

This removes the need for the webpack step during development.

Please consider this style for the future development.

Thanks, Nickolay

**Comment by maxkfranz** [comment]
That's an interesting idea.

Using full path names (e.g. `./node_modules/lodash/src/debounce`) rather than the name of the package (e.g. `lodash.debounce`) may be brittle.  A dependency could move files around between releases.  Is there a way to mitigate this?

This project uses livereload for the debug page.  When any source file changes, the page reloads.  Is there a similar tool that works with ES modules?

We also have to consider testability with older browsers, without support for ES modules.  That means we won't be able to remove webpack completely, even if it's not necessary for testing in modern browsers.

**Comment by SamuraiJack** [comment]
> Using full path names (e.g. ./node_modules/lodash/src/debounce) rather than the name of the package (e.g. lodash.debounce) may be brittle. A dependency could move files around between releases. Is there a way to mitigate this?

No, unfortunately for now, one would need to track all urls manually. There's a proposal to support "absolute" urls for Ecma modules, but its still at early stage.

>This project uses livereload for the debug page. When any source file changes, the page reloads. Is there a similar tool that works with ES modules?

There's no such feature. Where would it live? Everything becomes native - just files and browser, like in old good pre-webpack days. I think the removal of webpacking step and hassle free code reuse between browsers and node outweighs the need to hit `F5`

>We also have to consider testability with older browsers, without support for ES modules. That means we won't be able to remove webpack completely, even if it's not necessary for testing in modern browsers.

This would still require webpacking. However under older browsers you mean IE probably, which only exists in unsupported and outdated versions of Windows. It is approaching irrelevance very soon.

Well, I don't insist on any immediate changes, just bringing the "new style" to your attention. Please keep in mind what is possible when planning the future releases. 

Thanks for your project, very useful tool!

**Comment by maxkfranz** [comment]
I agree that IE will continue to decrease in usage over time, but there is still a considerable number of people who use it (people who use internal enterprise systems, people in China, etc.).  It may make sense to drop support for legacy browsers in v4, and people who need to support IE could continue to use v3.  I've added this to a list of potential breaking changes for v4 in #2019.

> There's no such feature. Where would it live? Everything becomes native - just files and browser, like in old good pre-webpack days. I think the removal of webpacking step and hassle free code reuse between browsers and node outweighs the need to hit F5

I was mistaken about issues around Livereload.  It should work fine.

> No, unfortunately for now, one would need to track all urls manually. There's a proposal to support "absolute" urls for Ecma modules, but its still at early stage.

Would you please link to the proposal here so that it can be referenced and tracked?

**Comment by SamuraiJack** [comment]
Regarding IE - yes, that sounds like a good plan. At some point we'll have to stop optimize for the past and start optimizing for the future. IE users should be absolutely fine using previous version.

According to https://github.com/guybedford/es-module-shims the "absolute path" for modules (also called "bare path" or "import path") is already implemented behind the flag in Chrome 76! Didn't know that, thats good news.

There's also: https://github.com/WICG/import-maps
