### ISSUE TITLE
can parent node support other shape?

### ISSUE THREAD

**Issue by everhopingandwaiting** [cytoscape/cytoscape.js#2677]
```js

      selector: 'node:parent',
      style: {
        'background-color': 'lightgrey',
        shape: 'star',
        'border-color': 'cyan',
        'border-radius': '50',
        'background-fill': 'radial-gradient'

      }
```
![image](https://user-images.githubusercontent.com/6021724/80606823-53c67100-8a67-11ea-8463-181853d71362.png)

**Comment by cheblin** [comment]
[shape : The shape of the node’s body. Note that each shape fits within the specified width and ](https://js.cytoscape.org/#style/node-body)height, and so you may have to adjust width and height if you desire an equilateral shape (i.e. width !== height for several equilateral shapes). Only *rectangle shapes are supported by compounds, because the dimensions of a compound are defined by the bounding box of the children. The following values are accepted:
ellipse
triangle
round-triangle
rectangle
round-rectangle
bottom-round-rectangle
cut-rectangle
barrel
rhomboid
diamond
round-diamond
pentagon
round-pentagon
hexagon
round-hexagon
concave-hexagon
heptagon
round-heptagon
octagon
round-octagon
star
tag
round-tag
vee
polygon (custom polygon specified via shape-polygon-points).
shape-polygon-points : An array (or a space-separated string) of numbers ranging on [-1, 1], representing alternating x and y values (i.e. x1 y1 x2 y2, x3 y3 ...). This represents the points in the polygon for the node’s shape. The bounding box of the node is given by (-1, -1), (1, -1), (1, 1), (-1, 1). The node’s position is the origin (0, 0).

**Comment by maxkfranz** [comment]
In future, please [post questions to Stack Overflow](http://stackoverflow.com/questions/ask?tags=cytoscape.js,javascript).  

- The issue tracker is for feature requests and bug reports.
- There is a large community of users on Stack Overflow who may want to help you with your code.  
- Core contributors to Cytoscape.js have limited time to spend on the project overall, and that time must be spent mostly on code maintenance and updates.
- Stack Overflow answers tend to come up in Google searches better than closed GitHub issues, so it benefits other developers with similar questions.

Please follow the [Stack Overflow guidelines](https://stackoverflow.com/help/how-to-ask) to be considerate of the community and to improve the chances of receiving a good answer.
