### ISSUE TITLE
Logging event.target freezes the window

### ISSUE THREAD

**Issue by jsphstls** [cytoscape/cytoscape.js#2682]
**Issue type**
Bug report

**Environment info**

- Cytoscape.js version : 3.15.0
- Browser/Node.js & version : Chrome 81, codesandbox

**Current (buggy) behaviour**

Logging the `event.target` to the console will freeze the browser window.

**Desired behaviour**

This should not freeze the browser window.

**Minimum steps to reproduce**

https://codesandbox.io/s/cytoscape-event-target-9elmn

**Comment by maxkfranz** [comment]
This seems like it only affects codesandbox.io, so I suspect that problem lies there.

**Comment by jsphstls** [comment]
True, I do not get the freeze locally, though I do see that the target contains a self-reference:
![image](https://user-images.githubusercontent.com/4481784/82354858-a340f280-99be-11ea-9c13-68153719d370.png)

That could be the part that codesandbox cannot handle.

**Comment by maxkfranz** [comment]
It sounds like that site has a serialisation problem. I don’t see those references going away as long as collections can be used with indices and the [ ] operator.  An element has the same API as a collection so that the distinction is invisible to consumers of the lib: An element is the same as a collection of size one.
