### ISSUE TITLE
flickering rendering graph on chrome mac os x

### ISSUE THREAD

**Issue by canbax** [cytoscape/cytoscape.js#2709]
**core library**

Bug report

**Environment info**

- Cytoscape.js version: 3.15.0:
- Browser: Google Chrome on MacOS, Google Chrome 81.0.4044.138 (Official Build) (64-bit), macOS catalina 10.15.5. It does not happen in Safari browser.

**Current (buggy) behaviour**
I'm adding more elements to the graph and running layout. After some level rendering disappears.
![render bug](https://user-images.githubusercontent.com/8426741/84470372-e58ee400-ac8b-11ea-9f92-2a2a8ea8974a.gif)

rendering disappears after a certain zoom level

**Desired behaviour**
render graph always

**Minimum steps to reproduce**

**Comment by maxkfranz** [comment]
If this is a Chrome-only issue, then it’s almost certainly a bug in Chrome.  Over the past few years, Chrome has become a bit buggier than the other browsers for canvas and WebGL.  Usually these issues are resolved by the Chromium team after a release or two.  So the options I see at this point are to just wait it out or to file a report in the Chromium issue tracker.  If you opt to file a bug report, I expect that they would like to see a more minimal reproducible test case — without Cytoscape.

**Comment by gregroyal** [comment]
Our team gets this same issue with chrome and firefox. We haven't upgraded in a long time though (currently on 3.1.5). After upgrading to current (3.15.2) we saw this issue. After meticulously checking, we noticed it going from v3.2.22 to v3.3.0 is where the issue started happening for us. I'm not sure if its only related to the browser since an older version of cytoscape still has no flickering with modern browsers. Here's the diff https://github.com/cytoscape/cytoscape.js/compare/v3.2.22...v3.3.0
@maxkfranz do you know if there was a change in between those version that might have kicked off this issue?

**Comment by gregroyal** [comment]
I think for our issue, we've pinpointed it down to our stylesheet styling nodes dynamically by the data. 
We have 2 issues from what we can tell. Labels get offset sometimes and the nodes disappear / get offset other times.


For example:

```
[{
    'selector': 'node',
    'css': {
      'content': 'data(title)'
    }
},
{
    'selector': 'node[?iconUrl]',
    'css': {
      'background-image': 'data(iconUrl)',
      'background-fit': 'contain'
    }
}]
```

The labels don't get messed up often, but they still break after zooming / running a bunch of layouts

When the graph is in a broken state, if we re-run the stylesheet without these lines the nodes show up again. And right after If i return it back to the original stylesheet, they disappear again

@maxkfranz are those methods of styling data still supported?

**Comment by gregroyal** [comment]
Ok i found it. For us the issue was the cache validation was incorrect. If i commented out the cache check, and it generates the styles at every zoom every time. It works great!

https://github.com/cytoscape/cytoscape.js/blob/7a27717f223c3c954b85db683c224ae14f4c8c4f/dist/cytoscape.umd.js#L28113

**Comment by maxkfranz** [comment]
> this also seems to be the lower down reason, is the texture is retired, but maybe never property re-added?

Could the element be hanging on to an old reference after the retirement?

**Comment by maxkfranz** [comment]
Reopening for visibility

**Comment by gregroyal** [comment]
Thanks! Sorry we haven't investigated this any further yet.

**Comment by maxkfranz** [comment]
An alternative to tracking down a potential reference issue may be to defer retirement until the texture is completely unused, rather than when mostly unused. It certainly would not be an ideal solution, but it may be more tractable — and it may be sufficient for now. 

When you have time to investigate, that alternative may be worth exploring.

**Comment by janhartmann** [comment]
Some of my users of an applications is also reporting that labels are messed up, too small and out of place. I have a feeling this could be related to this issue also. Have anyone looked further into this?
