### ISSUE TITLE
cy.png with {full: true} does not work

### ISSUE THREAD

**Issue by alejoar** [cytoscape/cytoscape.js#2711]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.15.0
- Browser/Node.js & version : Chrome 83.0.4103.97

**Current (buggy) behaviour**

In certain node configurations, when calling `cy.png({full: true})` all I get is `"data:,"`

**Desired behaviour**

I should be getting the png data, i.e. `"data:image/png;base64, (...)"`

**Minimum steps to reproduce**

I managed to extract a minimum example from the data I am using (I used `.json`). Check this jsbin example, where the issue happens with just three nodes. There's a `console.log` at the end to show the result of `cy.png`.

https://jsbin.com/bimoxur/1/edit?js,console,output

Note that modifying the `_size` value of any nodes seems to fix the issue, so I'm guessing there are certain combinations that break the functionality.

**Comment by maxkfranz** [comment]
See 

- https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/canvas#Maximum_canvas_size

 > If the height or width of the canvas is 0 or larger than the maximum canvas size, the string "data:," is returned.

If you have ideas on how to address this issue, you're welcome to make a pull request.

**Comment by alejoar** [comment]
I believe the correct solution to this involves detecting the browser and then use `cy.elements().boundingBox().w` and `cy.elements().boundingBox().h`(or actually filter to visible ones) to calculate the correct scaling factor to use in order to be able to generate an image.

However, doing some quick testing, I didn't get to make sense out of the numbers I am getting when compared to the numbers shown in the links you shared. I didn't really go deep into it though.

My solution right now is to set `maxWidth` and  `maxHeight` to 16384, which seems to address my specific issue.

Thank you @maxkfranz for pointing this out.

**Comment by maxkfranz** [comment]
Generally it’s best to avoid browser testing, especially when the affected behaviour of the browser can change over time.  Feature testing is the best practice, but that’s probably not possible here.  Documenting the the internals of `cy.png()` isn’t a great option either, since consumers shouldn’t really know about the internal rendering implementation.

Since setting the max width and height to 16384 worked for you, maybe the most tractable solution is to set 16384 as the default for both max width and max height.  That doesn’t make things perfect, but it may make things easier for most people most of the time.

Would you be open to making a PR for that change?  It would be great to include it in a patch release.

**Comment by alejoar** [comment]
@maxkfranz I'm not sure that's the optimal solution. This needs a bit of experimenting. For example, would a rectangular shape where the width exceeds 16384 pixels with a smaller height work?

I will try to experiment a bit but can't promise I'll do it since I don't have much free time.
