### ISSUE TITLE
Border is cutting the background image when using bounds-expansion

### ISSUE THREAD

**Issue by janhartmann** [cytoscape/cytoscape.js#2726]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.15.2
- Browser/Node.js & version : Chrome, NodeJS 12.18.2

**Current (buggy) behaviour**

When using the ` "background-clip": "none", "bounds-expansion": n` together with a border, the background image will be cut with border. 

![image](https://user-images.githubusercontent.com/1107383/87400807-56e2ef00-c5ca-11ea-9aa2-c5afef98b230.png)

**Desired behaviour**

I would like to control whether or not the border should be cutting the background image or controlling the z-index of the background image.

**Minimum steps to reproduce**

Create a node style with the following:
```{
        selector: "node",
        style: {
          shape: "round-rectangle",
          "background-opacity": 1,
          "background-width": "30",
          "background-height": "30",
          "background-position-x": "-10",
          "background-position-y": "-10",
          "background-clip": "none",
          "bounds-expansion": 20,
          "border-width": 1,
          width: 50,
          height: 50,
        },
      }
```

**Comment by maxkfranz** [comment]
IIRC, we just use a traditional draw order:

(1) First, the background shape fill
(2) The background images
(3) The border
(4) The label

(I might be missing some other layers in that list, but those ones come immediately to mind.)

If (2) and (3) were swapped, that could conflict with other use cases -- e.g. when you want to apply clipping.  Since this existing draw order is expected behaviour, do you foresee a potential new feature that could address your issue?

**Comment by janhartmann** [comment]
I can follow why this order is applied and I was wondering if this is actually a new feature or a bug report.

If it is a new feature, maybe it could be a “background-z-index”, but that is naturally supported by the drawing order of the background images.

Maybe a “bounds-expansion-clip“: “background border”. 

Just some thoughs.

**Comment by maxkfranz** [comment]
> If it is a new feature, maybe it could be a “background-z-index”, but that is naturally supported by the drawing order of the background images.

I agree that z-index may be too complicated, since there are existing z-index properties and background images are a different scope.  It may be confusing.

> Maybe a “bounds-expansion-clip“: “background border”.

I think a qualitative enum property like this would be more appropriate.  Since it's not strictly to do with clipping, what about something like `background-image-containment: inside | over`?  Today's behaviour would be `inside` (between node body and node border).  It sounds like what you're describing would be `over` (on top of the node body and node border).
