### ISSUE TITLE
SVG Background Image 

### ISSUE THREAD

**Issue by pdugas** [cytoscape/cytoscape.js#2750]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : current master https://rawgit.com/cytoscape/cytoscape.js/master/dist/cytoscape.min.js
- Browser/Node.js & version : Google Chrome Version 85.0.4183.102 (Official Build) (64-bit)

**Current (buggy) behaviour**

An SVG background image for a node is getting scaled unexpectedly when zooming in and out. I found an existing example at  <https://jsbin.com/wuzukogemu/6> when I was searching for a solution. Zooming in via two-finger touch illustrates the issue clearly - slowly spread the touches and the image scale will start out constant then jump. Zooming via mouse scroll-wheel _jumps_ immediately for me too.

**Desired behavior**

The background image should be scaled smoothly as the node is scaled

**Minimum steps to reproduce**

* Visit https://jsbin.com/wuzukogemu/6
* Zoom in the Output panel

**Comment by pdugas** [comment]
Clarifying... When I two-finger-touch zoom in on the Output panel in the example, the circular nodes expand smoothly while the SVG icon remains constant until it *jumps* to a larger scale at some point. If I continue to zoom in, it *jumps* again. Screenshots below. 

![2020-09-22_12-35](https://user-images.githubusercontent.com/710928/93911418-5bb1d680-fcd0-11ea-997b-168aea162efb.png)
![2020-09-22_12-36](https://user-images.githubusercontent.com/710928/93911433-5f455d80-fcd0-11ea-9843-a7e9eb55bb64.png)
![2020-09-22_12-36_1](https://user-images.githubusercontent.com/710928/93911442-62404e00-fcd0-11ea-9bd5-7e7b0386ce8c.png)

**Comment by pdugas** [comment]
Related... the position and scale of SVG background images appears to be hosed in general for me. Everything works as expected, including this scale issue, when I switch from using an SVG to a PNG. This doesn't appear to be something new.

https://stackoverflow.com/questions/46036677/cytoscape-js-node-background-image-issue

**Comment by maxkfranz** [comment]
Have you read the ['SVG image considerations' notes](https://js.cytoscape.org/#style/background-image)?  The image dimensions need to be well defined.  You probably won't be able to use something exported from Graphic or Inkscape without manually modifying some of the properties.

**Comment by pdugas** [comment]
I have now but I confess I'm not following all of the points there. The SVG used in that example is at https://cdn.rawgit.com/energiekollektiv/saiv/dev/images/icons/demand.svg. At first glance, I appears to comply with those points but the point about memonize isn't clear to me. Is that what you're referring to when you suggest image dimensions need to be well defined?

**Comment by maxkfranz** [comment]
No, that would be for programmatically-generated SVGs (i.e. `function(ele) : SvgUriString`).  There are several ways to specify the dimensions of an SVG within the SVG markup.  To complicate things further, different browsers determine the overall dimensions differently.  Your image, for example, works in Safari but neither in Firefox nor in Chrome.

The [SBGN stylesheet](https://github.com/PathwayCommons/cytoscape-sbgn-stylesheet) by @d2fong is a good example of using SVG.  Dylan spent a lot of time working around SVG issues to make sure that the shapes in that stylesheet worked well in different browsers.  It's a bit simpler if you're not generating SVGs on the fly, like that stylesheet.

It's been many years since SVG was introduced into the browser, and it is still error-prone and finicky.  Ultimately, you have to decide whether the benefits of SVG outweigh the costs of handling the obscure problems it brings.

**Comment by pdugas** [comment]
I appreciate the explanation, Max. I leaned into using SVGs to avoid scaling issues of rasters and to allow me to color them on the fly for _status_ indications but the hassle of doing so here and with marker icons in Google Maps has changed my mind. It's easy enough to pre-generate rasters of the necessary sizes and colors so I think I'll go that route and avoid banging my head against this particular wall.  Thanks again.
