### ISSUE TITLE
Webkit browsers render very large canvases

### ISSUE THREAD

**Issue by domenicrosati** [cytoscape/cytoscape.js#2753]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.15.2
- Browser/Node.js & version : safari 

**Current (buggy) behaviour**

Without limiting the container size of the visualization, canvases are rended very large. On the visualizations we have: https://scite.ai/visualizations/global-analysis-of-genome-transcriptome-9L4dJr?dois[0]=10.1038%2Fmsb.2012.40&dois[1]=10.7554%2Felife.05068&focusedElement=10.7554%2Felife.05068

Three canvases are rendered that are >100mb each and the resolution size is something like 2000px * 4000px

This causes safari  and ios to  crash on our visualizations.

It can be resolved if you limit the max height/width of  the container.

**Desired behaviour**

I would expect similar behaviour to chrome where the canvases are rended according to the current browser height / width. And the canvases are in the general range similar to chrome (about 2.2mb each on desktop)

**Minimum steps to reproduce**

Render some large visualization on safari. Look at the canvas sizes.
 

I realize that I have resolved the issue for myself by setting the container. However those canvases are still large like 17mb (maybe this is chrome optimizations IDK). 

At the very least, If there was a way to communicate what users had to do for webkit support in the docs that would be desired.

**Comment by maxkfranz** [comment]
Note that you have to consider screen pixels, not CSS pixels.  CSS pixels will tell you what an old-fashioned, low-density screen would have to render.  A modern, high-density display will use many more pixels.

You can control the pixel density of the visualisation, at a cost to quality.  Otherwise, there isn't much that can be done -- other than documentation updates, as you've mentioned.

I'm not aware of what these specific limitations are, so I'd encourage you to post your research here.  If you have specific suggestions on how to improve the documentation, you're welcome to make those directly in a pull request to the md files.

**Comment by maxkfranz** [comment]
@domenicrosati, have you found any factors that seem to affect your issue?  I haven't seen this problem on iPads or iPhones that I've used.

**Comment by domenicrosati** [comment]
@maxkfranz  - I didn't look into it too much further after I found that explicitly limiting the width and height  on the containing element increased performance dramatically on webkit devices. You are welcome to close this issue  if you don't think there is anything to do further / docs that might be good to add. Thanks for the advice.
