### ISSUE TITLE
Distinguish between user and layout zoom/pan

### ISSUE THREAD

**Issue by janhartmann** [cytoscape/cytoscape.js#2756]
**Description of new feature**

I would like to distinguish between a layout zoom/pan and a user zoom/pan. 

**Motivation for new feature**

As a default behaviour in my application, I want to fit everything to the screen using the layout `fit: true`. 

However, if the user wants to explore the graph closer, I want to change the layout options to `fit: false`, in order for the user to be in control. The reason for this is that my layout runs everytime new data is coming in to the graph and when the user is in control the graph should not fit again.

This switch should only happen on the user initiated zoom/pan, however with the current event handlers for `zoom` and `pan`, I cannot distinguish whether it was the user or the layout.

**Comment by maxkfranz** [comment]
What about the addition of events like these?

- pinchzoom
- scrollzoom
- dragpan

Those kinds of events kill two birds with one stone:  You can tell that they're user generated, and you can also tell exactly what kind of gesture originated a viewport change.

I think that this would just involve adding extra `emit()`s nearby the existing `emit()` calls in the renderer and updating the docs.  Would you be interested in making a PR for events like these?

**Comment by maxkfranz** [comment]
I suppose a caveat would be that some browsers, like Chrome, translate pinch gestures on the Mac touchpad into wheel events.  So the scrollzoom event may come up unexpectedly when you pinch on Mac.

**Comment by maxkfranz** [comment]
@janhartmann, do you think events like those would suffice for your use case?  Would you be open to making a PR and testing the feature addition in your app to confirm that it's sufficient?

**Comment by janhartmann** [comment]
Yes they would and maybe it is time for me to get a feeling for the codebase as well. Let me get back to this next week. :-)

**Comment by maxkfranz** [comment]
Most of the source is organised in the same hierarchy as the documentation, so it should be fairly straightforward to find things.  The main thing that isn't documented is the renderer, since that is abstracted away for the consumer.  

There's a `BaseRenderer` that contains everything that isn't specific to a particular rendering technology (e.g. canvas, webgl, svg).  There is a `CanvasRenderer` that subclasses the `BaseRenderer` with canvas-specific drawing methods.

The `BaseRenderer` has all the gesture code.  You can see that here: https://github.com/cytoscape/cytoscape.js/blob/e45bdf8889441b990d75ecd8259ade2e480bb1be/src/extensions/renderer/base/load-listeners.js

I suppose you'd just be emitting the new events (e.g. pinchzoom) alongside the existing ones (e.g. zoom).

**Comment by charles-stuart-appdetex** [comment]
I'm trying to track whether or not a graph is dirty based on whether or not the user has interacted with it, and I'm having the same issue where I want to be able to watch for pan events and they're being emitted by Cytoscape when the graph initially renders and as well by the user as they move the graph.

**Comment by maxkfranz** [comment]
If you're interested in this feature, PRs are always welcome!  I've outlined some of the details in a previous comment

**Comment by charles-stuart-appdetex** [comment]
I'll try and take a look next week. Thanks for the details.
