### ISSUE TITLE
Hardware Supported Renderer

### ISSUE THREAD

**Issue by KonradHoeffner** [cytoscape/cytoscape.js#2798]
**Description of new feature**
A new renderer should improve performance using hardware-supported rendering, such as OpenGL/WebGL, instead of canvas.

**Motivation for new feature**
With 2643 nodes and 4903 edges, I get around 5 FPS in Firefox Developer Edition 85.0b4 (64-bit) on a 4k screen when scrolling on an Intel i7-9700 and 16 GB RAM.

Seeing that one of my cores is up to 100% utilized, it seems to me as if the rendering is being done using the CPU and not the GPU. Given that GPUs, even internal ones, are specialized for this task, I expect this to bring a large performance benefit.

**Comment by maxkfranz** [comment]
I'll add some notes here, because this has been considered before:

(1) This can help with complicated nodes.  Blitting a node texture with WebGL is a bit faster than with canvas.  This can work with the existing texture caches and the existing canvas renderer.

(2) WebGL doesn't help that much with edges if you want high quality figures.  You can get cheaper edges with WebGL, but it's typically at the cost of having jaggy, aliased lines.

(3) It is possible to create a WebGL-only renderer by creating a new renderer class.  You could get better speed, but there's a drop in quality and a large increase in complexity in order to support all the Cytoscape style properties.  @keiono has created a prototype renderer, but it's not hooked up to the Cytoscape API at all.  You could get in touch with Kei if you're interested in making that prototype a production-ready Cytoscape renderer.

**Comment by manju-reddys** [comment]
I think it is possible with [Pixijs](https://www.pixijs.com/), their WebGL api is compatible with canvas.

**Comment by tonxxd** [comment]
Any news about this?

**Comment by ExtReMLapin** [comment]
https://github.com/cytoscape/cytoscape.js/tree/feature/gpu

**Comment by mikekucera** [comment]
Currently working on this full time.

**Comment by KonradHoeffner** [comment]
> Currently working on this full time.

If your work includes a publication and you need a reference to motivate why such a renderer is useful, you can cite our newly published paper about SNIK Graph at <https://doi.org/10.21105/jose.00180>, which writes about a hardware supported renderer in the future work section.
