### ISSUE TITLE
Support Multithreading

### ISSUE THREAD

**Issue by KonradHoeffner** [cytoscape/cytoscape.js#2799]
**Description of new feature**
Cytoscape.js should support multithreading, either using web workers or some other mechanism, such as WebAssembly.

**Motivation for new feature**
Modern midrange CPUs usually have between 6 to 12 cores and between 12 to 24 threads.
However only one core/thread seems to be used by Cytoscape.js, impacting the performance.
For example, with 2643 nodes and 4903 edges, recalculating the layout using Euler takes around 14 seconds on Firefox Developer Edition 85.0b4 (64-bit) on an Intel i7-9700 with 16 GB RAM.

Even considering the overhead of synchronization and so on, I would expect CPU-bound performance to massively increase when using all of the cores.

**Comment by maxkfranz** [comment]
This is a great idea, and it would be an excellent addition once browsers have good support for multithreading with ordinary JS code. 

In the browsers today, a web worker has separate memory, like a process.  That means that you have large serialisation and deserialisation costs in order to facilitate inter-worker communication.  That overhead negates the benefits you might get for a typical JS project.

The only current efficient way to use web workers is to use typed arrays to store all your data.  That means you can't really use JS objects (e.g. classes), and so you can't really use web workers well in most JS projects.

It would be interesting to use something like Rust/WASM for Cytoscape v4.  I encourage anyone who's interested in that idea to either drop a line here or in [the discussions](https://github.com/cytoscape/cytoscape.js/discussions).

**Comment by dahnny012** [comment]
Is there way to write the code multithreaded in such a way that we can run it on a node process on a server?

**Comment by maxkfranz** [comment]
Great suggestion, @nickchomey.  It’s worth exploring.

**Comment by maxkfranz** [comment]
Even if it is possible with the tool you mentioned, it would only facilitate the process to some degree.  It would be a major undertaking in any case.

Anyone who’s interested in this idea is welcome to use this issue to scope it out.
