### ISSUE TITLE
Nodes become non-interactive after being hidden by visibility property and shown again

### ISSUE THREAD

**Issue by darress** [cytoscape/cytoscape.js#2815]
**Environment info**

- Cytoscape.js version : 3.18.0
- Browser/Node.js & version : Chrome Version 88.0.4324.104, Node v10.14.2

**Current (buggy) behaviour**

Visible/interactive nodes cannot be grabbed, because renderer.cachedZSortedEles.interactive is not valid

**Desired behaviour**

All visible and interactive nodes should be grabbed

**Minimum steps to reproduce**

Unfortunately I have no time for a repro project, and our project is pretty big, but we do the following:

We set the "display" data property of some edges to "none".
We set the "visibility" data property of nodes with no edges to "hidden".
The data properties are bound to the same properties in stylesheet.

When we restore all display and visibility values, when the cachedZSortedEles.interactive are calculated, the width and height properties of the nodes are 0, so they get excluded from the cachedZSortedEles.interactive array and cannot be grabbed.

If I set renderer.cachedZSortedEles to null after resetting the properties, grabbing will work again.

**Comment by maxkfranz** [comment]
This isn't reproducible on the demo page:

```js
cy.$('#a').style('visibility', 'hidden');
cy.$('#a').style('visibility', 'visible');
```

Please provide a reproducible test case, including:

- Browser version
- OS version
- A code sample that reproduces the issue.  [A JSBin](http://jsbin.com/fiqugiq) can be forked to easily provide a code sample.

It's important to provide a reproducible demo.  Without that, it's not practical to verify that there is indeed a bug in the library -- or whether there is a bug in the library consumer's app.  It's easy and quick to create a demo using JSBin if you have a reproducible issue.

More often than not, issue reports without a demo are due to bugs in the consumer's code.  So unfortunately, it's not a good use of our limited resources to spend time investigating which which issue reports are genuine.

As soon as you provide a reproducible demo, this can be investigated further.  Thanks for your feedback

**Comment by darress** [comment]
Thank you for your detailed answer!

Unfortunately it's also not a very good use of resources for us to create a reproduction project, because we already have a workaround in place.

Also thank you for creating this awesome framework!
