### ISSUE TITLE
getPointAtLength

### ISSUE THREAD

**Issue by brucenguyen1** [cytoscape/cytoscape.js#2824]
Add a function to calculate get point at an edge length where the input is the percentage of the length. This is similar to SVG getPointAtLength, cytoscape.js can do it as it manages the drawing of different edge types based on canvas drawing functions.
This feature would be useful for calculating progress flow animation along the edges.

**Comment by maxkfranz** [comment]
It's nontrivial to get true distances along curves for beziers, especially when you have several distinct beziers in series.  The simple cases are a single straight line or a single bezier, with a t value on [0, 1].  If an absolute distance is specified or if the edges are more complex, then things get much more complex and expensive.

It's simpler and more performant to make these calculations in your own app, where you can leverage assumptions that would not hold true in the general-purpose library in order to simplify things.

If you're interested in the general case, I encourage you to make [an extension](https://js.cytoscape.org/#extensions).  Once you're satisfied that the extension handles all the cases in a general way, it could be considered for merging into the main lib in a PR.

Thanks for your feedback
