### ISSUE TITLE
Labels are blurred, misaligned and sometimes missing

### ISSUE THREAD

**Issue by janhartmann** [cytoscape/cytoscape.js#2828]
**Environment info**

- Cytoscape.js version : 3.18.0
- Browser/Node.js & version : Chrome 88.0.4324.192 (Official Build) (x86_64)

**Current (buggy) behaviour**

I have been receiving reports of the graph I am rendering is sometimes not showing the right labels at their right positions and sometimes blurred or missing completely. If the user does a refresh the graph is rendered fine again. I am unable to reproduce this issue on my own setup. Screenshot of the rendering:

![image](https://user-images.githubusercontent.com/1107383/109955417-e6751380-7cfb-11eb-988b-8d034bf7bbac.png)

They also sometimes see the edge's labels on the node body or labels on nodes where they dont belong.

I have a strong indication it can be related to https://github.com/cytoscape/cytoscape.js/issues/2290 and/or https://github.com/cytoscape/cytoscape.js/issues/2709.

**Desired behaviour**

Rendering the graph without misalignment, blurred or missing labels.

**Minimum steps to reproduce**

Unfortunately not able to reproduce myself, however I will update if I am able to.

**Comment by janhartmann** [comment]
You mean, instead of setting:

```js
 if( eleCache && eleCache.invalidated ){ 
   eleCache.invalidated = false; 
   eleCache.texture.invalidatedWidth -= eleCache.width; 
 } 
```

We change this to

```js
 if( eleCache && eleCache.invalidated ){ 
   eleCache = null;
 } 
```

Or did I misunderstand?

**Comment by Alexandr23** [comment]
Hi! I am suffering from almost the same problem.

Sometime labels are not being rendered properly. It can be a missing label, partially rendered label or other texts.

I tried to delve deeper into the texture caching mechanism, but have not yet found the cause of the problem. It looks as if the cache is taken with the correct dimensions, since the lengths of the labels are the same as expected, but coordinates or texture or  level is wrong.

The problem has never been reproduced locally, but it often appears among our users.

Can you tell me in which direction it is better to go deeper?

**Comment by Alexandr23** [comment]
Hi @maxkfranz @janhartmann, 
I managed to create an environment where the issue is predictably reproducible. After a few days of investigation I found a problem with retired textures.

The thing is that you can retire the same texture multiple times and have more than one copy of the same texture object in the  `RetiredTextureQueue`. Later when you recycle the texture you will have it in both queues - `TextureQueue` and `RetiredTextureQueue`. it means that some caches will be pointing to areas of the texture that are overwritten already.

What we need to do is to remove all copies of the texture from the queue.

Could you please review my pull request? https://github.com/cytoscape/cytoscape.js/pull/2845

**Comment by janhartmann** [comment]
Hi Max, I work together with Alexandr so we verified it worked on our application.

**Comment by maxkfranz** [comment]
> Hi Max, I work together with Alexandr so we verified it worked on our application.

Great

**Comment by maxkfranz** [comment]
@Alexandr23, @janhartmann 

This was released yesterday.  Been busy but wanted to get it out.

Thanks again for the PR, and good luck with your project

**Comment by janhartmann** [comment]
Thanks a lot @maxkfranz, take care :-)
