### ISSUE TITLE
Add support for ICO format 

### ISSUE THREAD

**Issue by amrrizq** [cytoscape/cytoscape.js#2839]
When adding background image to node, the current supported image formats are PNG, JPG, and SVG (stated in https://js.cytoscape.org/#style/background-image). We wish that ICO format could be added to the previous three formats. I'm using cytoscape.js in a project that needs to grab FAVICON from the websites, to visualize relations between different websites. although some websites uses PNG and support multiple formats, the ICO is still used in some websites.
So, it'll be very nice to add this feature to cytoscape.js.

**Comment by maxkfranz** [comment]
Since you're interested in this feature, you're welcome to make a pull request with the implementation for your feature.  Take a look at our [contributing file](https://github.com/cytoscape/cytoscape.js/blob/unstable/.github/CONTRIBUTING.md) for instructions on how to get started with your pull request.

**Comment by youssefeldakar** [comment]
Would be interested in implementing it. @maxkfranz would it be possible to point out the relevant part in the code tree to work on? Thanks.

**Comment by maxkfranz** [comment]
You can start by making a standalone ICO loader that can write its output to canvas or preferably a base 64 PNG file.  Once you have that, we can discuss if and how that could be integrated.
