### ISSUE TITLE
cy not making deep copies

### ISSUE THREAD

**Issue by canbax** [cytoscape/cytoscape.js#2841]
**Environment info**

- Cytoscape.js version : 3.2.0
- Browser/Node.js & version :^

**Current (buggy) behaviour**

Cytoscape.js invades my own objects. The passed objects are all passed by reference and they are being changed in cytoscape.js To prevent my objects from being changed, they should be passed as a deep copy. I don't know if this is intended. Maybe better for performance but it causes weird situations for me. 

**Desired behaviour**
Cytoscape.js to not change my own JS objects. I think it should make its own deep copies.

Here is a link to jsbin. https://jsbin.com/xuvuxub/edit?html,css,js,console,output

In the code you can see that I'm passing an object named `elems`. The first node in the `elems` is `{ data: { id: 'cat', name:'asd' } }`

From cytoscape.js I'm changing the value of the property named `name` to `yoo`. The value of my own object is also changing.
You can see it on the console logs.

I also see the same behavior with methods like `cy.json()`

**Comment by maxkfranz** [comment]
It sounds like you've solved your issue.  Have you noticed [this part of the documentation](https://js.cytoscape.org/#notation/object-ownership), or did you sort things out on your own?  If not, then you're welcome to suggest further clarifications to the documentation in a PR so that the documentation's clarity is to your satisfaction.

**Comment by canbax** [comment]
I think the documentation is clear. I understand that such a thing is good for performance.
