### ISSUE TITLE
SVG Export

### ISSUE THREAD

**Issue by apowers313** [cytoscape/cytoscape.js#2923]
**Description of new feature**
Same as https://github.com/cytoscape/cytoscape.js/issues/1944 and https://github.com/nrnb/GoogleSummerOfCode/issues/61:
Create an API similar to [cy.png](https://js.cytoscape.org/#cy.png) that exports graphs in a SVG format.

**Motivation for new feature**
Existing PNG and JPG formats lose semantics of the original image, lack resolution scalability, and are difficult to manipulate individual elements.

Would you accept a pull request for this feature? If so, any tips on where to get started?

**Comment by maxkfranz** [comment]
This ought to be an extension, and it would be easier for you to build it that way anyway.

As long as your team puts together a top-level function that returns the SVG, it should be easy to package your code as an extension.  The existing public API should have enough style information in order to build up the SVG, especially with the edge point functions: https://js.cytoscape.org/#collection/edge-points

Start by making an export function that includes 20px-by-20px black nodes for all nodes and black 1px straight lines for all edges.  Then progressively add support for more and more style properties.

**Comment by hasanbalci** [comment]
There is an extension for svg export [here](https://www.npmjs.com/package/cytoscape-svg). @apowers313 You may give it a try.
