### ISSUE TITLE
Remove file heap.js

### ISSUE THREAD

**Issue by cnoelle** [cytoscape/cytoscape.js#2934]
In the repo and the distribution there is a file [src/heap.js](https://github.com/cytoscape/cytoscape.js/blob/unstable/src/heap.js), which consists of a single line 

```javascript
export { default } from 'heap';
```

The `'heap'` here probably refers to the dependency *heap*, but it may also be interpreted as the source file itself, which then leads to an  error: too much recursion. I had this issue with a current webpack, typescript and ESM modules in the browser, and it might be the same bug reported before:
https://github.com/cytoscape/cytoscape.js/issues/2570
https://github.com/cytoscape/cytoscape.js/issues/1952

For me removing the file altogether solved the issue, another option could be to rename it to avoid the naming conflict.

**Comment by maxkfranz** [comment]
Here's another avenue you can investigate:  When you're consuming Cytoscape, you're actually using one of the [built, dist files](https://github.com/cytoscape/cytoscape.js/tree/unstable/dist).  Bundlers, like Webpack, select the one referenced in package.json.  That leads me to believe that there's something else at play.

Feel free to investigate further and post your results here

**Comment by maxkfranz** [comment]
If we were to change the file structure of the library, as you suggest, how are we to know that the true cause of the issue has been resolved?  How can we be certain that the same issue will not crop up again?

You’re welcome to make a PR for your proposed change.  Before it is merged in, I would like to see some cursory root cause analysis, likely starting with a minimal reproducible example.  If your issue is with Webpack, an issue report should also be filed with Webpack so that it can be properly resolved.  A general Webpack issue likely affects more people than just Cytoscape users, so we ought to try to get things sorted out there.

**Comment by tsvetan-ganev** [comment]
@maxkfranz, I consider this a breaking change. I upgraded from version 3.19.0 to 3.21.0 and my build started failing - I didn't change neither my TypeScript version nor the `tsconfig.json` files. Nobody expects a minor version to break their build. I don't see how what @cnoelle proposes is any worse than introducing a breaking change to all TypeScript users.

Since this is a widely used library and TypeScript has become mainstream, the integration between the two must be seamless. Are you interested in me creating some integration tests that make sure Cytoscape.js and TypeScript continue working with each other (at least in the most basic configuration) + adding instructions how to integrate the two somewhere to the README?

**Comment by maxkfranz** [comment]
> @maxkfranz, I consider this a breaking change. I upgraded from version 3.19.0 to 3.21.0 and my build started failing - I didn't change neither my TypeScript version nor the `tsconfig.json` files. Nobody expects a minor version to break their build. I don't see how what @cnoelle proposes is any worse than introducing a breaking change to all TypeScript users.

I don't think anything re. the build process changed from 3.19 to 3.21, so there may be a quirk in tsc.  Lots of packages on npm use Rollup.  We don't build using tsc, so the only feedback re. TS that can come in is user feedback in the issue tracker.

The tsc compiler may handle dependencies in a unique way.  We have several types of supported builds (e.g. esm.min.js if you don't want to have your project's compiler handle dependencies).  The build variations are outlined [in the docs](https://js.cytoscape.org/#getting-started/including-cytoscape.js).

Any potential mitigations should have some root cause analysis or at least automated tests (ideally both).

> 
> Since this is a widely used library and TypeScript has become mainstream, the integration between the two must be seamless. Are you interested in me creating some integration tests that make sure Cytoscape.js and TypeScript continue working with each other (at least in the most basic configuration) + adding instructions how to integrate the two somewhere to the README?

Sounds good
