### ISSUE TITLE
Function to remove nodes overlap

### ISSUE THREAD

**Issue by davidecrs** [cytoscape/cytoscape.js#2994]
**Description of new feature**
It would be useful if there was a function to simply remove the overlap of nodes without running the layout.
For example https://ialab.it.monash.edu/webcola/examples/nonoverlapping.html

**Motivation for new feature**
Layouts generally produce good results; however, sometimes it may happen that some nodes overlap each other. Therefore, it would be useful to have a function (for a button) able to remove the overlap of the nodes while maintaining the calculated positions, without performing further iterations of the layout (producing significantly changes in the positions of the nodes).

**Comment by maxkfranz** [comment]
Great idea

That sounds like an interesting feature.  Since you mentioned it’s a part/feature of the Cola layout, you’re welcome to make a PR on the Cola extension to make that feature easier to access.  Alternatively, you could add a demo for the feature in the Cola extension, if it’s already easy enough to carry out that feature with the existing API
