### ISSUE TITLE
Bg + Animate

### ISSUE THREAD

**Issue by rac021** [cytoscape/cytoscape.js#3087]
Hi, 

I have a node with a specific bg.

Doing

```
node.data().bg = color ;

```
works fine.

But when I call the **animate** function like 

```
 node.animate({
        style: { 'background-color': 'red'  }
 }).delay( 100 ).animate({
    style: { 'background-color': node.data().bg }
  })
```
**node.data().bg = color**  stop working

Can anyone tells me what's wrong with my code ?

Thank's

**Comment by maxkfranz** [comment]
It looks like you're having trouble with your code.  

In future, please [post questions requesting help to Stack Overflow](http://stackoverflow.com/questions/ask?tags=cytoscape.js,javascript) or the [discussions section](https://github.com/cytoscape/cytoscape.js/discussions).  

- It's not scaleable or sustainable to provide free, custom-tailored support to every consumer of Cytoscape.js.
- The issue tracker is only for feature requests and bug reports.
- There is a large community of users who may want to help you in the discussions section or on Stack Overflow.  
- Stack Overflow answers tend to come up in Google searches better than closed GitHub issues, so it benefits other developers with similar questions.

Follow the [Stack Overflow guidelines](https://stackoverflow.com/help/how-to-ask) to be considerate of the community and to improve the chances of receiving a good answer.  Those guidelines are also fitting for GitHub Discussions, if you opt for that.

If you do find a reproducible bug, you're welcome to post a bug report here.  Include all the information according to the issue template so that the issue can be addresses effectively.
