### ISSUE TITLE
Get Access to cytoscape Canvas Directly Through cytoscape API

### ISSUE THREAD

**Issue by source-transformer** [cytoscape/cytoscape.js#3094]
**Description of new feature**

The following extension exists:
https://www.npmjs.com/package/cytoscape-canvas

But it is five years old and doesn't work in a typescript environment (i.e. missing types decl's).  

I also found this more up to date package:
https://www.npmjs.com/package/cytoscape-canvas

But, this relies on the author of this package keeping it up to date with cytoscape updates.

**Motivation for new feature**

Generating a background and/or overlay in SVG or Canvas shouldn't require an external package/extension/plugin.

**For reviewers**

_Reviewers should ensure that the following tasks are carried out for incorporated issues:_

- [ ] Ensure that the reporter has adequately described their idea.  If not, elicit more information about the use case.  You should iteratively build a spec together.
- [ ] Ensure that the issue is a good fit for the core library.  Some things are best done in extensions (e.g. UI-related features that aren't style-related).  Some things are best done by app authors themselves -- instead of in Cytoscape libraries.
- [ ] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [ ] The commits have been incorporated into the `unstable` branch via pull request.  The corresponding pull request is cross-referenced.

**Comment by maxkfranz** [comment]
`cytoscape-canvas` is a great extension, and it's being used in production for children's educational software.  Its [demo](https://github.com/classcraft/cytoscape.js-canvas#demo), as is typical for extension demos, links to the latest version of Cytoscape so you can easily confirm that it works with the latest version core library.

> But, this relies on the author of this package keeping it up to date with cytoscape updates.

That's one of the reasons why Cytoscape conservatively follows semver, as libraries should.  An extension author ought not to need to update anything, unless the library releases a major, breaking version (e.g. v4).  We don't frequently make breaking/major semver releases, fashionable as that may be for web tech.

If you find the extension's community [type definition](https://www.npmjs.com/package/@types/cytoscape-canvas) not to your liking, then you're welcome to suggest and make updates at [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).  You're also free to make your own extension in TypeScript, if you prefer.  Those are some of the benefits of open source.

> Generating a background and/or overlay in SVG or Canvas shouldn't require an external package/extension/plugin.

The underlying rendering technology of the core library is not, and should not be, exposed to consumers.  The tech used for rendering can change over time, and it has.  We're free to make those improvements precisely because it's not exposed to consumers.

Thanks for your feedback, and all the best with your project.

**Comment by source-transformer** [comment]
Not allowing users to write to the same canvas as cytoscape makes sense - as the underlying cytoscape code needs to be able to clear the rendering area (canvas or whatever) at any given moment.

I can create a follow up question (in a different git issue) - instead continuing to post to this "new feature request" git issue.  But, after integrating cytoscape-canvas and writing to my dynamically generated canvas behind cytoscape's canvas I've run into two issues:

1. cytoscape's position/coordinates seem to be relative/offset to some unknown factor (padding, fit, offset, etc).  Specifically, if I set a node to origin (0,0) - it doesn't get rendered in the top left.  I have an example where I'm rendering a hex-grid to my dynamic canvas and where you can see the hex centered at 25,30 doesn't align with the node centered at 25,30.  

I found this post:
https://community.plotly.com/t/cytoscape-node-position-not-working/66647

I tried changing the layout settings on my cytoscape canvas - but this didn't fixed the issue (the following going thru the ngx-cytoscape interface):

```
const elementsDef: ElementsDefinition = { nodes: [], edges: [] }
const cytoscapeOptions: CytoscapeOptions = { elements: elementsDef };
cytoscapeOptions.style = style;
const presetLayout: PresetLayoutOptions = { name: 'preset', fit: false };
cytoscapeOptions.layout = presetLayout;
```

screenshot:
<img width="76" alt="image" src="https://user-images.githubusercontent.com/50280003/213609291-57ee2666-886c-40ac-a4d4-9f98910b1395.png">


2. The second question has to do with moving a node in cytoscape.  When I move a node - it ends up dragging (panning) my hex grid that I render to the dynamically generated canvas by the cytoscape-canvas extension.  Is there a way to move nodes without panning the canvas beneath?


Thanks!

**Comment by source-transformer** [comment]
I just tried the same test circumventing ngx-cytoscape and using cytoscape directly (in my angular app) and the issue doesn't occur.  I think the bug in their package is here:

```
  private render(options: CytoscapeOptions): void {
    if (options) {
      this.core = cytoscape({ ...options, container: this.cyElementRef.nativeElement });
      this.core.fit();
      this.coreChanged.emit(this.core);
    }
  }
```

Specifically, the render code always calls "this.core.fit()" regardless of whether the layout has been set to:

```
{ name: 'preset', fit: false }
```

I'll see if I can get a repro for that package's owners.
