### ISSUE TITLE
crash NS_ERROR_FAILURE with Firefox

### ISSUE THREAD

**Issue by solyane2002** [cytoscape/cytoscape.js#3136]
**Environment info**
- Cytoscape.js version : 3.23.0
- Browser/Node.js & version : FireFox For Fedora v112.0.1 (64-bit) Fedora - 1.0

**Current (buggy) behaviour**
Load a cyjs file
=> graph is visible
click on it to move or zoom 
=> crash
NS_ERROR_FAILURE exception 

The error is located in cytoscapejs source code, in the function makeLayers, line 28022
![image](https://github.com/cytoscape/cytoscape.js/assets/53021239/6c986e02-9523-4077-8843-bb4643c8dd70)

Tested on Chrome => no crash 
Version 114.0.5735.198 (Official Build) (64-bit)

**Desired behaviour**

No Crash on Firefox neither

**Minimum steps to reproduce**
This is quite tricky to reproduce as on my side the crash occurs only with one file, but I don't know what is the pain point in the file and I can't share it (confidential). The file is quite big (>800 ko) but I have other bigger files without the issue.

I report the issue just in case someone else has the same error, may be we can share and investigate further.
May be it can be helpful to know that it is specific to Firefox.

**Comment by maxkfranz** [comment]
Are you getting this 'cyjs' file from the [Cytoscape desktop app](https://cytoscape.org)?

**Comment by solyane2002** [comment]
nope, the file comes from networkX

**Comment by maxkfranz** [comment]
> nope, the file comes from networkX:
https://networkx.org/documentation/stable/reference/readwrite/generated/networkx.readwrite.json_graph.cytoscape_data.html#cytoscape-data

OK, so it's [an ordinary JSON file then](https://js.cytoscape.org/#notation/elements-json).

> May be it can be helpful to know that it is specific to Firefox.

This doesn't affect any other browsers with the same dataset?  Assuming that's true, I've tagged this issue so others can find it and add comments.

Normally, it may be helpful to post a dataset that reproduces this.  However, if this is really Firefox-only, then it's probably not addressable on the Cytoscape side.  On the other hand, a reproducible dataset would be useful to post on [Bugzilla](https://bugzilla.mozilla.org/home) so that the Firefox team could look into the issue on their side.

Would you be open to posting an anonymised version of your dataset?

**Comment by solyane2002** [comment]
Thank you for your feedback.
Unfortunately, the bug is really unstable: now I can't reproduce on Firefox neither. Same file, same version.
May be it is related to a specific context (memory, tabs opened,... ?)
The specificity of my is just the size, 900k.
I will close the ticket for now and reopen if I have some news.

**Comment by maxkfranz** [comment]
OK, thanks @solyane2002
