### ISSUE TITLE
Recursion error thown when trying to add lots of edges with bezier curve style

### ISSUE THREAD

**Issue by ngkahinkeith** [cytoscape/cytoscape.js#3299]
**Environment info**

- Cytoscape.js version : v3.30.3
- Browser/Node.js & version : Chrome 131.0.6778.70, Firefox 115.10.0esr & Firefox 131.0

**Current (buggy) behaviour**
I know this is not a general use case on cytoscape, but when trying to insert a lot of edges into graph from A to B, cytoscape throws error and unable to create the graph

Error on Chrome
![Screenshot 2024-11-13 162409](https://github.com/user-attachments/assets/8a507648-272e-4ad4-9f59-470e54f55e92)

Error on Firefox
![Screenshot 2024-11-13 162447](https://github.com/user-attachments/assets/7045c45c-075d-4411-a85f-a19060de35bb)

**Desired behaviour**
There should be no error and the graph can be created (ignoring performance issue)

**Minimum steps to reproduce**
https://jsbin.com/wavofokobu/1/edit?css,js,output

or

```js
var cy = cytoscape({
  container: document.getElementById('cy'),
  
  style: cytoscape.stylesheet()
    
    .selector('edge')
      .style({
        'curve-style': 'bezier'
      }),
}); // cy init
  
// simulate user add/insert data in later time after cytoscape has been inited
cy.add([
    { data: { id: 'n1' }, position: { x: 50, y: 50} },
    { data: { id: 'n2' }, position: { x: 50, y: 500} },
  ])
  

cy.startBatch();
cy.add(Array.from(Array(600)).map((_, i) => ({
     data: { source: 'n1', target: 'n2' } ,
  })))
cy.endBatch();
```

**For reviewers**

_Reviewers should ensure that the following tasks are carried out for incorporated issues:_

- [ ] Ensure that the reporter has included a reproducible demo.  They can easily fork this JSBin demo: http://jsbin.com/fiqugiq
- [ ] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [ ] The commits have been incorporated into the corresponding branches.  Bug-fix patches go on
    - [ ] `master`,
    - [ ] `unstable`, and
    - [ ] the previous feature release branch (e.g. `1.1.x` if the current release is 1.2).
- [ ] The issue has been labelled as a [`bug`](https://github.com/cytoscape/cytoscape.js/labels/bug), if necessary.

**Comment by mikekucera** [comment]
Hi @maxkfranz, I would like to get your opinion on this.

This is what I think is happening... When the style is first applied it sets each 'curve-style' to 'bezier'. When the first edge is set to 'bezier' it calls checkBoundsTrigger() which then loops over all parallel edges calling isBundledBezier() on each. 

https://github.com/cytoscape/cytoscape.js/blob/unstable/src/style/apply.js#L823-L827

The calls to isBundledBezier() call cleanStyle() which recurses back into applyStyle() which causes checkBoundsTrigger() to loop over all parallel edges again. If there's a lot of parallel edges (eg 600-700) this will overflow the stack. But even with fewer edges isBundledBezier() gets called n^2 times (I think). 

I'm not sure what the best way to fix this is. But one option could be to simply remove the call to isBundledBezier() and just dirty the bounding box cache of all parallel edges regardless of what type of edge it is. This removes the recursion caused by calling isBundledBezier(). If 'curve-style' never changes after initialization then I don't think it matters much. If it does then I'm not sure if checking if the edges are bezier helps performance since it causes so many recursive calls, it might be fine to just dirty all BB caches of all parallel edges. What do you think?

**Comment by maxkfranz** [comment]
This looks like some previous optimisation that's turned into a regression.

Let's just go with your simple approach.  The curve-style is already checked here, so the inner check is probably redundant apart from perhaps some weird edge cases:

https://github.com/cytoscape/cytoscape.js/blob/f5afa6d0ed133bc5c0bd594434119b4df43b5074/src/style/apply.js#L819-L822

So this if could just be removed so it's unconditional like you suggested:

https://github.com/cytoscape/cytoscape.js/blob/f5afa6d0ed133bc5c0bd594434119b4df43b5074/src/style/apply.js#L824-L826

The lib has lots of micro-optimisations, because JS used to be much slower in browsers.  In future, we should probably just remove these as needed since the gains in JS browser performance over the years and our move to WebGL will be much larger in impact.
