### ISSUE TITLE
Support for specifying arbitrary bezier control points for edges

### ISSUE THREAD

**Issue by stanleygu** [cytoscape/cytoscape.js#394]
In order to have more customizable graph layouts

**Comment by Sigfried** [comment]
I'm running into this same problem, as described at http://stackoverflow.com/questions/41638266/how-to-use-bezier-curves-in-cytoscape-js. I wanted to make edges that avoid passing through nodes like:

![pretty_links](https://cloud.githubusercontent.com/assets/1586931/21940968/9dd45f8c-d994-11e6-80d7-21aa52a3b82a.png)

Since I couldn't figure out how to add control points (and I'm not sure where I'd put them anyway), I added waypoints that I want curves to pass through. The result is pretty awful:

![ugly_edges](https://cloud.githubusercontent.com/assets/1586931/21940937/786d71b6-d994-11e6-9791-c6c1a1f252b1.png)

Is there a another way to accomplish the same end?

**Comment by maxkfranz** [comment]
See http://stackoverflow.com/a/41646675/947225
