### ISSUE TITLE
Support string stylesheets

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#396]
In addition to the JSON format used for specifying stylesheets, allow for string stylesheets formatted like CSS.

e.g.

```
node {
  height: 10
}
```

becomes

```
{
  'selector': 'node',
  'css': {
    'height': 10
  }
}
```

etc.

See https://github.com/aschriner/cytoscapejs-css-style

**Comment by ignorabilis** [comment]
The mentioned reason for the missing hover is not actually true. Not all touch devices are missing the hover option - in fact several high end devices do have such an option when using a stylus. Just because  most of the touch devices are missing this functionality it doesn't mean that all devices should be punished for that. 

It's the developers job to know that their product might end in an environment that does not support hover and do something about that.

**Comment by maxkfranz** [comment]
If a dev wants to use hover, he can write a few lines and use a class instead of a state selector.  There's nothing preventing you from using hover if you want.

I can see where you're going with your argument, but I think it's actually the opposite: Just because a subset of devices support something, we shouldn't punish all the remaining devices by depriving them of features by default.

In desktop-only projects, hover may be OK.  For other projects, hover is not sufficient.  That means that you need to handle touch in some analogous way for your particular app, or it means you need to handle the entire feature in a consistent, device agnostic way without hover at all.  Most commonly, devs will do neither if `:hover` is available to them -- leaving touch devices without a feature.

More often than not, the second option is superior because it offers uniformity.  For the first option, I think it's better to have the dev write a few lines so he can consider touch support as well.  Using custom events, those few lines also allow him to generalise a gesture on top of hover for desktop and some other action on touch.
