### ISSUE TITLE
pointer offset in scrollable div

### ISSUE THREAD

**Issue by kzuberi** [cytoscape/cytoscape.js#514]
Experimenting with putting a cytoscape.js widget within an [ipython notebook](http://ipython.org/notebook.html), seems to work but having trouble with the mouse pointer. The notebook places the cytoscape container within a scrollable div, and scrolling messes up the container position/offset calculation. 

I've tried to make a stripped down example without any python bits here: http://jsbin.com/josuxi/1 

To work around the issue I change findContainerPageCoords() to simply use getBoundingClientRect() - would this be a viable change for cytoscape.js or is there a reason the coordinates aren't already calculated this way?

Likely related to #190.

**Comment by AaronWatters** [comment]
I'm seeing this problem in Cytoscape.js 2.4.8.  Is there a patch?
I'm also using IPython notebooks.  
The symptom is that the network responds correctly to mouse events until I move the containing scroll bar.  After that the events are responding to the wrong position.
If you want to see this in action go to http://mybinder.org/repo/simonsfoundation/jp_gene_viz and then navigate to the I-Python notebook at "examples/cytoscape demo.ipynb".

**Comment by maxkfranz** [comment]
The code for this hasn't changed and I have confirmed it working locally.

Cytoscape.js can only detect if a scroll happens in a parent div.  If the event is killed somehow, there's nothing it can do.  If you can detect the scroll yourself and call `cy.resize()` each time, it should act as a workaround.  If not, you'll have to file an issue with IPython notebooks -- as the issue seems to be on their side.

**Comment by AaronWatters** [comment]
The problem is that the network has finished initializing before the DOM element is positioned in the document tree.  For this reason the containing divs are not all updated with the `onscroll` event.  Here is a work around for my Jupyter/IPython notebook widget:

https://github.com/simonsfoundation/jp_gene_viz/commit/b5aa536edc32ceda7bdb1c2f8c8943fc73458fba#diff-2a0de7348fa9ad6d5ebde063aa952462R36

It would be nice to add some sort of `cy.fix()` functionality to fix up the `onscroll` events after initializations to support applications that do sophisticated DOM manipulation like this.

**Comment by kzuberi** [comment]
For what its worth it seemed to work okay for me after Max's fix. My half baked implementation is [here](https://github.com/kzuberi/ipython-cytoscape.js) though by now i've forgotten most of how it worked.

**Comment by AaronWatters** [comment]
Thanks @kzuberi.  I read and learned from your code.  I didn't get it to work with the latest version of Jupyter, but that may be my fault.  I think the widget framework has changed pretty significantly recently.  The scrolling was definitely an issue before the patch mentioned above.

**Comment by maxkfranz** [comment]
@AaronWatters `cy.resize()` is automatically called if any ancestor DOM element is scrolled.  If you move the cy div around in the DOM, then that won't work.  If you want to move things around, your options are:

(1) Use CSS instead.  Changing the DOM hierarchy shouldn't be necessary for visual changes.

(2) Create your instance in its final location.

(3) Create a new instance each time you move the DOM elements.

(4) Call `cy.resize()` when your app encounters a `scroll` event.

If you want things to be automatic, then don't move things in the DOM.  If you really want to move things around in the DOM, you'll have to handle things manually via (3) or (4).

**Comment by AaronWatters** [comment]
@maxkfranz -- I will request that Jupyter inform plugin widgets when they are (re)positioned in the DOM.  If they implement this then I can simply postpone the "real" initialization until after the object is positioned.  I still think it would be nice to have an official interface to allow cytoscape.js client code to say "please fix up the event callbacks on all ancestor containers" (unless it already exists and I missed it).

I'm not sure why the Jupyter widget interface creates objects first and then positions them later, but I'm assuming there may be a good reason for it.  Thanks!

**Comment by maxkfranz** [comment]
@AaronWatters Having an additional interface wouldn't help, because you'd need to call it at that time after the DOM element is repositioned in the tree.  If you don't know when that is, you can't call the function at the right time.  And if you do know when that is, you may as well just init at that time.

Unfortunately, it's not possible with current web APIs to do all of this in an automatic way that's also performant without knowing exactly how a dev's app is structured.  It's the same case for other UI libs like Leaflet: http://leafletjs.com/reference.html#map-invalidatesize

I've improved the docs re. `cy.resize()` and moving the tree around.  Thanks for the feedback
