### ISSUE TITLE
Export to SVG extension

### ISSUE THREAD

**Issue by acardona** [cytoscape/cytoscape.js#639]
Write an extension that builds up svg objects based on the computed style of each of the elements and returns a root svg element.

*Using an automatic canvas-to-svg library will not work.*

Original content follows:
## 

Would be wonderful to be able to export to SVG, completing this fantastic library that is cytoscapejs. Is an export to SVG perhaps in the roadmap?

**Comment by DSin52** [comment]
I noticed that in the recent versions, an option for JPG export has been added in.  Is there any hope that an SVG option will also get implemented soon considering this issue was created several months ago?

**Comment by maxkfranz** [comment]
Unfortunately, it would be a very large undertaking and I'm not sure whether it will fit into the next release -- given the extensive changes needed in the renderer.  It also would double maintenance costs of the renderer for little pragmatic benefit over high-res PNGs.

You could use @tomka's method and indeed his change to disable `Path2D` for export could make it into a minor, patch release to make things more straightforward.

If you're interested in native support in the renderer sooner, I can review a PR that covers the changes I've mentioned earlier.

**Comment by miskar** [comment]
Is it possible to have an example code that uses the SVGcanvas approach as developed by acardona and tomka? I am a rookie in javascript and had difficulty in implementing the svg export functionality. Thanks a lot in advance.

**Comment by tomka** [comment]
Hi @miskar, the commit linked right before my last comment in this issue contains the changes needed to make it work (at least for us). You basically need to do the following:

    // Create a new SVGKit SVG canvas of desired size, it will be used to render from Cytoscape.
    var svg = new SVGCanvas(width, height);
    
    // Cytoscape uses Path2D if it is available. Unfortunately, SVGKit isn't able
    // to make use of this as well and silently fails to draw paths. We therefore
    // have to monkey-patch Cytoscape to not use Path2D by overriding its test.
    // We reset to the original function after the graph has been rendered.
    var CanvasRenderer = cytoscape('renderer', 'canvas');
    var orignalUsePaths = CanvasRenderer.usePaths;
    CanvasRenderer.usePaths = function() { return false; };

    // Assuming your cytoscape instance is available as 'cy', render it to the SVG canvas
    // created earlier.
    cy.renderer().renderTo( svg, 1.0, {x: 0, y: 0}, 1.0 ); 
    
    // Reset Path2D test of Cytoscape
    CanvasRenderer.usePaths = orignalUsePaths;

**Comment by sepro** [comment]
I've tried the solution from @tomka , but ran into an error with setTransform (which isn't implemented in SVGKit as mentioned by @unidesigner). How did you get around this?

**Comment by maxkfranz** [comment]
I've tried `SVGCanvas` and it works only in very, very simple cases.  It's not a reliable solution...

**Comment by eelco2k** [comment]
I'm also getting some error's when trying to convert canvas to svg with canvas2svg.js 

`canvas2svg.js:515 Error: Invalid value for <path> attribute d="L 54.1865707939973 -189.17190648836421 L 60.196982187342144 -196.81961561481185 L 50.47256805017713 -197.03931925361914"`

So i added this piece of code to make sure a path always starts with an "M". on line 515 of canvas2svg.js

d=d.replace(/^L/, 'M');

i'm using Canvas 2 Svg v1.0.6

**Comment by jelmerjellema** [comment]
When I use canvs2svg I do not get errors. The first tests however give me a svg that is filled with PNG objects for each node (our nodes have SVG backgrounds). Is cytoscapeJS rendering background SVG as PNG? In that case there is no use for exporting to SVG, because it will always contain bitmaps. 

This is my code, which does not yet deliver a good SVG anyway.

`   var ctx = new C2S(1000,1000);
                modelctrl.cy().renderer().renderTo( ctx, 0, 0, 1 );
                var mySerializedSVG = ctx.getSerializedSvg();`

**Comment by tomka** [comment]
Yeah we noticed the same. Cytoscape caches previously rendered elements as images. We had some success with overriding the caches during SVG export so that cache look-ups would always fail, which in turn causes the actual drawing routines to be called. However, this also didn't allow previous hack to work completely due to some problems with SVGCanvas.

Since we only need to export relatively simple nodes and edges and their labels, we wrote our own SVG exporter in the end:

https://github.com/catmaid/CATMAID/blob/dev/django/applications/catmaid/static/libs/catmaid/svg-factory.js

On the calling side, all Cytoscape nodes and edges are walked and rendered one by one. Luckily Cytoscape caches some rendering information, so we barely need to do any math ourselves (for now):

https://github.com/catmaid/CATMAID/blob/dev/django/applications/catmaid/static/js/widgets/compartment_graph_widget.js#L2364

Depending on how complex your graph is and the features you use, a similar approach might work for you.

**Comment by maxkfranz** [comment]
https://github.com/nrnb/GoogleSummerOfCode/issues/61

This project will use a similar approach with new calculated rendered values in 3.1:

https://github.com/cytoscape/cytoscape.js/issues/1552

https://github.com/cytoscape/cytoscape.js/issues/1551

The GSOC project (if accepted) will give a good initial version of a SVG export extension.  It will probably support all rendering features in 3.1.  For core versions beyond that, the extension will probably require community PRs for new rendering features added to the core.

**Comment by tfjmp** [comment]
Is there any update on svg export? My apology if it is already supported through an extension.

**Comment by jelmerjellema** [comment]
As far as I know there is no update.

There are two roads that people seem to follow:

1. Use a pseudocanvas library like Canvas2Svg (the one I tried) and make the native cytoscape.js code render to this canvas. (using cy.renderer().renderTo(...))
2. Create special code to directly create a svg from the information in cytoscape.

I tried the first route, because the second one is like building a new graph library for svg, including styling etc. I found out the cytoscape uses a lot of bitmap caching for speed, and as you can read above, people have tried to hack the renderer to forget the caches. What I did was just create a new cytoscape instance, fill this with the same elements - cy2.json(cy1.json()); - and  render this to the pseudocanvas.

This kind of worked, but not enough. The real problem in our project was, that we use SVG background images for nodes. These are rendered by CytoscapeJs using canvas.drawImage, with as argument an <img src="url for svg background">. At this point, any SVG paths are already turned into bitmaps, so the final SVG will contain a bitmapped image in the right dimensions for the current zoom. Not scalable at all...

So I am ready to give up on this. The alternative might be finding a good way to export a PNG in a given resolution. 

The only thing I can think of right now (using route 1) is make the cytoscape renderer render svg images not through an image tag, but by converting the SVG into canvas. Maybe through Path2D (https://developer.mozilla.org/en-US/docs/Web/API/Path2D/Path2D) or some library?

**Comment by gexiaowei** [comment]
@jelmerjellema I try your way to use your code
`var ctx = new C2S(1000,1000);
cy.renderer().renderTo( ctx);
var mySerializedSVG = ctx.getSerializedSvg();`
it has no error happend, but it just output and svg with base64 encode image
I just want to know if I can output an svg with nodes

**Comment by maxkfranz** [comment]
Trying to use any of the automatic canvas-to-svg conversion libs isn't going to work.  It was only semi-working when cyjs just directly drew everything with the canvas fill/stroke apis.  Now cyjs is more advanced.  In future, cyjs will use webgl in places.  At this point, using a canvas-to-svg is unrealistic and hacky.

The only way to have this working is to build a svg exporter extension that builds up svg objects based on the stylesheet and the other computed style values (like bezier points).

Please keep further discussion in this thread on the topic of an exporter extension for svg.

**Comment by zfrenchee** [comment]
@maxkfranz I just downloaded cytoscape and it seems like this is a feature on the current release. Might be suitable to close this issue. Thanks for providing this feature!

**Comment by VGSebastian** [comment]
@zfrenchee I don't see any mention of this in the release notes or other documentation of cytoscape.js. Are you maybe confusing cytoscape.js and cytoscape? The former is a JavaScript library while the latter is a standalone desktop app. See also http://manual.cytoscape.org/en/stable/Cytoscape.js_and_Cytoscape.html

**Comment by zfrenchee** [comment]
My mistake @VGSebastian!

**Comment by cancerberoSgx** [comment]
Hi, I just arrived to the conversation, but I would also in investigate using dagre graphlib / dot file format  .(https://github.com/dagrejs) file format. Since the library already renders to dagre, would not be possible to extract the .dot file or graphlib representation ? . If so then it could be translated to a .doc file or to a .good quality svg.
 
Dagre itself won't render but  this project http://viz-js.com/, (emsripten port of graphbi) will render graphlib/.dot to  svg

Again, I'm new on these libraries and don't know the status of the project although the demo looks nice, but it could help people that just need to transform graphs offline. Regarding this, my advice would be not to invest trying to transform canvas/bitmaps to svg..My two cents. will try to investigate more, thanks
