### ISSUE TITLE
Animated expanding/collapsing nodes demo

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#735]
This project would entail the creation of a demo that includes expanding and collapsing subgraphs.  The graph content would be well suited to social data or the relationships between people with some sort of hierarchy (e.g. political groups, companies, etc).

It would be interesting if this demo used more regular, consistent means of expanding and collapsing, like the circle layout with animation, rather than a physics simulation.  

This would be a good demo to use with the Dagre layout, especially if the graph content were hierarchical.

**Comment by srmocher** [comment]
I am currently implementing something similar for visualizing Wikipedia category hierarchy (it's more of a Directed graph than a tree) for any particular subject. It's not a finished implementation but I thought it was worth sharing it since I've implemented some of the interactions you've specified. The link is [http://wikigraph.azurewebsites.net/index.html](url). There are four types of nodes here - blue (categories), brown ellipsis (more categories), green (pages), yellow ellipsis (more pages). Since nodes expand and the graphs become dense and overlap with each other, I have added interaction to drag a center and it's direct children. Other main interactions include expanding (left click) and collapsing (right click). I would be interested to know your thoughts.
