### ISSUE TITLE
Edge (rendering) approach angle to/from a node

### ISSUE THREAD

**Issue by nmorse** [cytoscape/cytoscape.js#783]
I would like to specify (or hint at) the angle of approach of an edge coming into (or out of) a node.
Possibly edge attributes `source_angle` and `target_angle` would either control or hint this to the renderer.

**Comment by maxkfranz** [comment]
Good idea, though this could apply only to bezier curve edges.  Would that suit your usecase?

**Comment by nmorse** [comment]
Yes, only bezier curve edges, that makes sense and is within my usecase. I also understand that this may cause some odd visual arrangements if nodes are not placed accordingly. But if it helps here is an example: 
![screenshot](https://cloud.githubusercontent.com/assets/25401/5601624/f360b012-92d9-11e4-9ad6-8427a837e65e.png)
I have a self edge that stems out of the top and I was hoping for a side or downward (visual) "flow".

**Comment by maxkfranz** [comment]
That's a good point.  State machines are an important usecase.  Adding to 2.4 milestone

**Comment by maxkfranz** [comment]
Removing from 2.4 milestone due to time constraints.  2.4 has been in the pipeline for a while now...

**Comment by KulvinderSen** [comment]
Hi maxkfranz,
  
  I have attached an image below. I am getting layout shown in image part A) but what I need is layout B). Can you please point me toward the right direction that how can I achieve this?

![cystoscape](https://cloud.githubusercontent.com/assets/12406102/7580982/09c02816-f89b-11e4-9af1-53cc21438427.png)

**Comment by maxkfranz** [comment]
@nmorse For your case, couldn't you reverse the arrow direction on the loops to get the effect you want?

**Comment by tmullen71** [comment]
This is something I'd like to be able to do as well (also for state machines).

**Comment by Lenndev** [comment]
So, this is still on the wishlist?

**Comment by tmullen71** [comment]
I'd still definitely like it.

**Comment by maxkfranz** [comment]
This is similar to the more general issue : https://github.com/cytoscape/cytoscape.js/issues/1219

That issue is being considered for 2.8, but its requirements need to be clarified.  In both that issue and this one, there are invalid/undesirable rendering results to consider:  It's easy to create bad results if you can specify position and/or angle.  

Further, this wouldn't work well with freeform graphs.  It would work with only heavily restricted or static graphs.

There are already a lot of high priority items (like performance-related enhancements) for 2.8, so  I'm not sure that issue will make it into 2.8.

**Comment by tmullen71** [comment]
I can see how too much freedom could result in problems. For me, it would be nice just to be able to set edges to loop up (emerging at NW and entering at NE, for example) or left, right, or bottom, rather than always looping to the northwest (ie. emerging at N and entering at W).

**Comment by tonymullen** [comment]
In case anybody's interested, I've solved this for my own purposes by making a local alteration in Cytoscape starting at line 12803 (in version 2.6.7) as follows: 

```
        //rs.ctrlpts = [
        //  srcPos.x,
        //  srcPos.y - (1 + Math.pow(srcH, 1.12) / 100) * loopDist * (j / 3 + 1),
        //  srcPos.x - (1 + Math.pow(srcW, 1.12) / 100) * loopDist * (j / 3 + 1),
        //  srcPos.y
        //];

        // my loop alteration
        rs.ctrlpts = [
          srcPos.x + (0.4)*(1 + Math.pow(srcH, 1.12) / 100) * loopDist * (j / 3 + 1),
          srcPos.y - (0.6)*(1 + Math.pow(srcH, 1.12) / 100) * loopDist * (j / 3 + 1),
          srcPos.x - (0.4)*(1 + Math.pow(srcW, 1.12) / 100) * loopDist * (j / 3 + 1),
          srcPos.y - (0.6)*(1 + Math.pow(srcW, 1.12) / 100) * loopDist * (j / 3 + 1)
        ];
```

If you have suggestions for how I could incorporate a change like this in a way that was consistent with the design goals of the project I'd be happy to work on integrating it and making a pull request, otherwise I can keep my changes local.

**Comment by maxkfranz** [comment]
@tonymullen That looks great!  We'd need style properties to control it.  My intuition is that this would only apply to loops and compound loops, as setting angles for regular edges would often give bad results.  Maybe only one style property would be needed, assuming the loops always sweep ~90deg.

**Comment by maxkfranz** [comment]
General impl of this for https://github.com/cytoscape/cytoscape.js/issues/1613

@tonymullen's loop options also work for loops

Both will be in 3.1
