### ISSUE TITLE
Fixed element size (nodes,edges,font) regardless of zoom

### ISSUE THREAD

**Issue by markov00** [cytoscape/cytoscape.js#789]
Is there a way to specify a fixed size for each element regardless of the zoom? on #780 I've found a way to have a fixed node size that you can test [here](http://jsbin.com/hapasuyoni/2/edit?js,output): 
but it has some problems:
- the labels are redrawn only when you are selecting a node or an edge
- the arrow size depend on the initial edge width, but if this width change the edge arrow doesn't change its dimension
- edges curves: we can't control the bezier control point so if the edges are relatively very near each other, the curve is very big.
  I'm asking if there is a different way to create a graph with fixed element size regardless of the zoom level. 
  Think of a big graph that you want to explore like the [tokyo railways demo](http://jsbin.com/gist/f64e811fc3311414e083?js,output), if you zoom in  everything becomes overlapped and unreadable. I think this feature can be very useful.

**Comment by markov00** [comment]
I absolutely agree: my approach was just a workaround, but implementing this at renderer level will be much more efficient and easier for developers.

**Comment by ktei** [comment]
Bump up this. I currently set font-size and node radius based on the count of visible nodes, because when there are only a few nodes, without any adjustment, all nodes and labels become very very big. I can work around with this by tweaking zoom level and style dynamically.

It'd be nice to see that: if a max node radius is specified, then regardless of how many nodes are there, their size won't go beyond the max node radius (which potentially means that the cytoscape would choose a proper zoom level for the graph when it's loaded...?)

Also, it'd be nice to see that: if a max text size is specified, then regardless of how many nodes are there, all the text's size won't go beyond the max value?

I fully understand that at the moment, cytoscape is just trying to fully fill the canvas on loading, but it doesn't look very good when you just have a handful nodes, but each one of them is so large with very big font size.

Thoughts?

**Comment by maxkfranz** [comment]
@ktei For your case, just don't use the `fit` option.  You can instead call `cy.zoom( yourPreferredZoom )` and `cy.center()`.

**Comment by maxkfranz** [comment]
This would actually require some other model on the viewport, like a stretch rather than a zoom.

**Comment by swtyler** [comment]
@maxkfranz Any updates on this? Do you have any suggestions for fixed size labels? Here is an example scenario:

I am monitoring traffic patterns and use cytoscape to graph those patterns. Now I want to overlay the graph onto a map (which we have working). The problem is that when I zoom in, I have almost no control over the label text size. I've found a way around the node size problem - similar to what @markov00 did in the initial post. However, I am stuck working with the label. I want to zoom in, see more of the map, but keep the node shape and label size the same throughout.

I've tried some hacks but they only work *a little* better. I'm not sure why anyone would ever want to keep zooming in on a label.

Thanks for any info!

**Comment by maxkfranz** [comment]
The issue with completely different zoom behaviour is twofold:

(1) It's not really a zoom.  Zoom is defined as graphics zoom/scale.  See Wikipedia for background: https://en.wikipedia.org/wiki/Scaling_%28geometry%29  The behaviour being described in this issue is really a stretch rather than a zoom -- you're stretching the nodes apart but you're not changing the scale.

(2) It completely throws off all calculations for hittests, edge positioning calculations, boundingboxes, layouts, text dimension calculations (which are very, very expensive), and many more things -- because it breaks the assumption that model co-ordinates are constant with zoom and pan.  Untrue zoom/scale behaviour would break all of these and require sweeping changes.  It also means the `textureOnViewport` option wouldn't work.

The solution for this should be done separately in an extension: An extension could modify sizes (e.g. `font-size`, `width`) on  changes in zoom (or possibly debounce to be more performant but less smooth).  The change in font size would be inversely proportional to the zoom to keep the rendered sizes constant.  The extension could have options for what is kept fixed and what is not (labels, nodes, edges).

**Comment by swtyler** [comment]
@maxkfranz Thanks for the response.

We went with what we could do today, changing the font size relative to the zoom. Initially we struggled with this because our minZoom-maxZoom values were so large that the font would have had to be less than 1px in size when zoomed in and/or the font kerning was out of whack. After adjusting the zoom values, it's working well enough.

**Comment by janblok** [comment]
@swtyler Can this cytoscape extension be found anywhere on Github? We are facing the exact same challenge.

**Comment by michalhabala** [comment]
@swtyler the font part is very interesting for me also. Please can you give some more hints or pieces of code that made it possible? Thank you

**Comment by maxkfranz** [comment]
Just use sensible min- and max-zoom values for the stylesheet you use.  

Your initial stylesheet values can be increased or decreased to accommodate the zoom bounds -- as long as the initial sizes are proportional.

**Comment by swtyler** [comment]
We have a custom app with a few setting changes, no plugin necessary.

To add on to what @maxkfranz mentioned (this is pseudocode so bear with me):

// this worked for us compared to a previous min/max like 1-8192 but it's very dependent on your application, the map you're using, etc.
this.cy(minzoom : 0.1, maxzoom : 4.096)

// modify the font based on the zoom
var dim = 12/this.cy.zoom();
var maxDim = Math.max(dim,2);
this.cy.nodes().css('font-size' : maxDim);

**Comment by maxkfranz** [comment]
Not possible with 2.7+

Performance enhancement that cache textures per element or per layer conflict with this.

You're better off creating breakpoints in the zoom where the style is changed appropriately -- just like CSS `@media` query breakpoints.

**Comment by Does666** [comment]
> Property ideas:
> 
> * `element-sizing: fixed | relative`
> * `text-sizing: fixed | relative`

Where set these two properties ?  I didn't find any info about this.

**Comment by nmz787-intel** [comment]
how do I enable this? I have thousands of nodes on my graph, with even more edges.. and while the initial layout (breadthfirst) looks fine (albeit so small the edges and nodes all overlap), when I zoom in to see the detail, the nodes scale in diameter, and still block visibility of the edges!

**Comment by cp-cheung** [comment]
> how do I enable this? I have thousands of nodes on my graph, with even more edges.. and while the initial layout (breadthfirst) looks fine (albeit so small the edges and nodes all overlap), when I zoom in to see the detail, the nodes scale in diameter, and still block visibility of the edges!

I don't think that the 'property ideas' was ever implemented. You can fix your element size by using an eventlistener and css. 
See the following example: 

```
cy.on('zoom', function () {
    let currentZoom = cy.zoom();
    let zoomFactor = 1 / currentZoom;
    let nodeSize = zoomFactor * defaultNodeSize;
    let edgeSize = zoomFactor * defaultEdgeSize;
    let fontSize = nodeSize / 2;

    cy.style()
      .resetToDefault()
      .selector('edge')
      .style('width', edgeSize)
      .selector('node')
      .style('width', nodeSize)
      .style('height', nodeSize)
      .style('font-size', fontSize)
      .style('text-valign', 'center')
      .style('text-halign', 'center')
      .style('label', 'data(id)')
      .update();
});
```
You will need to play around with the defaultNodeSize and defaultEdgeSize.

For more advance usage, replace `1 / currentZoom` with:
`currentZoom < thresholdZoomLevelFixedElements ? 1 : thresholdZoomLevelFixedElements / currentZoom;`

This will retain the default zoom behavior until the threshold is reached. After that the elements size will be fixed.

**Comment by nmz787-intel** [comment]
How to do that in Python dash? The syntax is very different than the javascript version.

**Comment by cp-cheung** [comment]
I have no experience and knowledge of Python dash. I can't help you there. 

A quick look at their [documentation](https://dash.plotly.com/cytoscape/events) suggest that a python dash version of my example should be possible.
