### ISSUE TITLE
Allow to add label background color

### ISSUE THREAD

**Issue by MissChocoe** [cytoscape/cytoscape.js#825]
This could be useful if some labels are overlapping, label with an opaque background color would be easier to read.

**Comment by maxkfranz** [comment]
That makes sense.  Proposed properties:

* `text-background-color` : With the specified colour, places a rectangular background on the label text (no background is used by default or when specified with the value `none`).
* `text-background-opacity` : Specifies the opacity of the label text background colour (fully opaque with a value of `1` by default).

Note that this will have performance concerns as it will increase the number of shapes drawn per element.  However, the expense can be minimised by using sqaure rectangles rather than ones with rounded corners.  What do you think?  If rounded corners are a requirement, then it may merit an additional property.

**Comment by MissChocoe** [comment]
To reduce performance issue, you could put the opacity at 0 by default and then not draw the shape in that case. And I'm sure at some point someone will want rounded corner ;) Might as well put it as an option (but used regular rectangle by default). Properties name make sense.

**Comment by MissChocoe** [comment]
I can actually implement it. :)

**Comment by MissChocoe** [comment]
I've created a pull request with this feature. I decided to let go of the round rectangle to simplify rendering of all that but added the border in addition to background color. So here's the full list of new properties: 

 * **`text-background-color`** : A color to apply on the text background, may be `none` or a valid color.
 * **`text-background-opacity`** : The opacity of the label background.
 * **`text-border-width`** : The border width to put around the label.
 * **`text-border-style`** : The style of the border around the label; may be `solid`, `dotted`, `dashed`, or `double`.
 * **`text-border-color`** : The color of the border around the label.

**Comment by MissChocoe** [comment]
One more property that could be added is text-margin. For now, I've fixed it to 4px so the text is not glue to the border. Maybe we should let user control that.

**Comment by jonorthwash** [comment]
Is this what `"text-background-opacity": 1, "text-background-color": "#ffffff"` is supposed to look like?
![2017-11-19-20 44 50_001](https://user-images.githubusercontent.com/963849/32998595-8d55b51e-cd6a-11e7-961e-9aa156087e50.png)
I'm happy to file a bug report if something is wrong, but that seems to be heavily discouraged if there's any chance I'm just being being stupid, so I decided to assume I was stupid this time.

If the answer is just "ask on stackexchange", that's fine too.
&lt;/stupidity&gt;

**Comment by maxkfranz** [comment]
@jonorthwash It's working fine for me on master (3.2.6) with those two properties:

![screen shot 2017-11-21 at 11 28 48 am](https://user-images.githubusercontent.com/989043/33084159-3838fb72-ceaf-11e7-8042-de0881c4eb42.png)

**Comment by jonorthwash** [comment]
We're using a version from earliest this summer, so that could be it. 

@maryszmary, could you check whether updating cytoscape works?

Otherwise, we might need to make an mwe and file a bug.
