### ISSUE TITLE
Add shadow properties

### ISSUE THREAD

**Issue by MissChocoe** [cytoscape/cytoscape.js#831]
Canvas allow to draw shadow. Cytoscape could use that power. Proposed properties (which are the one available in the canvas, color being transferred to rgba to reflect opacity):

For node/edges:
shadow-blur
shadow-opacity
shadow-color
shadow-offset-x
shadow-offset-y

For labels:
text-shadow-blur
text-shadow-opacity
text-shadow-color
text-shadow-offset-x
text-shadow-offset-y

I have already this all done, just need to transfer to github and make a pull request.

**Comment by maxkfranz** [comment]
It could be, but then again, I have avoided adding that because it doesn't add much utility over the border and text outline and it adds considerable rendering expense -- meaning that people who want to use large graphs wouldn't like it.

People tend to gravitate towards fancy styles like that even though they're often prohibitively expensive, so I've avoided adding blurs and shadows thus far.

Maybe expensive styles should be marked with the red asterisk or similar in the docs.  Most devs ought to avoid them, because performance is so often a high concern.

**Comment by maxkfranz** [comment]
Merged; looking into issue you noted now

**Comment by MissChocoe** [comment]
@maxkfranz Thanks for your fix!

**Comment by maxkfranz** [comment]
Closing for now; let me know if there is anything else.  Thanks again!

**Comment by MissChocoe** [comment]
@maxkfranz  My pleasure! When do you plan on close v2.4? I'll try to download the latest changes to do some testing before the deadline.

**Comment by maxkfranz** [comment]
ASAP so some issues may have to be postponed to a later milestone...
