### ISSUE TITLE
Plotting data series on the Nodes

### ISSUE THREAD

**Issue by AjitPS** [cytoscape/cytoscape.js#862]
Hi, is it possible to plot different <b>bar charts on the nodes</b> in a network generated by CytoscapeJS ?

Is this functionality available, like in <i>cytoscape desktop</i> or does it require the usage of another library like D3.js or dygraphs ?

**Comment by AjitPS** [comment]
Is plotting bar charts or data series on the nodes possible in CytoscapeJS ?

**Comment by maxkfranz** [comment]
That would require adding that feature to the library.  I doubt traditional bar charts would be practical, but stripes could be -- they would be a linear analogue of the pie slices style.

**Comment by AjitPS** [comment]
Thanks Max. Yes, I would ideally like to have a data <b>series</b> on the node plotted using some values specific to the node.

Using your approach (i.e., the pie slices style nodes), would the plotted data series be a new node placed next to the selected node or can it be like a small image placed next to the node ?

**Comment by maxkfranz** [comment]
It would be like a foreground image

**Comment by maxkfranz** [comment]
It makes sense for the `pie-*` properties, since they can be used for decorations.  For more complex charts, it really doesn't make sense to introduce more properties/styles.  Instead, it would make sense to use a library dedicated for the chart you want to export a SVG file.  That SVG can be used as a node's background image.
