### ISSUE TITLE
Bezier edges don't render from parent to child

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#866]

**Comment by maxkfranz** [comment]
This adds a looplike edge for this case

**Comment by rasmushandersen** [comment]
Hi,

I see you fixed the bug, thanks. I still think there is room for improvement though. When Connecting from a child to a parent, i would suggest (and assume) that the connecting is made to the inside of the parent and not the outside. Currently the connection from the child to a parent seems really distracting and the compound node is not "self-contained" as the connections goes out of the parent. 

I hope you understand what i try to convey, otherwise please ask..

\Rasmus

**Comment by maxkfranz** [comment]
A connection from parent to child or vice versa must loop in order for the edge to point to the outside of the parent and to the outside of the child.  A straight edge or similar would not meet this requirement, and so it would look incorrect.  If you try drawing things out on paper, you'll see what I mean.

In any case, any more complex edge type for this case would have to wait until a future version.  At soonest 2.5.
