### ISSUE TITLE
Why do I have to render everything all at once?

### ISSUE THREAD

**Issue by jonathanmarvens** [cytoscape/cytoscape.js#877]
I'm currently working with a network of ~1,700 nodes and ~252,000 edges. Even though it can take a few seconds, the data loads fine in the browser. I know this is relatively large amount of data for the browser, but IME so far, Cytoscape.js is super slow and crashes its browser thread most of the time, even with about 1,000 nodes and 3,000 or so edges (which isn't much for anything realistic). I think part of this issue has to do with having to render everything at once. I want to render an initial layout and add nodes and edges as necessary (such as per animation frame) and work with it efficiently (i.e., without re-rendering the entire network). It doesn't seem this is possible with Cytoscape.js. Is it?

I'm just about to give up on Cytoscape.js, but I thought I'd ask here in case there's something I'm missing.

Much thanks in advance!

**Comment by jonathanmarvens** [comment]
For example, I'd like to be able to do something like this.

```javascript
cytoscapeOptions.ready = function () {
  let aF
  let i00
  let j00
  let networkManager

  networkManager = this

  // From: https://github.com/kof/animation-frame ...
  aF = new animationFrame()

  // Add the nodes.
  for (i00 = 0, j00 = data.nodes.length; i00 < j00; i00++) {
    (function (n00) {
      aF.request(function () {
        networkManager.add({
          data: data.nodes[n00],
          group: 'nodes',
        })

        // For garbage collection.
        data.nodes[n00] = null
      })
    })(i00)
  }

  // Add the edges.
  for (i00 = 0, j00 = data.edges.length; i00 < j00; i00++) {
    (function (n00) {
      aF.request(function () {
        networkManager.add({
          data: data.edges[n00],
          group: 'edges',
        })

        // For garbage collection.
        data.edges[n00] = null
      })
    })(i00)
  }
}
```

**Comment by ktei** [comment]
@jonathanmarvens I actually think the performance of cytoscape is relatively good. If you have a look at its source code, it uses some techniques to increase performance, for example, cache data, try its best to avoid redraw etc.

Here are some facts that may help:
1. Consider to use simpler styles. The more complicated your styles are, the slower the graph gets rendered, simple as that.
2. Regardless of how you render your graph, in the end, as long as you have that many nodes/edges on canvas, the framework HAS to draw that many at one time, because that's what canvas about: drawing things.
3. Check the documentation and it has a detailed section telling you how to increase performance.

Hope it helps.

**Comment by maxkfranz** [comment]
You also don't have to render everything at once.  That is under your control:

(1) Don't add elements until you need them displayed.

(2) Even if elements are previously added, you can use the stylesheet and classes or data to set whether certain elements are visible.  Invisible elements add very little rendering cost.

If you maximise your [performance](http://js.cytoscape.org/#performance), then you're running into bottlenecks on your browser and hardware.  There's nothing we can do for those bottlenecks, as they are out of our control.
