### ISSUE TITLE
Calling layout.stop() on continuous layouts doesn't stop them

### ISSUE THREAD

**Issue by jsalankey** [cytoscape/cytoscape.js#938]
I've been playing with the makeLayout() API and running infinite versions of Arbor and Cola and I'm finding that the layouts don't actually stop when you tell them to. The webworkers for Arbor are not cleaned up (i.e. I can still see them in my dev tools) and the layout will continue to try to position my nodes. The computerDerivatives and positionNodes functions for Cola continue to be called even after I stop them.

This would be less of a problem if it was possible to add nodes to a layout once it was started, but that is also not possible as far as I can tell. You have to stop and restart it with the new collection if you add or remove nodes.

**Comment by maxkfranz** [comment]
Adding and removing elements in a layout directly was considered for 2.4, but didn't make it in -- hence that architecture.  Also considered was the possibility of resuming a stopped layout, with a `.pause()` alias on `.stop()`.  Because Arbor uses its own internal web workers, it is not possible to destroy its worker from outside.  The spread layout uses the threads from Weaver.js, so [destroying may bve possible in 2.5](https://github.com/cytoscape/cytoscape.js/issues/947).

Those changes will probably make it into 2.5.

As for Cola : https://github.com/cytoscape/cytoscape.js/issues/948

Does this make sense?

**Comment by maxkfranz** [comment]
Closing as Cola has since been fixed and we can't control the webworkers of Arbor.  In any case, Arbor is only included for historical, backwards compatibility reasons.  There are better layouts.
