### ISSUE TITLE
Moving an element should select it

### ISSUE THREAD

**Issue by sylvain-hamel** [cytoscape/cytoscape.js#951]
**Steps to reproduce :**

- Set a css style for `:selected` to see the selected elements (set color to blue)
- Tap an element
- It becomes blue
- Tap and move another element

**Actual result :** The old elements has the selected state.
**Expected result :** The 1st elements should no longer be selected and the one that was moved should now be selected.

**Comment by maxkfranz** [comment]
In step (4), you say "tap and drag".  Do you mean (A) tap then drag or (B) tapstart and drag?

(A) behaves as you expect, whereas (B) does not.  Selection is not standard on (B), because there is no tap -- it's an incomplete tap with only tapstart (in the tapstart, tapend, tap sequence).

If you want selection to happen outside of tap events, you can bind to those events and manipulate the selection state as you wish at that point.  Does that make sense?

**Comment by rui-infotrack** [comment]
I don't think this is actually necessary. As I see, moving a node is different from selecting a node. So basically, when you move (drag) a node, it doesn't need to be selected automatically, because maybe all I want is just to move it somewhere. When I DO want to select a node, I single click on (touch) it to make it selected.

**Comment by sylvain-hamel** [comment]
I tested the same on my Windows Desktop by dragging files, then on my Mac by dragging files too and then in the Microsoft Visio application by dragging objects. And all cases, the newly moved object changes to the `selected` state as soon as I `mouse down` on it. I think this is the most common behavior.

**Comment by maxkfranz** [comment]
You can add a bit of logic to make selection happen on `tapstart`, though you will still get selection behaviour on `tap` (though the end effect is the same).  As for whether it's preferable UI, I'm not so sure.  Whereas `tapstart` selection can never be cancelled, in `tap` selection the user can back out at the last moment by dragging the node a bit rather than tapping it -- which is a common UI mechanism on things like buttons, menu items, etc.

**Comment by maxkfranz** [comment]
Closing for now, as I don't think this should be default behaviour
