### ISSUE TITLE
while scrolling the div nodes & edges is not properly rendering . while zoom out it renders correctly

### ISSUE THREAD

**Issue by nellaiiyappan** [cytoscape/cytoscape.js#953]

**Comment by maxkfranz** [comment]
Would you please provide an example (e.g. jsbin)?

**Comment by maxkfranz** [comment]
Or could you describe the issue a bit more in-depth with an example graph as a reference point?

**Comment by maxkfranz** [comment]
Is this issue still in 2.4.1 for you?  I think this may be related if you are using haystack edges:

https://github.com/cytoscape/cytoscape.js/issues/956

**Comment by nellaiiyappan** [comment]
Max,
Yes this issue still in 2.4.0 while using the preset . we need the scroll for layout. I have attached the source code with this 
https://gist.github.com/anonymous/5e524a6f7631e75fbb6a
Please advise me on this.

**Comment by maxkfranz** [comment]
(1) The example doesn't work for me

(2) After trying to fix the example, it's impossible to scroll.

(3) You shouldn't apply `overflow` to your cy div.  That will not work.  You may be able to have a parent div with `overflow: auto`, but the scroll will not pan your graph.  Those are separate mechanisms.

(4) If you play around with the inner contents of the cy div, you will get unexpected results.  It's like modifying private data -- the behaviour is unexpected.

(5) See also https://github.com/cytoscape/cytoscape.js/issues/721

Does this make sense?

Closing for now, because there isn't really anything we can do on the Cy.js side for this.  It's necessary to reconsider the structure/hierarchy of your layout.
