### ISSUE TITLE
Hyperedges

### ISSUE THREAD

**Issue by proteneer** [cytoscape/cytoscape.js#959]
I'm looking for guidance on the best way to visualize/draw hyperedges. The Java version of cytoscape seems to support this from the API level directly, but I couldn't quite figure out how this works with cytoscape. One could make fake intermediate nodes that act as a hyperedge-node of sorts, but it's kind of wonky. Open to suggestions.

**Comment by jsalankey** [comment]
Is a hyperedge just a grouping of all links between the two same nodes? 

In the application I work on using Cytoscape, I would have great use for an automated mechanism for grouping edges together based on a bucketing field. I am currently doing it in my own code and building Cytoscape edge elements out of my own group objects, but it's a cumbersome data model that doesn't mesh well with Cytoscape, and a native implementation would be extremely helpful. It significantly reduces the amount of rendered edges, unclutters the graph, and conveys the importance of an edge if you weight it by multiplicity.

**Comment by maxkfranz** [comment]
A hyperedge is an n:n edge, whereas a regular edge is a 1:1 edge.  That is, a hyperedge can have multiple sources and multiple targets.  This has been considered before, but has not been planned due to complications and conflicts it would have on the API.  A thorough analysis would be required.

Merging (which is what I think the desktop app does), is completely different.  That can be simulated by representing each set of parallel edges as a single edge.  Merging can be done in a straightforward way in your app level code, whereas hyperedges require API level support.

**Comment by jhonatandarosa** [comment]
We created a plugin to merge edges between two nodes.
I think it's not good yet, but we plan to create a public repository for it ASAP.
For now you can take a look here:
https://gist.github.com/jhonatandarosa/6bdab4f9020593901176
