### ISSUE TITLE
About FPS

### ISSUE THREAD

**Issue by rui-infotrack** [cytoscape/cytoscape.js#984]
@maxkfranz , I recently downloaded Fraps, and now I can detect the frame rate for canvas. I found that for an easy graph using cytoscapejs, the FPS is about 30, for example, http://js.cytoscape.org/demos/aedff159b0df05ccfaa5/

Don't get me wrong, because I'm more like curious, not complaining here. So if you have a look at this:
http://datavisualizationsoftwarelab.com/en/products/net-chart/

Its FPS is 60, and to be honest I don't think they're doing anything quite different or special, but I'm wondering could cytoscape hit 60 FPS? or is there any reason that it stays at 30 at the moment.

**Comment by maxkfranz** [comment]
We alter the regular flow of rendering for performance:

(1) The rendering rate is altered based on how fast you can draw so the period to draw is consistent (i.e. smoother).

(2) Rendering happens on demand.  Unnecessary (i.e. no change) frames are dropped.

(3) Related to (1) and (2), we make intermittent calls to `requestAnimationFrame()`.

(4) Rendering is prioritised to get the last frame in as quickly as possible (e.g. during user events like drag).  This ensures that the elements keep up with the user's cursor or finger.

(5) User events are rate limited to ~30 per second.  This avoid redundant calculations (overhead) and makes less powerful hardware more user responsive (especially on ARM touch devices like iPad). Because of this and (2)+(4), you'll get maximum 30 updates per second on user events like drag.

Because of this, it's difficult to accurately measure framerate for Cy.js in general. You may be running into (5), since the easiest way to test is to drag elements to get redraws to happen.  I think animations should be 60 FPS, but I'm not entirely sure.  In any case, I don't think a tool will be able to give an accurate depiction of the rendering speed.

If you set in your init options the following, you'll get a slightly closer approximation to how fast rendering is going:

```
    renderer: {
      name: 'canvas',
      showFps: true
    },
```

Warning: This option is undocumented, and not meant to be used in production.  It could change in future.

**Comment by rui-infotrack** [comment]
Thank you @maxkfranz That helped a lot.

**Comment by maxkfranz** [comment]
OK; closing for now
